---
title: "OpenTarget_gene_sets_all_traits"
output: html_document
author: "Aaron Kollotzek and Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
---

Load libraries
```{r}
library(STutility)
library(dplyr)
library(tidyverse)
library(reshape2)
```



Load OpenTarget files: OBS! Update file location for relevant OpenTargets files
```{r}
get_opentarget <- function (opentarget_dir = paste0(getwd(),"/OpenTargets/all_traits"), mouse_genes = NULL ){
  OT.files <- list()
  disease.names <- character()
  i <- 1
  column.names <- c("Gene_symbol","Overall_assoc.score","Genetic_assoc.","Somatic_mutation","Drugs","Pathways_system_biology","Text_mining","RNA_expression","Animal_models","Target_name")
  
  if (!is.null(mouse_genes)){
    

      conversion.table <- read.table(mouse_genes,
                                     sep = "\t",
                                     header = TRUE) 
      #if mouse_genes dataframe is specified, load it

  }
  
  for (OT.file in list.files(opentarget_dir)){
    if (grepl("diseases_", OT.file)){
      print(OT.file)
  
      df <- read.table(paste(opentarget_dir, OT.file, sep= "/"),
                     sep= "\t",
                     header=TRUE,
                     quote = "")
    
      names(df) <- column.names  # rename columns
      
      df[df == "No data"] <- NA #Re-name N/A
    
      
    
      names(df) <- column.names  # rename columns
      
      df[df == "No data"] <- NA #Re-name N/A
      
      if (!is.null(mouse_genes)){
        df$Gene_symbol <- conversion.table[match(df$Gene_symbol,conversion.table$hgnc_symbol),]$mgi_symbol #convert human to mouse annotation
        OT.files[[i]] <- df
        } else {
          OT.files[[i]] <- df
        }
      i <- i+1
      disease.name <- sub(".*diseases_","", OT.file)
      disease.name <- gsub(".tsv", "", disease.name)
      disease.names <- append(disease.names, disease.name)
    }
  }

  names(OT.files) <-  disease.names
  OT.files <- map(OT.files, ~.x %>%
                    distinct())
  return(OT.files)
}
```

OBS! Update file location for relevant OpenTargets files
```{r}
OpenTargets.path <- "OpenTargets/all_traits"
OT.files.human <-get_opentarget(opentarget_dir = OpenTargets.path)
```

#Removes duplicates
```{r, clean OT.files.human from duplicates}
OT.files.human <- map(OT.files.human, ~.x %>%
  dplyr::select(Gene_symbol, Overall_assoc.score, Genetic_assoc.,Drugs, Animal_models)%>%
  distinct() %>%
  group_by(Gene_symbol)%>%
  slice(which.max(Overall_assoc.score))%>% #==> when there is a gene mentioned twice, only keep the row where the overall association score is the highest ==> reason for duplicates is that multiple human genes have the same mouse homolog etc...
    ungroup())

# saveRDS(OT.files.human, file = paste("OpenTargets", sample,"OT_files_list.rds", sep = "/"))


```

Gene sets for HUMAN
```{r, create gene sets from the }
all_gene_sets <- list()
list.names <- character()
i <- 1
j <- 1
for (df in OT.files.human){
  ## Genes overall association score
  OpenTarget_Overall_assoc.score_xxx <- arrange(df, desc(Overall_assoc.score))
  OpenTarget_Overall_assoc.score_xxx <- OpenTarget_Overall_assoc.score_xxx[!is.na(OpenTarget_Overall_assoc.score_xxx$Overall_assoc.score),]$Gene_symbol
  ## Genes genetic association score
  OpenTarget_Genetic_assoc._xxx <- arrange(df, desc(Genetic_assoc.))
  OpenTarget_Genetic_assoc._xxx <- OpenTarget_Genetic_assoc._xxx[!is.na(OpenTarget_Genetic_assoc._xxx$Genetic_assoc.),]$Gene_symbol
  print(length(OpenTarget_Genetic_assoc._xxx))
  ## Genes drug target
  OpenTarget_Drugs_xxx <- arrange(df, desc(Drugs))
  # print(dim(OpenTarget_Drugs_xxx_top100_[!is.na("Drugs"),]))
  OpenTarget_Drugs_xxx <- OpenTarget_Drugs_xxx[!is.na(OpenTarget_Drugs_xxx$Drugs),]$Gene_symbol
  all_gene_sets[[i]] <- unique(OpenTarget_Overall_assoc.score_xxx)
  all_gene_sets[[i+1]] <- unique(OpenTarget_Genetic_assoc._xxx)
  all_gene_sets[[i+2]] <- unique(OpenTarget_Drugs_xxx)
  list.names <- append(list.names,(c(gsub("xxx", names(OT.files.human[j]),"OpenTarget_Overall_assoc.score_xxx"),
                            gsub("xxx", names(OT.files.human[j]),"OpenTarget_Genetic_assoc._xxx"),
                            gsub("xxx", names(OT.files.human[j]),"OpenTarget_Drugs_xxx"))))
  j <- j+1
  i <- i+3
}
names(all_gene_sets) <- list.names
```


Subsetting list to only Genetic and Drugs gene lists
```{r}
patterns <- c("Genetic","Drugs")

all_gene_sets <- all_gene_sets[grep(
  paste(patterns, collapse = "|"),
  names(all_gene_sets),
  ignore.case = TRUE
  )]
```

Removing empty terms
```{r}
all_gene_sets$OpenTarget_Drugs_total_cholesterol_measurement_v23.06
all_gene_sets$OpenTarget_Drugs_total_cholesterol_measurement_v23.06 <- NULL
all_gene_sets$OpenTarget_Drugs_low_density_lipoprotein_cholesterol_measurement_v23.06
all_gene_sets$OpenTarget_Drugs_low_density_lipoprotein_cholesterol_measurement_v23.06 <- NULL
```

Jaccard function:
```{r}
jaccard <- function(a, b) {
  intersection = length(intersect(a, b))
  union = length(a) + length(b) - intersection
  return (intersection/union)
}
```


Print all genes shared combinations:
```{r}
# två for-loopar
# Börja med att skapa en tom matrix med lika många kolumner som rader
# kolumn- och rad-namn ska vara samma som namnen på hallmark gene sets
length.mat <- matrix(data = NA, 
                  nrow = length(all_gene_sets), 
                  ncol = length(all_gene_sets), 
                  dimnames = list(names(all_gene_sets), 
                                  names(all_gene_sets)))


# Iterera över två for-loopar, en för rader och en för kolumner
for (i in 1:length(all_gene_sets)) {
  for (j in 1:length(all_gene_sets)) {
    # Spara jaccard mellan par av gene sets
    length.mat[i, j] <- jaccard(all_gene_sets[[i]],all_gene_sets[[j]])
  }
}


```


```{r, fig.height=12, fig.width=14}
length.mat.df <- as.data.frame(length.mat)

library(tidyverse)

df2 <- length.mat.df %>%
  rownames_to_column() %>%
  gather(colname, value, -rowname)
head(df2)

df2$value <- ifelse(df2$rowname == df2$colname, NA, df2$value)

ggplot(df2, aes(x = rowname, y = colname, fill = value)) +
  geom_tile()
```

Re-format plot

```{r, fig.height=12, fig.width=14}
# Get lower triangle of the correlation matrix
  get_lower_tri<-function(length.mat){
    length.mat[upper.tri(length.mat)] <- NA
    return(length.mat)
  }
  # Get upper triangle of the correlation matrix
  get_upper_tri <- function(length.mat){
    length.mat[lower.tri(length.mat)]<- NA
    return(length.mat)
  }


# Reorder function
reorder_length.mat <- function(length.mat){
# Use correlation between variables as distance
dd <- as.dist((1-length.mat)/2)
hc <- hclust(dd)
length.mat <-length.mat[hc$order, hc$order]
}

# Reorder the correlation matrix
length.mat <- reorder_length.mat(length.mat)
#lower_tri <- get_lower_tri(length.mat)
# Melt the correlation matrix
melted_length.mat <- melt(length.mat, na.rm = TRUE)
melted_length.mat$value <- ifelse(melted_length.mat$Var1 == melted_length.mat$Var2, NA, melted_length.mat$value)
# Create a ggheatmap
ggheatmap <- ggplot(melted_length.mat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, space = "Lab", 
    name="Jaccard index", limits=c(0,1)) +
  theme_minimal()+ # minimal theme
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()#+
  #geom_text(aes(label = round(value, 2)))

# Print the heatmap
ggheatmap + ggtitle("All traits")
```




```{r, fig.height=12, fig.width=14}
# Get lower triangle of the correlation matrix
  get_lower_tri<-function(length.mat){
    length.mat[upper.tri(length.mat)] <- NA
    return(length.mat)
  }
  # Get upper triangle of the correlation matrix
  get_upper_tri <- function(length.mat){
    length.mat[lower.tri(length.mat)]<- NA
    return(length.mat)
  }


# Reorder function
reorder_length.mat <- function(length.mat){
# Use correlation between variables as distance
dd <- as.dist((1-length.mat)/2)
hc <- hclust(dd)
length.mat <-length.mat[hc$order, hc$order]
}

# Reorder the correlation matrix
length.mat <- reorder_length.mat(length.mat)
#lower_tri <- get_lower_tri(length.mat)
# Melt the correlation matrix
melted_length.mat <- melt(length.mat, na.rm = TRUE)
melted_length.mat$value <- ifelse(melted_length.mat$Var1 == melted_length.mat$Var2, NA, melted_length.mat$value)
# Create a ggheatmap
ggheatmap <- ggplot(melted_length.mat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, space = "Lab", 
    name="Jaccard index") +
  theme_minimal()+ # minimal theme
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1))+
 coord_fixed()#+
  #geom_text(aes(label = round(value, 2)))

# Print the heatmap
ggheatmap + ggtitle("All traits")
```

PDF
```{r}
pdf(file = "OpenTarget_gene_sets_all_traits_Jaccard_index.pdf", width = 15, height = 15)

ggheatmap + ggtitle("All traits")

dev.off()
```

SessionInfo
```{r}
sessionInfo()
```

