---
title: "QC_ST_data_overview"
output: html_document
date: "2024-02-27"
---

NOTE: Plots Supplementary Figure 6 a and b.

# Load libraries
```{r}
library(STutility)
library(ggplot2)
library(tidyverse)
library(hrbrthemes)
library(viridis)
library(RColorBrewer)
```


# Load ST datasets  {.tabset}

## Brain
```{r}

## brain_human_151509
infoTable_brain_human_151509 <- read.csv("Brain/Human_brain_DLPFC_151509/spatial_data/infoTable_2.csv", sep = ";")

se_brain_human_151509 <- InputFromTable(infotable = infoTable_brain_human_151509, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_brain_human_151509$dataset <- "brain_human_151509"
median(se_brain_human_151509$nFeature_RNA)
median(se_brain_human_151509$nCount_RNA)

## brain_human_151673
infoTable_brain_human_151673 <- read.csv("Brain/Human_brain_DLPFC_151673/spatial_data/infoTable_2.csv", sep = ";")

se_brain_human_151673 <- InputFromTable(infotable = infoTable_brain_human_151673, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_brain_human_151673$dataset <- "brain_human_151673"
median(se_brain_human_151673$nFeature_RNA)
median(se_brain_human_151673$nCount_RNA)

## brain_mouse_10X
infoTable_brain_mouse_10X <- read.csv("Brain/10X_Visium_mouse_brain_coronal/spatial_data/infoTable_2.csv", sep = ";")

se_brain_mouse_10X <- InputFromTable(infotable = infoTable_brain_mouse_10X, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_brain_mouse_10X$dataset <- "brain_mouse_10X"
median(se_brain_mouse_10X$nFeature_RNA)
median(se_brain_mouse_10X$nCount_RNA)

## brain_mouse_cell2location
infoTable_brain_mouse_cell2location <- read.csv("Brain/Cell2location_Visium_mouse_brain_coronal_1/spatial_data/infoTable_2.csv", sep = ";")

se_brain_mouse_cell2location <- InputFromTable(infotable = infoTable_brain_mouse_cell2location, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_brain_mouse_cell2location$dataset <- "brain_mouse_cell2location"
median(se_brain_mouse_cell2location$nFeature_RNA)
median(se_brain_mouse_cell2location$nCount_RNA)

```


## Heart
```{r}

## adult_ACH003
infoTable_heart_human_adult_ACH003 <- read.csv("Heart/adult_ACH003/spatial_data/infoTable_2.csv", sep = ";")

se_heart_human_adult_ACH003 <- InputFromTable(infotable = infoTable_heart_human_adult_ACH003, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_heart_human_adult_ACH003$dataset <- "heart_human_adult_ACH003"
median(se_heart_human_adult_ACH003$nFeature_RNA)
median(se_heart_human_adult_ACH003$nCount_RNA)

## adult_ACH004
infoTable_heart_human_adult_ACH004 <- read.csv("Heart/adult_ACH004/spatial_data/infoTable_2.csv", sep = ";")

se_heart_human_adult_ACH004 <- InputFromTable(infotable = infoTable_heart_human_adult_ACH004, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_heart_human_adult_ACH004$dataset <- "heart_human_adult_ACH004"
median(se_heart_human_adult_ACH004$nFeature_RNA)
median(se_heart_human_adult_ACH004$nCount_RNA)

## pcw6.5_nr8
se_heart_human_pcw6.5_nr8 <- readRDS(file = "Heart/pcw6.5_nr8/spatial_data/se_8.RDS")

se_heart_human_pcw6.5_nr8$dataset <- "heart_human_pcw6.5_nr8"
se_heart_human_pcw6.5_nr8
median(se_heart_human_pcw6.5_nr8$nFeature_RNA)
median(se_heart_human_pcw6.5_nr8$nCount_RNA)

## pcw9_nr16
se_heart_human_pcw9_nr16 <- readRDS(file = "Heart/pcw9_nr16/spatial_data/se_16.RDS")

se_heart_human_pcw9_nr16$dataset <- "heart_human_pcw9_nr16"
se_heart_human_pcw9_nr16
median(se_heart_human_pcw9_nr16$nFeature_RNA)
median(se_heart_human_pcw9_nr16$nCount_RNA)

```


## Intestine
```{r}
## adult_HFGA_A1
infoTable_intestine_human_adult_HFGA_A1 <- read.csv("Intestine/adult_HFGA_A1/spatial_data/infoTable_2.csv", sep = ";")

se_intestine_human_adult_HFGA_A1 <- InputFromTable(infotable = infoTable_intestine_human_adult_HFGA_A1, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_intestine_human_adult_HFGA_A1$dataset <- "intestine_human_adult_HFGA_A1"
median(se_intestine_human_adult_HFGA_A1$nFeature_RNA)
median(se_intestine_human_adult_HFGA_A1$nCount_RNA)

## adult_RRST_349_B1
infoTable_intestine_human_adult_RRST_349_B1 <- read.csv("Intestine/adult_RRST_349_B1/spatial_data/infoTable_2.csv", sep = ";")

se_intestine_human_adult_RRST_349_B1 <- InputFromTable(infotable = infoTable_intestine_human_adult_RRST_349_B1, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_intestine_human_adult_RRST_349_B1$dataset <- "intestine_human_adult_RRST_349_B1"
median(se_intestine_human_adult_RRST_349_B1$nFeature_RNA)
median(se_intestine_human_adult_RRST_349_B1$nCount_RNA)

## pcw12_HFGA_A8
infoTable_intestine_human_pcw12_HFGA_A8 <- read.csv("Intestine/pcw12_HFGA_A8/spatial_data/infoTable_2.csv", sep = ";")

se_intestine_human_pcw12_HFGA_A8 <- InputFromTable(infotable = infoTable_intestine_human_pcw12_HFGA_A8, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_intestine_human_pcw12_HFGA_A8$dataset <- "intestine_human_pcw12_HFGA_A8"
median(se_intestine_human_pcw12_HFGA_A8$nFeature_RNA)
median(se_intestine_human_pcw12_HFGA_A8$nCount_RNA)

## pcw19_HFGA_A4
infoTable_intestine_human_pcw19_HFGA_A4 <- read.csv("Intestine/pcw19_HFGA_A4/spatial_data/infoTable_2.csv", sep = ";")

se_intestine_human_pcw19_HFGA_A4 <- InputFromTable(infotable = infoTable_intestine_human_pcw19_HFGA_A4, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_intestine_human_pcw19_HFGA_A4$dataset <- "intestine_human_pcw19_HFGA_A4"
median(se_intestine_human_pcw19_HFGA_A4$nFeature_RNA)
median(se_intestine_human_pcw19_HFGA_A4$nCount_RNA)

## mouse_healing_ctrl
infoTable_intestine_mouse_healing_ctrl <- read.csv("Intestine/mouse_healing_ctrl/spatial_data/infoTable_2.csv", sep = ";")

se_intestine_mouse_healing_ctrl <- InputFromTable(infotable = infoTable_intestine_mouse_healing_ctrl, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_intestine_mouse_healing_ctrl$dataset <- "intestine_mouse_healing_ctrl"
median(se_intestine_mouse_healing_ctrl$nFeature_RNA)
median(se_intestine_mouse_healing_ctrl$nCount_RNA)

```

## Kidney

```{r}
## human_JCI
infoTable_kidney_human_JCI <- read.csv("Kidney/human_JCI/spatial_data/infoTable_2.csv", sep = ";")

se_kidney_human_JCI <- InputFromTable(infotable = infoTable_kidney_human_JCI, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_kidney_human_JCI$dataset <- "kidney_human_JCI"
median(se_kidney_human_JCI$nFeature_RNA)
median(se_kidney_human_JCI$nCount_RNA)

## mouse_10X
infoTable_kidney_mouse_10X <- read.csv("Kidney/mouse_10X_coronal/spatial_data/infoTable_2.csv", sep = ";")

se_kidney_mouse_10X <- InputFromTable(infotable = infoTable_kidney_mouse_10X, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_kidney_mouse_10X$dataset <- "kidney_mouse_10X"
median(se_kidney_mouse_10X$nFeature_RNA)
median(se_kidney_mouse_10X$nCount_RNA)

## mouse_JCI
infoTable_kidney_mouse_JCI <- read.csv("Kidney/mouse_JCI/spatial_data/infoTable_2.csv", sep = ";")

se_kidney_mouse_JCI <- InputFromTable(infotable = infoTable_kidney_mouse_JCI, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_kidney_mouse_JCI$dataset <- "kidney_mouse_JCI"
median(se_kidney_mouse_JCI$nFeature_RNA)
median(se_kidney_mouse_JCI$nCount_RNA)

```


## Liver
```{r}
## human_JBO0018
infoTable_liver_human_JBO0018 <- read.csv("Liver/human_JBO0018/spatial_data/infoTable_2.csv", sep = ";")

se_liver_human_JBO0018 <- InputFromTable(infotable = infoTable_liver_human_JBO0018, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_liver_human_JBO0018$dataset <- "liver_human_JBO0018"
median(se_liver_human_JBO0018$nFeature_RNA)
median(se_liver_human_JBO0018$nCount_RNA)

## human_JBO0022
infoTable_liver_human_JBO0022 <- read.csv("Liver/human_JBO0022/spatial_data/infoTable_2.csv", sep = ";")

se_liver_human_JBO0022 <- InputFromTable(infotable = infoTable_liver_human_JBO0022, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_liver_human_JBO0022$dataset <- "liver_human_JBO0022"
median(se_liver_human_JBO0022$nFeature_RNA)
median(se_liver_human_JBO0022$nCount_RNA)

## mouse_JBO002
infoTable_liver_mouse_JBO002 <- read.csv("Liver/mouse_JBO002/spatial_data/infoTable_2.csv", sep = ";")

se_liver_mouse_JBO002 <- InputFromTable(infotable = infoTable_liver_mouse_JBO002, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_liver_mouse_JBO002$dataset <- "liver_mouse_JBO002"
median(se_liver_mouse_JBO002$nFeature_RNA)
median(se_liver_mouse_JBO002$nCount_RNA)

## mouse_zonation_C1
ensids <- read.table(file = list.files(system.file("extdata", package = "STutility"), full.names = T, pattern = "mouse_genes"), header = T, sep = "\t", stringsAsFactors = F)

infoTable_liver_mouse_zonation_C1 <- read.csv("Liver/mouse_zonation_C1/spatial_data/infoTable_2.csv", sep = ";")

se_liver_mouse_zonation_C1 <- InputFromTable(infotable = infoTable_liver_mouse_zonation_C1, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "2k",
                      annotation = ensids,
                      transpose = TRUE)

se_liver_mouse_zonation_C1$dataset <- "liver_mouse_zonation_C1"
median(se_liver_mouse_zonation_C1$nFeature_RNA)
median(se_liver_mouse_zonation_C1$nCount_RNA)

```


## Lung
```{r}
## HLA_Bronchi_A42_311
infoTable_lung_bronchi_human_A42 <- read.csv("Lung/HLA_Bronchi_A42_311/spatial_data/infoTable_2.csv", sep = ";")

se_lung_bronchi_human_A42 <- InputFromTable(infotable = infoTable_lung_bronchi_human_A42, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_lung_bronchi_human_A42$dataset <- "lung_bronchi_human_A42"
median(se_lung_bronchi_human_A42$nFeature_RNA)
median(se_lung_bronchi_human_A42$nCount_RNA)

## HLA_Bronchi_A50_467
infoTable_lung_bronchi_human_A50 <- read.csv("Lung/HLA_Bronchi_A50_467/spatial_data/infoTable_2.csv", sep = ";")

se_lung_bronchi_human_A50 <- InputFromTable(infotable = infoTable_lung_bronchi_human_A50, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_lung_bronchi_human_A50$dataset <- "lung_bronchi_human_A50"
median(se_lung_bronchi_human_A50$nFeature_RNA)
median(se_lung_bronchi_human_A50$nCount_RNA)

## HLA_Parenchyma_A37_347
infoTable_lung_parenchyma_human_A37 <- read.csv("Lung/HLA_Parenchyma_A37_347/spatial_data/infoTable_2.csv", sep = ";")

se_lung_parenchyma_human_A37 <- InputFromTable(infotable = infoTable_lung_parenchyma_human_A37, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_lung_parenchyma_human_A37$dataset <- "lung_parenchyma_human_A37"
median(se_lung_parenchyma_human_A37$nFeature_RNA)
median(se_lung_parenchyma_human_A37$nCount_RNA)

## HLA_Parenchyma_A48_345
infoTable_lung_parenchyma_human_A48 <- read.csv("Lung/HLA_Parenchyma_A48_345/spatial_data/infoTable_2.csv", sep = ";")

se_lung_parenchyma_human_A48 <- InputFromTable(infotable = infoTable_lung_parenchyma_human_A48, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_lung_parenchyma_human_A48$dataset <- "lung_parenchyma_human_A48"
median(se_lung_parenchyma_human_A48$nFeature_RNA)
median(se_lung_parenchyma_human_A48$nCount_RNA)

```


## Pancreas
```{r}
## pancreas_human_15PCW_S1
infoTable_pancreas_human_pcw15_S1 <- read.csv("Pancreas/pancreas_human_15PCW_S1/spatial_data/infoTable_2.csv", sep = ";")

se_pancreas_human_pcw15_S1 <- InputFromTable(infotable = infoTable_pancreas_human_pcw15_S1, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_pancreas_human_pcw15_S1$dataset <- "pancreas_human_pcw15_S1"
median(se_pancreas_human_pcw15_S1$nFeature_RNA)
median(se_pancreas_human_pcw15_S1$nCount_RNA)


## pancreas_human_18PCW_S1
infoTable_pancreas_human_pcw18_S1 <- read.csv("Pancreas/pancreas_human_18PCW_S1/spatial_data/infoTable_2.csv", sep = ";")

se_pancreas_human_pcw18_S1 <- InputFromTable(infotable = infoTable_pancreas_human_pcw18_S1, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_pancreas_human_pcw18_S1$dataset <- "pancreas_human_pcw18_S1"
median(se_pancreas_human_pcw18_S1$nFeature_RNA)
median(se_pancreas_human_pcw18_S1$nCount_RNA)


## pancreas_human_20PCW_S1
infoTable_pancreas_human_pcw20_S1 <- read.csv("Pancreas/pancreas_human_20PCW_S1/spatial_data/infoTable_2.csv", sep = ";")

se_pancreas_human_pcw20_S1 <- InputFromTable(infotable = infoTable_pancreas_human_pcw20_S1, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_pancreas_human_pcw20_S1$dataset <- "pancreas_human_pcw20_S1"
median(se_pancreas_human_pcw20_S1$nFeature_RNA)
median(se_pancreas_human_pcw20_S1$nCount_RNA)

```




## Spinal_cord
```{r}
## w5_V10T03_302B1
infoTable_spinal_cord_human_pcw5_302B1 <- read.csv("Spinal_cord/w5_V10T03_302B1/spatial_data/infoTable_2.csv", sep = ";")

se_spinal_cord_human_pcw5_302B1 <- InputFromTable(infotable = infoTable_spinal_cord_human_pcw5_302B1, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_spinal_cord_human_pcw5_302B1$dataset <- "spinal_cord_human_pcw5_302B1"
median(se_spinal_cord_human_pcw5_302B1$nFeature_RNA)
median(se_spinal_cord_human_pcw5_302B1$nCount_RNA)


## w8_V10F24_107B1
infoTable_spinal_cord_human_pcw8_107B1 <- read.csv("Spinal_cord/w8_V10F24_107B1/spatial_data/infoTable_2.csv", sep = ";")

se_spinal_cord_human_pcw8_107B1 <- InputFromTable(infotable = infoTable_spinal_cord_human_pcw8_107B1, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_spinal_cord_human_pcw8_107B1$dataset <- "spinal_cord_human_pcw8_107B1"
median(se_spinal_cord_human_pcw8_107B1$nFeature_RNA)
median(se_spinal_cord_human_pcw8_107B1$nCount_RNA)


## w9_V10T03_288A1
infoTable_spinal_cord_human_pcw9_288A1 <- read.csv("Spinal_cord/w9_V10T03_288A1/spatial_data/infoTable_2.csv", sep = ";")

se_spinal_cord_human_pcw9_288A1 <- InputFromTable(infotable = infoTable_spinal_cord_human_pcw9_288A1, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_spinal_cord_human_pcw9_288A1$dataset <- "spinal_cord_human_pcw9_288A1"
median(se_spinal_cord_human_pcw9_288A1$nFeature_RNA)
median(se_spinal_cord_human_pcw9_288A1$nCount_RNA)


## w12_V10T03_290D1
infoTable_spinal_cord_human_pcw12_290D1 <- read.csv("Spinal_cord/w12_V10T03_290D1/spatial_data/infoTable_2.csv", sep = ";")

se_spinal_cord_human_pcw12_290D1 <- InputFromTable(infotable = infoTable_spinal_cord_human_pcw12_290D1, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

se_spinal_cord_human_pcw12_290D1$dataset <- "spinal_cord_human_pcw12_290D1"
median(se_spinal_cord_human_pcw12_290D1$nFeature_RNA)
median(se_spinal_cord_human_pcw12_290D1$nCount_RNA)

```


# Plot  {.tabset}

Merge datasets

```{r}
se.merged <- MergeSTData(se_brain_human_151509, y = list(se_brain_human_151673, se_brain_mouse_10X, se_brain_mouse_cell2location, se_heart_human_adult_ACH003, se_heart_human_adult_ACH004, se_heart_human_pcw6.5_nr8, se_heart_human_pcw9_nr16,se_intestine_human_adult_HFGA_A1, se_intestine_human_adult_RRST_349_B1, se_intestine_human_pcw12_HFGA_A8, se_intestine_human_pcw19_HFGA_A4, se_intestine_mouse_healing_ctrl, se_kidney_human_JCI, se_kidney_mouse_10X, se_kidney_mouse_JCI, se_liver_human_JBO0018, se_liver_human_JBO0022, se_liver_mouse_JBO002, se_liver_mouse_zonation_C1, se_lung_bronchi_human_A42, se_lung_bronchi_human_A50, se_lung_parenchyma_human_A37, se_lung_parenchyma_human_A48, se_pancreas_human_pcw15_S1, se_pancreas_human_pcw18_S1, se_pancreas_human_pcw20_S1, se_spinal_cord_human_pcw5_302B1, se_spinal_cord_human_pcw8_107B1, se_spinal_cord_human_pcw9_288A1, se_spinal_cord_human_pcw12_290D1))

se.merged <- SetIdent(se.merged, value = "dataset")
```

## Genes

Colors
```{r}
brewer.pal(n = 8, name = "Dark2")
c("#1B9E77", "#D95F02", "#7570B3", "#E7298A", "#66A61E", "#E6AB02", "#A6761D", "#666666")

brain_color <- rep("#1B9E77",4)
heart_color <- rep("#D95F02",4)
intestine_color <- rep("#7570B3",5)
kidney_color <- rep("#E7298A",3)
liver_color <- rep("#66A61E",4)
lung_color <- rep("#E6AB02",4)
pancreas_color <- rep("#A6761D",3)
spinal_cord_color <- rep("#666666",4)

color_legend <- c(brain_color,heart_color,intestine_color,kidney_color,liver_color,lung_color,pancreas_color,spinal_cord_color)
```


```{r, fig.width=20, fig.height=10}
VlnPlot(se.merged, features = "nFeature_RNA") + 
  geom_boxplot(width=0.1, fill="white")+
  scale_y_continuous(n.breaks = 10) +
  scale_fill_manual(values = color_legend)  +
  #scale_fill_viridis(discrete = TRUE, alpha=0.6, option = "viridis")+
  ggtitle("Number of Genes after filtering")+
  xlab("Datasets")+
  ylab("Genes")

```

PDF
```{r}
pdf(file = "QC_ST_data_overview_[Genes].pdf", height = 10, width = 20)

VlnPlot(se.merged, features = "nFeature_RNA") + 
  geom_boxplot(width=0.1, fill="white")+
  scale_y_continuous(n.breaks = 10) +
  scale_fill_manual(values = color_legend)  +
  #scale_fill_viridis(discrete = TRUE, alpha=0.6, option = "viridis")+
  ggtitle("Number of Genes after filtering")+
  xlab("Datasets")+
  ylab("Genes")


dev.off()
```


## UMI

```{r, fig.width=20, fig.height=15}
VlnPlot(se.merged, features = "nCount_RNA") + 
  geom_boxplot(width=0.1, fill="white") +
  scale_y_continuous(n.breaks = 20) +
  #scale_y_continuous(n.breaks = 10, limits = c(0,50000)) +
  scale_fill_manual(values = color_legend)  +
  #scale_fill_viridis(discrete = TRUE, alpha=0.6, option = "viridis")+
  ggtitle("Number of UMIs after filtering")+
  xlab("Datasets")+
  ylab("UMIs")

```


PDF
```{r}
pdf(file = "QC_ST_data_overview_[UMI].pdf", height = 15, width = 20)

VlnPlot(se.merged, features = "nCount_RNA") + 
  geom_boxplot(width=0.1, fill="white") +
  scale_y_continuous(n.breaks = 20) +
  #scale_y_continuous(n.breaks = 10, limits = c(0,50000)) +
  scale_fill_manual(values = color_legend)  +
  #scale_fill_viridis(discrete = TRUE, alpha=0.6, option = "viridis")+
  ggtitle("Number of UMIs after filtering")+
  xlab("Datasets")+
  ylab("UMIs")


dev.off()
```


SessionInfo
```{r}
sessionInfo()
```



