---
title: "Supplementary_table_dataset_overview"
output: html_document
date: "2025-05-05"
---

NOTE: Creates the plot for figure 2f, the proportion of significant substructures across tissues for i) all genetically associated genes, ii) top genes, and iii) drug target genes of selected tissue-trait pairs


Load libraries
```{r}
library(ggplot2)
library(forcats)
library(hrbrthemes)
library(dplyr)
library(tidyr)
library(viridis)

```


Load data
```{r}
mydata <- read.csv(file = "Supplementary_table_dataset_overview.csv",sep = ";")
```
df[df==""]<-NA

```{r}
mydata[mydata=="N/A"] <- NA

mydata$Significantly_enriched_structures_.Genetic_top_genes. <- as.numeric(mydata$Significantly_enriched_structures_.Genetic_top_genes.)

mydata$Significantly_enriched_structures_..Drugs. <- as.numeric(mydata$Significantly_enriched_structures_..Drugs.)
```

```{r}
sum(mydata$Spatial_structures_.number.)
sum(mydata$Significantly_enriched_structures_.Genetic.)
sum(mydata$Significantly_enriched_structures_.Genetic_top_genes.,na.rm = T)
sum(mydata$Significantly_enriched_structures_..Drugs.,na.rm = T)
```

```{r}
print("% genetic structures enriched")
(338/1353)*100

print("% genetic top structures enriched")
(297/1353)*100

print("% drug targets structures enriched")
(651/1353)*100

print("% N/A")
100 - sum((338/1353)*100 + (297/1353)*100 + (651/1353)*100)
```


```{r}
table(mydata$Spatial_structures_.number.) # traits per structure number in a dataset
table(mydata$Significantly_enriched_structures_.Genetic.) 
table(mydata$Significantly_enriched_structures_.Genetic_top_genes.)
table(mydata$Significantly_enriched_structures_..Drugs.)
```

```{r}
mydata$Genetic <- (mydata$Significantly_enriched_structures_.Genetic.)/(mydata$Spatial_structures_.number.)
mydata$Genetic_top <- (mydata$Significantly_enriched_structures_.Genetic_top_genes.)/(mydata$Spatial_structures_.number.)
mydata$Drugs <- (mydata$Significantly_enriched_structures_..Drugs.)/(mydata$Spatial_structures_.number.)
```


```{r}
mydata_genetic <- data.frame(mydata$Genetic,(mydata$Group <- "Genetic"))
colnames(mydata_genetic) <- c("proportion","Group")

mydata_genetic_top <- data.frame(mydata$Genetic_top,(mydata$Group <- "Genetic_top"))
colnames(mydata_genetic_top) <- c("proportion","Group")

mydata_drugs <- data.frame(mydata$Drugs,(mydata$Group <- "Drugs"))
colnames(mydata_drugs) <- c("proportion","Group")

mydata_plot <- rbind(mydata_genetic,mydata_genetic_top,mydata_drugs)
```


```{r}
table(mydata_genetic$Group)
table(mydata_genetic$proportion)
sum(is.na(mydata$Significantly_enriched_structures_.Genetic.))
152-97-31 # one or more (not all) substructures enriched
24/152 # trait-specific substructure enrichment
```

```{r}
table(mydata_genetic_top$Group)
table(mydata_genetic_top$proportion)
sum(is.na(mydata$Significantly_enriched_structures_.Genetic_top_genes.))
152-52-26-42 # one or more (not all) substructures enriched
32/152 # trait-specific substructure enrichment
42/152 # no top genes
26/152 # broad tissue wide enrichment
52/152 # no tissue enrichment
```

```{r}
table(mydata_drugs$Group)
table(mydata_drugs$proportion)
sum(is.na(mydata$Significantly_enriched_structures_..Drugs.))
152-55-58-12 # one or more (not all) substructures enriched
27/152 # trait-specific substructure enrichment
```


```{r}
theme_set(theme_classic())

# Color by groups
p1 <- ggplot(mydata_genetic, aes(x=proportion, color=Group, fill=Group)) + 
                geom_histogram(alpha=1, color="black",position="identity") +
                ylab("Genetic")+
                xlab("Proportion of significant structures") +
                scale_x_continuous(breaks = seq(0, 1, 0.2), lim = c(-0.1, 1.1))+
                ylim(0,100)+
                scale_fill_manual(values=c("#2171B5"))+ 
                coord_cartesian(ylim = c(10, 100))+
                theme_classic(base_size = 18)

# Use custom color palettes
p1
```

PDF
```{r, eval=FALSE}
pdf(file = "Supplementary_table_dataset_overview_proportion_significant_structures_Genetic_10_100.pdf", width=9,height=3)

p1

dev.off()
```


```{r}
theme_set(theme_classic())

# Color by groups
p2 <- ggplot(mydata_genetic, aes(x=proportion, color=Group, fill=Group)) + 
                geom_histogram(alpha=1, color="black",position="identity") +
                ylab("Genetic")+
                xlab("Proportion of significant structures") +
                scale_x_continuous(breaks = seq(0, 1, 0.2), lim = c(-0.1, 1.1))+
                ylim(0,100)+
                scale_fill_manual(values=c("#2171B5"))+ 
                coord_cartesian(ylim = c(0, 10))+
                theme_classic(base_size = 18)

# Use custom color palettes
p2
```


PDF
```{r, eval=FALSE}
pdf(file = "Supplementary_table_dataset_overview_proportion_significant_structures_Genetic_0_10.pdf", width=9,height=3)

p2

dev.off()
```


```{r}
theme_set(theme_classic())

# Color by groups
p3 <- ggplot(mydata_genetic_top, aes(x=proportion, color=Group, fill=Group)) + 
                geom_histogram(alpha=1, color="black",position="identity") +
                ylab("Genetic top")+
                xlab("Proportion of significant structures") +
                scale_x_continuous(breaks = seq(0, 1, 0.2), lim = c(-0.1, 1.1))+
                ylim(0,100)+
                scale_fill_manual(values=c("#88419D"))+ 
                coord_cartesian(ylim = c(10, 100))+
                theme_classic(base_size = 18)

# Use custom color palettes
p3
```

PDF
```{r, eval=FALSE}
pdf(file = "Supplementary_table_dataset_overview_proportion_significant_structures_Genetic_top_10_100.pdf", width=9,height=3)

p3

dev.off()
```


```{r}
theme_set(theme_classic())

# Color by groups
p4 <- ggplot(mydata_genetic_top, aes(x=proportion, color=Group, fill=Group)) + 
                geom_histogram(alpha=1, color="black",position="identity") +
                ylab("Genetic top")+
                xlab("Proportion of significant structures") +
                scale_x_continuous(breaks = seq(0, 1, 0.2), lim = c(-0.1, 1.1))+
                ylim(0,100)+
                scale_fill_manual(values=c("#88419D"))+ 
                coord_cartesian(ylim = c(0, 10))+
                theme_classic(base_size = 18)

# Use custom color palettes
p4
```


PDF
```{r, eval=FALSE}
pdf(file = "Supplementary_table_dataset_overview_proportion_significant_structures_Genetic_top_0_10.pdf", width=9,height=3)

p4

dev.off()
```


```{r}
theme_set(theme_classic())

# Color by groups
p5 <- ggplot(mydata_drugs, aes(x=proportion, color=Group, fill=Group)) + 
                geom_histogram(alpha=1, color="black",position="identity") +
                ylab("Drug targets")+
                xlab("Proportion of significant structures") +
                 scale_x_continuous(breaks = seq(0, 1, 0.2), lim = c(-0.1, 1.1))+
                ylim(0,100)+
                scale_fill_manual(values=c("#238B45"))+ 
                coord_cartesian(ylim = c(10, 100))+
                theme_classic(base_size = 18)


# Use custom color palettes
p5
```

PDF
```{r,eval=FALSE}
pdf(file = "Supplementary_table_dataset_overview_proportion_significant_structures_Drugs_10_100.pdf", width=9,height=3)

p5

dev.off()
```

```{r}
theme_set(theme_classic())

# Color by groups
p6 <- ggplot(mydata_drugs, aes(x=proportion, color=Group, fill=Group)) + 
                geom_histogram(alpha=1, color="black",position="identity") +
                ylab("Drug targets")+
                xlab("Proportion of significant structures") +
                 scale_x_continuous(breaks = seq(0, 1, 0.2), lim = c(-0.1, 1.1))+
                ylim(0,100)+
                scale_fill_manual(values=c("#238B45"))+ 
                coord_cartesian(ylim = c(0, 10))+
                theme_classic(base_size = 18)


# Use custom color palettes
p6
```


PDF
```{r, eval=FALSE}
pdf(file = "Supplementary_table_dataset_overview_proportion_significant_structures_Drugs_0_10.pdf", width=9,height=3)

p6

dev.off()
```


SessionInfo
```{r}
sessionInfo()
```

