---
title: "pval_distribution_[all_datasets]_summary_selected_tissue_trait_pairs"
author: "Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
 html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

NOTE: Creates a summary file for all calculated p-values of all selected tissue-trait pairs.

#Load libraries
```{r}
library(dplyr)
library(tidyr)
```


# Brain datasets
```{r}
##_Human_brain_DLPFC_151509
meta.data.ADHD_Human_brain_DLPFC_151509 <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_ADHD_all_genes.RDS")
meta.data.ADHD_Human_brain_DLPFC_151509$trait_gene_list <- "ADHD_all_genes"

meta.data.AHD_Human_brain_DLPFC_151509 <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_Human_brain_DLPFC_151509$trait_gene_list <- "AHD_all_genes"

meta.data.ALS_Human_brain_DLPFC_151509 <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_Human_brain_DLPFC_151509$trait_gene_list <- "ALS_all_genes"

meta.data.ALZ_Human_brain_DLPFC_151509 <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_ALZ_all_genes.RDS")
meta.data.ALZ_Human_brain_DLPFC_151509$trait_gene_list <- "ALZ_all_genes"

meta.data.ALZ_Human_brain_DLPFC_151509_top <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_ALZ_top60_genes.RDS")
meta.data.ALZ_Human_brain_DLPFC_151509_top$trait_gene_list <- "ALZ_top60_genes"

meta.data.ASD_Human_brain_DLPFC_151509 <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_ASD_all_genes.RDS")
meta.data.ASD_Human_brain_DLPFC_151509$trait_gene_list <- "ASD_all_genes"

meta.data.BIP_Human_brain_DLPFC_151509 <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_BIP_all_genes.RDS")
meta.data.BIP_Human_brain_DLPFC_151509$trait_gene_list <- "BIP_all_genes"

meta.data.EPI_Human_brain_DLPFC_151509 <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_EPI_all_genes.RDS")
meta.data.EPI_Human_brain_DLPFC_151509$trait_gene_list <- "EPI_all_genes"

meta.data.EPI_Human_brain_DLPFC_151509_top <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_EPI_top200_genes.RDS")
meta.data.EPI_Human_brain_DLPFC_151509_top$trait_gene_list <- "EPI_top200_genes"

meta.data.INS_Human_brain_DLPFC_151509 <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_INS_all_genes.RDS")
meta.data.INS_Human_brain_DLPFC_151509$trait_gene_list <- "INS_all_genes"

meta.data.INS_Human_brain_DLPFC_151509_top <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_INS_top50_genes.RDS")
meta.data.INS_Human_brain_DLPFC_151509_top$trait_gene_list <- "INS_top50_genes"

meta.data.MDD_Human_brain_DLPFC_151509 <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_MDD_all_genes.RDS")
meta.data.MDD_Human_brain_DLPFC_151509$trait_gene_list <- "MDD_all_genes"

meta.data.MS_Human_brain_DLPFC_151509 <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_Human_brain_DLPFC_151509$trait_gene_list <- "MS_all_genes"

meta.data.PAR_Human_brain_DLPFC_151509 <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_PAR_all_genes.RDS")
meta.data.PAR_Human_brain_DLPFC_151509$trait_gene_list <- "PAR_all_genes"

meta.data.PAR_Human_brain_DLPFC_151509_top <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_PAR_top100_genes.RDS")
meta.data.PAR_Human_brain_DLPFC_151509_top$trait_gene_list <- "PAR_top100_genes"

meta.data.SCZ_Human_brain_DLPFC_151509 <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_SCZ_all_genes.RDS")
meta.data.SCZ_Human_brain_DLPFC_151509$trait_gene_list <- "SCZ_all_genes"

meta.data.SCZ_Human_brain_DLPFC_151509_top <- readRDS(file = "Brain/Human_brain_DLPFC_151509/p_value_distribution/pval.distribution_SCZ_top210_genes.RDS")
meta.data.SCZ_Human_brain_DLPFC_151509_top$trait_gene_list <- "SCZ_top210_genes"

brain_human_151509 <- rbind(meta.data.ADHD_Human_brain_DLPFC_151509,meta.data.AHD_Human_brain_DLPFC_151509)
brain_human_151509 <- rbind(brain_human_151509,meta.data.ALS_Human_brain_DLPFC_151509)
brain_human_151509 <- rbind(brain_human_151509,meta.data.ALZ_Human_brain_DLPFC_151509)
brain_human_151509 <- rbind(brain_human_151509,meta.data.ALZ_Human_brain_DLPFC_151509_top)
brain_human_151509 <- rbind(brain_human_151509,meta.data.ASD_Human_brain_DLPFC_151509)
brain_human_151509 <- rbind(brain_human_151509,meta.data.BIP_Human_brain_DLPFC_151509)
brain_human_151509 <- rbind(brain_human_151509,meta.data.EPI_Human_brain_DLPFC_151509)
brain_human_151509 <- rbind(brain_human_151509,meta.data.EPI_Human_brain_DLPFC_151509_top)
brain_human_151509 <- rbind(brain_human_151509,meta.data.INS_Human_brain_DLPFC_151509)
brain_human_151509 <- rbind(brain_human_151509,meta.data.INS_Human_brain_DLPFC_151509_top)
brain_human_151509 <- rbind(brain_human_151509,meta.data.MDD_Human_brain_DLPFC_151509)
brain_human_151509 <- rbind(brain_human_151509,meta.data.MS_Human_brain_DLPFC_151509)
brain_human_151509 <- rbind(brain_human_151509,meta.data.PAR_Human_brain_DLPFC_151509)
brain_human_151509 <- rbind(brain_human_151509,meta.data.PAR_Human_brain_DLPFC_151509_top)
brain_human_151509 <- rbind(brain_human_151509,meta.data.SCZ_Human_brain_DLPFC_151509)
brain_human_151509 <- rbind(brain_human_151509,meta.data.SCZ_Human_brain_DLPFC_151509_top)

#Add dataset name
brain_human_151509$dataset <- "brain_human_151509"

#Reorder
brain_human_151509 <- brain_human_151509[,c(11:9,1:8)]

```


```{r}

##_Human_brain_DLPFC_151673
meta.data.ADHD_Human_brain_DLPFC_151673 <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_ADHD_all_genes.RDS")
meta.data.ADHD_Human_brain_DLPFC_151673$trait_gene_list <- "ADHD_all_genes"

meta.data.ADHD_Human_brain_DLPFC_151673_top <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_ADHD_top100_genes.RDS")
meta.data.ADHD_Human_brain_DLPFC_151673_top$trait_gene_list <- "ADHD_top100_genes"

meta.data.AHD_Human_brain_DLPFC_151673 <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_Human_brain_DLPFC_151673$trait_gene_list <- "AHD_all_genes"

meta.data.ALS_Human_brain_DLPFC_151673 <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_Human_brain_DLPFC_151673$trait_gene_list <- "ALS_all_genes"
  
meta.data.ALZ_Human_brain_DLPFC_151673 <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_ALZ_all_genes.RDS")
meta.data.ALZ_Human_brain_DLPFC_151673$trait_gene_list <- "ALZ_all_genes"

meta.data.ALZ_Human_brain_DLPFC_151673_top <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_ALZ_top60_genes.RDS")
meta.data.ALZ_Human_brain_DLPFC_151673_top$trait_gene_list <- "ALZ_top60_genes"

meta.data.ASD_Human_brain_DLPFC_151673 <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_ASD_all_genes.RDS")
meta.data.ASD_Human_brain_DLPFC_151673$trait_gene_list <- "ASD_all_genes"

meta.data.ASD_Human_brain_DLPFC_151673_top <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_ASD_top60_genes.RDS")
meta.data.ASD_Human_brain_DLPFC_151673_top$trait_gene_list <- "ASD_top60_genes"

meta.data.BIP_Human_brain_DLPFC_151673 <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_BIP_all_genes.RDS")
meta.data.BIP_Human_brain_DLPFC_151673$trait_gene_list <- "BIP_all_genes"

meta.data.EPI_Human_brain_DLPFC_151673 <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_EPI_all_genes.RDS")
meta.data.EPI_Human_brain_DLPFC_151673$trait_gene_list <- "EPI_all_genes"

meta.data.EPI_Human_brain_DLPFC_151673_top <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_EPI_top210_genes.RDS")
meta.data.EPI_Human_brain_DLPFC_151673_top$trait_gene_list <- "EPI_top210_genes"

meta.data.INS_Human_brain_DLPFC_151673 <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_INS_all_genes.RDS")
meta.data.INS_Human_brain_DLPFC_151673$trait_gene_list <- "INS_all_genes"

meta.data.INS_Human_brain_DLPFC_151673_top <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_INS_top50_genes.RDS")
meta.data.INS_Human_brain_DLPFC_151673_top$trait_gene_list <- "INS_top50_genes"

meta.data.MDD_Human_brain_DLPFC_151673 <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_MDD_all_genes.RDS")
meta.data.MDD_Human_brain_DLPFC_151673$trait_gene_list <- "MDD_all_genes"

meta.data.MS_Human_brain_DLPFC_151673 <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_Human_brain_DLPFC_151673$trait_gene_list <- "MS_all_genes"

meta.data.PAR_Human_brain_DLPFC_151673 <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_PAR_all_genes.RDS")
meta.data.PAR_Human_brain_DLPFC_151673$trait_gene_list <- "PAR_all_genes"

meta.data.PAR_Human_brain_DLPFC_151673_top <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_PAR_top100_genes.RDS")
meta.data.PAR_Human_brain_DLPFC_151673_top$trait_gene_list <- "PAR_top100_genes"

meta.data.SCZ_Human_brain_DLPFC_151673 <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_SCZ_all_genes.RDS")
meta.data.SCZ_Human_brain_DLPFC_151673$trait_gene_list <- "SCZ_all_genes"

meta.data.SCZ_Human_brain_DLPFC_151673_top <- readRDS(file = "Brain/Human_brain_DLPFC_151673/p_value_distribution/pval.distribution_SCZ_top230_genes.RDS")
meta.data.SCZ_Human_brain_DLPFC_151673_top$trait_gene_list <- "SCZ_top230_genes"

#Merge
brain_human_151673 <- rbind(meta.data.ADHD_Human_brain_DLPFC_151673,meta.data.ADHD_Human_brain_DLPFC_151673_top)
brain_human_151673 <- rbind(brain_human_151673,meta.data.AHD_Human_brain_DLPFC_151673)
brain_human_151673 <- rbind(brain_human_151673,meta.data.ALS_Human_brain_DLPFC_151673)
brain_human_151673 <- rbind(brain_human_151673,meta.data.ALZ_Human_brain_DLPFC_151673)
brain_human_151673 <- rbind(brain_human_151673,meta.data.ALZ_Human_brain_DLPFC_151673_top)
brain_human_151673 <- rbind(brain_human_151673,meta.data.ASD_Human_brain_DLPFC_151673)
brain_human_151673 <- rbind(brain_human_151673,meta.data.ASD_Human_brain_DLPFC_151673_top)
brain_human_151673 <- rbind(brain_human_151673,meta.data.BIP_Human_brain_DLPFC_151673)
brain_human_151673 <- rbind(brain_human_151673,meta.data.EPI_Human_brain_DLPFC_151673)
brain_human_151673 <- rbind(brain_human_151673,meta.data.EPI_Human_brain_DLPFC_151673_top)
brain_human_151673 <- rbind(brain_human_151673,meta.data.INS_Human_brain_DLPFC_151673)
brain_human_151673 <- rbind(brain_human_151673,meta.data.INS_Human_brain_DLPFC_151673_top)
brain_human_151673 <- rbind(brain_human_151673,meta.data.MDD_Human_brain_DLPFC_151673)
brain_human_151673 <- rbind(brain_human_151673,meta.data.MS_Human_brain_DLPFC_151673)
brain_human_151673 <- rbind(brain_human_151673,meta.data.PAR_Human_brain_DLPFC_151673)
brain_human_151673 <- rbind(brain_human_151673,meta.data.PAR_Human_brain_DLPFC_151673_top)
brain_human_151673 <- rbind(brain_human_151673,meta.data.SCZ_Human_brain_DLPFC_151673)
brain_human_151673 <- rbind(brain_human_151673,meta.data.SCZ_Human_brain_DLPFC_151673_top)

#Add dataset name
brain_human_151673$dataset <- "brain_human_151673"

#Reorder
brain_human_151673 <- brain_human_151673[,c(11:9,1:8)]

```


```{r}
##_10X_Visium_mouse_brain_coronal
meta.data.ADHD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_ADHD_all_genes.RDS")
meta.data.ADHD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "ADHD_all_genes"

meta.data.ADHD_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_ADHD_top200_genes.RDS")
meta.data.ADHD_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "ADHD_top200_genes"

meta.data.AHD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "AHD_all_genes"

meta.data.AHD_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_AHD_top50_genes.RDS")
meta.data.AHD_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "AHD_top50_genes"

meta.data.ALS_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_10X_Visium_mouse_brain_coronal$trait_gene_list <- "ALS_all_genes"

meta.data.ALS_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_ALS_top50_genes.RDS")
meta.data.ALS_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "ALS_top50_genes"

meta.data.ALZ_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_ALZ_all_genes.RDS")
meta.data.ALZ_10X_Visium_mouse_brain_coronal$trait_gene_list <- "ALZ_all_genes"

meta.data.ALZ_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_ALZ_top70_genes.RDS")
meta.data.ALZ_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "ALZ_top70_genes"

meta.data.ASD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_ASD_all_genes.RDS")
meta.data.ASD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "ASD_all_genes"

meta.data.ASD_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_ASD_top130_genes.RDS")
meta.data.ASD_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "ASD_top130_genes"

meta.data.BIP_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_BIP_all_genes.RDS")
meta.data.BIP_10X_Visium_mouse_brain_coronal$trait_gene_list <- "BIP_all_genes"

meta.data.BIP_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_BIP_top80_genes.RDS")
meta.data.BIP_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "BIP_top80_genes"

meta.data.EPI_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_EPI_all_genes.RDS")
meta.data.EPI_10X_Visium_mouse_brain_coronal$trait_gene_list <- "EPI_all_genes"

meta.data.EPI_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_EPI_top220_genes.RDS")
meta.data.EPI_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "EPI_top220_genes"

meta.data.INS_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_INS_all_genes.RDS")
meta.data.INS_10X_Visium_mouse_brain_coronal$trait_gene_list <- "INS_all_genes"

meta.data.INS_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_INS_top50_genes.RDS")
meta.data.INS_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "INS_top50_genes"

meta.data.MDD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_MDD_all_genes.RDS")
meta.data.MDD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "MDD_all_genes"

meta.data.MDD_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_MDD_top70_genes.RDS")
meta.data.MDD_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "MDD_top70_genes"

meta.data.MS_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_10X_Visium_mouse_brain_coronal$trait_gene_list <- "MS_all_genes"

meta.data.PAR_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_PAR_all_genes.RDS")
meta.data.PAR_10X_Visium_mouse_brain_coronal$trait_gene_list <- "PAR_all_genes"

meta.data.PAR_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_PAR_top110_genes.RDS")
meta.data.PAR_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "PAR_top110_genes"

meta.data.SCZ_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_SCZ_all_genes.RDS")
meta.data.SCZ_10X_Visium_mouse_brain_coronal$trait_gene_list <- "SCZ_all_genes"

meta.data.SCZ_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_SCZ_top140_genes.RDS")
meta.data.SCZ_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "SCZ_top140_genes"

#Merge
brain_mouse_10X <- rbind(meta.data.ADHD_10X_Visium_mouse_brain_coronal,meta.data.ADHD_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.AHD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.AHD_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.ALS_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.ALS_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.ALZ_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.ALZ_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.ASD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.ASD_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.BIP_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.BIP_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.EPI_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.EPI_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.INS_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.INS_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.MDD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.MDD_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.MS_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.PAR_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.PAR_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.SCZ_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.SCZ_10X_Visium_mouse_brain_coronal_top)

#Add dataset name
brain_mouse_10X$dataset <- "brain_mouse_10X"

#Reorder
brain_mouse_10X <- brain_mouse_10X[,c(11:9,1:8)]

```


```{r}
##_Cell2location_Visium_mouse_brain_coronal_1
meta.data.ADHD_Cell2location_Visium_mouse_brain_coronal_1 <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_ADHD_all_genes.RDS")
meta.data.ADHD_Cell2location_Visium_mouse_brain_coronal_1$trait_gene_list <- "ADHD_all_genes"

meta.data.ADHD_Cell2location_Visium_mouse_brain_coronal_1_top <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_ADHD_top200_genes.RDS")
meta.data.ADHD_Cell2location_Visium_mouse_brain_coronal_1_top$trait_gene_list <- "ADHD_top200_genes"

meta.data.AHD_Cell2location_Visium_mouse_brain_coronal_1 <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_Cell2location_Visium_mouse_brain_coronal_1$trait_gene_list <- "AHD_all_genes"

meta.data.AHD_Cell2location_Visium_mouse_brain_coronal_1_top <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_AHD_top50_genes.RDS")
meta.data.AHD_Cell2location_Visium_mouse_brain_coronal_1_top$trait_gene_list <- "AHD_top50_genes"

meta.data.ALS_Cell2location_Visium_mouse_brain_coronal_1 <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_Cell2location_Visium_mouse_brain_coronal_1$trait_gene_list <- "ALS_all_genes"

meta.data.ALS_Cell2location_Visium_mouse_brain_coronal_1_top <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_ALS_top90_genes.RDS")
meta.data.ALS_Cell2location_Visium_mouse_brain_coronal_1_top$trait_gene_list <- "ALS_top90_genes"

meta.data.ALZ_Cell2location_Visium_mouse_brain_coronal_1 <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_ALZ_all_genes.RDS")
meta.data.ALZ_Cell2location_Visium_mouse_brain_coronal_1$trait_gene_list <- "ALZ_all_genes"

meta.data.ALZ_Cell2location_Visium_mouse_brain_coronal_1_top <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_ALZ_top70_genes.RDS")
meta.data.ALZ_Cell2location_Visium_mouse_brain_coronal_1_top$trait_gene_list <- "ALZ_top70_genes"

meta.data.ASD_Cell2location_Visium_mouse_brain_coronal_1 <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_ASD_all_genes.RDS")
meta.data.ASD_Cell2location_Visium_mouse_brain_coronal_1$trait_gene_list <- "ASD_all_genes"

meta.data.ASD_Cell2location_Visium_mouse_brain_coronal_1_top <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_ASD_top70_genes.RDS")
meta.data.ASD_Cell2location_Visium_mouse_brain_coronal_1_top$trait_gene_list <- "ASD_top70_genes"

meta.data.BIP_Cell2location_Visium_mouse_brain_coronal_1 <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_BIP_all_genes.RDS")
meta.data.BIP_Cell2location_Visium_mouse_brain_coronal_1$trait_gene_list <- "BIP_all_genes"

meta.data.BIP_Cell2location_Visium_mouse_brain_coronal_1_top <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_BIP_top120_genes.RDS")
meta.data.BIP_Cell2location_Visium_mouse_brain_coronal_1_top$trait_gene_list <- "BIP_top120_genes"

meta.data.EPI_Cell2location_Visium_mouse_brain_coronal_1 <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_EPI_all_genes.RDS")
meta.data.EPI_Cell2location_Visium_mouse_brain_coronal_1$trait_gene_list <- "EPI_all_genes"

meta.data.EPI_Cell2location_Visium_mouse_brain_coronal_1_top <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_EPI_top210_genes.RDS")
meta.data.EPI_Cell2location_Visium_mouse_brain_coronal_1_top$trait_gene_list <- "EPI_top210_genes"

meta.data.INS_Cell2location_Visium_mouse_brain_coronal_1 <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_INS_all_genes.RDS")
meta.data.INS_Cell2location_Visium_mouse_brain_coronal_1$trait_gene_list <- "INS_all_genes"

meta.data.INS_Cell2location_Visium_mouse_brain_coronal_1_top <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_INS_top50_genes.RDS")
meta.data.INS_Cell2location_Visium_mouse_brain_coronal_1_top$trait_gene_list <- "INS_top50_genes"

meta.data.MDD_Cell2location_Visium_mouse_brain_coronal_1 <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_MDD_all_genes.RDS")
meta.data.MDD_Cell2location_Visium_mouse_brain_coronal_1$trait_gene_list <- "MDD_all_genes"

meta.data.MDD_Cell2location_Visium_mouse_brain_coronal_1_top <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_MDD_top70_genes.RDS")
meta.data.MDD_Cell2location_Visium_mouse_brain_coronal_1_top$trait_gene_list <- "MDD_top70_genes"

meta.data.MS_Cell2location_Visium_mouse_brain_coronal_1 <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_Cell2location_Visium_mouse_brain_coronal_1$trait_gene_list <- "MS_all_genes"

meta.data.PAR_Cell2location_Visium_mouse_brain_coronal_1 <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_PAR_all_genes.RDS")
meta.data.PAR_Cell2location_Visium_mouse_brain_coronal_1$trait_gene_list <- "PAR_all_genes"

meta.data.PAR_Cell2location_Visium_mouse_brain_coronal_1_top <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_PAR_top100_genes.RDS")
meta.data.PAR_Cell2location_Visium_mouse_brain_coronal_1_top$trait_gene_list <- "PAR_top100_genes"

meta.data.SCZ_Cell2location_Visium_mouse_brain_coronal_1 <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_SCZ_all_genes.RDS")
meta.data.SCZ_Cell2location_Visium_mouse_brain_coronal_1$trait_gene_list <- "SCZ_all_genes"

meta.data.SCZ_Cell2location_Visium_mouse_brain_coronal_1_top <- readRDS(file = "Brain/Cell2location_Visium_mouse_brain_coronal_1/p_value_distribution/pval.distribution_SCZ_top130_genes.RDS")
meta.data.SCZ_Cell2location_Visium_mouse_brain_coronal_1_top$trait_gene_list <- "SCZ_top130_genes"

#Merge
brain_mouse_cell2location <- rbind(meta.data.ADHD_Cell2location_Visium_mouse_brain_coronal_1,meta.data.ADHD_Cell2location_Visium_mouse_brain_coronal_1_top)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.AHD_Cell2location_Visium_mouse_brain_coronal_1)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.AHD_Cell2location_Visium_mouse_brain_coronal_1_top)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.ALS_Cell2location_Visium_mouse_brain_coronal_1)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.ALS_Cell2location_Visium_mouse_brain_coronal_1_top)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.ALZ_Cell2location_Visium_mouse_brain_coronal_1)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.ALZ_Cell2location_Visium_mouse_brain_coronal_1_top)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.ASD_Cell2location_Visium_mouse_brain_coronal_1)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.ASD_Cell2location_Visium_mouse_brain_coronal_1_top)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.BIP_Cell2location_Visium_mouse_brain_coronal_1)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.BIP_Cell2location_Visium_mouse_brain_coronal_1_top)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.EPI_Cell2location_Visium_mouse_brain_coronal_1)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.EPI_Cell2location_Visium_mouse_brain_coronal_1_top)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.INS_Cell2location_Visium_mouse_brain_coronal_1)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.INS_Cell2location_Visium_mouse_brain_coronal_1_top)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.MDD_Cell2location_Visium_mouse_brain_coronal_1)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.MDD_Cell2location_Visium_mouse_brain_coronal_1_top)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.MS_Cell2location_Visium_mouse_brain_coronal_1)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.PAR_Cell2location_Visium_mouse_brain_coronal_1)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.PAR_Cell2location_Visium_mouse_brain_coronal_1_top)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.SCZ_Cell2location_Visium_mouse_brain_coronal_1)
brain_mouse_cell2location <- rbind(brain_mouse_cell2location,meta.data.SCZ_Cell2location_Visium_mouse_brain_coronal_1_top)

#Add dataset name
brain_mouse_cell2location$dataset <- "brain_mouse_cell2location"

#Reorder
brain_mouse_cell2location <- brain_mouse_cell2location[,c(11:9,1:8)]

```


# Heart datasets
```{r}
##adult_ACH003
meta.data.CAD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_adult_ACH003$trait_gene_list <- "CAD_all_genes"

meta.data.CAD_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_CAD_top180_genes.RDS")
meta.data.CAD_adult_ACH003_top$trait_gene_list <- "CAD_top180_genes"

meta.data.CHD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_CHD_all_genes.RDS")
meta.data.CHD_adult_ACH003$trait_gene_list <- "CHD_all_genes"

meta.data.CHD_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_CHD_top70_genes.RDS")
meta.data.CHD_adult_ACH003_top$trait_gene_list <- "CHD_top70_genes"

meta.data.LDL_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_adult_ACH003$`median(score_drugs)` <- "N/A"
meta.data.LDL_adult_ACH003$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_adult_ACH003$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_adult_ACH003 <- meta.data.LDL_adult_ACH003[,c(1:5,7:9,6)]
meta.data.LDL_adult_ACH003$trait_gene_list <- "LDL_all_genes"

meta.data.LDL_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_LDL_top90_genes.RDS")
meta.data.LDL_adult_ACH003_top$`median(score_drugs)` <- "N/A"
meta.data.LDL_adult_ACH003_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_adult_ACH003_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_adult_ACH003_top <- meta.data.LDL_adult_ACH003_top[,c(1:5,7:9,6)]
meta.data.LDL_adult_ACH003_top$trait_gene_list <- "LDL_top90_genes"

meta.data.MI_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_adult_ACH003$trait_gene_list <- "MI_all_genes"

meta.data.MI_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_MI_top70_genes.RDS")
meta.data.MI_adult_ACH003_top$trait_gene_list <- "MI_top70_genes"

#Merge
heart_human_adult_ACH003 <- rbind(meta.data.CAD_adult_ACH003,meta.data.CAD_adult_ACH003_top)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.CHD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.CHD_adult_ACH003_top)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.LDL_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.LDL_adult_ACH003_top)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.MI_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.MI_adult_ACH003_top)

#Add dataset name
heart_human_adult_ACH003$dataset <- "heart_human_adult_ACH003"

#Reorder
heart_human_adult_ACH003 <- heart_human_adult_ACH003[,c(11:9,1:8)]

```


```{r}
##adult_ACH004
meta.data.CAD_adult_ACH004 <- readRDS(file = "Heart/adult_ACH004/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_adult_ACH004$trait_gene_list <- "CAD_all_genes"

meta.data.CHD_adult_ACH004 <- readRDS(file = "Heart/adult_ACH004/p_value_distribution/pval.distribution_CHD_all_genes.RDS")
meta.data.CHD_adult_ACH004$trait_gene_list <- "CHD_all_genes"

meta.data.CHD_adult_ACH004_top <- readRDS(file = "Heart/adult_ACH004/p_value_distribution/pval.distribution_CHD_top70_genes.RDS")
meta.data.CHD_adult_ACH004_top$trait_gene_list <- "CHD_top70_genes"

meta.data.LDL_adult_ACH004 <- readRDS(file = "Heart/adult_ACH004/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_adult_ACH004$`median(score_drugs)` <- "N/A"
meta.data.LDL_adult_ACH004$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_adult_ACH004$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_adult_ACH004 <- meta.data.LDL_adult_ACH004[,c(1:5,7:9,6)]
meta.data.LDL_adult_ACH004$trait_gene_list <- "LDL_all_genes"

meta.data.MI_adult_ACH004 <- readRDS(file = "Heart/adult_ACH004/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_adult_ACH004$trait_gene_list <- "MI_all_genes"

#Merge
heart_human_adult_ACH004 <- rbind(meta.data.CAD_adult_ACH004,meta.data.CHD_adult_ACH004)
heart_human_adult_ACH004 <- rbind(heart_human_adult_ACH004,meta.data.CHD_adult_ACH004_top)
heart_human_adult_ACH004 <- rbind(heart_human_adult_ACH004,meta.data.LDL_adult_ACH004)
heart_human_adult_ACH004 <- rbind(heart_human_adult_ACH004,meta.data.MI_adult_ACH004)

#Add dataset name
heart_human_adult_ACH004$dataset <- "heart_human_adult_ACH004"

#Reorder
heart_human_adult_ACH004 <- heart_human_adult_ACH004[,c(11:9,1:8)]


```


```{r}
#_pcw6.5_nr8
meta.data.CAD_pcw6.5_nr8 <- readRDS(file = "Heart/pcw6.5_nr8/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_pcw6.5_nr8$trait_gene_list <- "CAD_all_genes"

meta.data.CAD_pcw6.5_nr8_top <- readRDS(file = "Heart/pcw6.5_nr8/p_value_distribution/pval.distribution_CAD_top70_genes.RDS")
meta.data.CAD_pcw6.5_nr8_top$trait_gene_list <- "CAD_top70_genes"

meta.data.CHD_pcw6.5_nr8 <- readRDS(file = "Heart/pcw6.5_nr8/p_value_distribution/pval.distribution_CHD_all_genes.RDS")
meta.data.CHD_pcw6.5_nr8$trait_gene_list <- "CHD_all_genes"

meta.data.CHD_pcw6.5_nr8_top <- readRDS(file = "Heart/pcw6.5_nr8/p_value_distribution/pval.distribution_CHD_top60_genes.RDS")
meta.data.CHD_pcw6.5_nr8_top$trait_gene_list <- "CHD_top60_genes"

meta.data.LDL_pcw6.5_nr8 <- readRDS(file = "Heart/pcw6.5_nr8/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_pcw6.5_nr8$`median(score_drugs)` <- "N/A"
meta.data.LDL_pcw6.5_nr8$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_pcw6.5_nr8$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_pcw6.5_nr8 <- meta.data.LDL_pcw6.5_nr8[,c(1:5,7:9,6)]
meta.data.LDL_pcw6.5_nr8$trait_gene_list <- "LDL_all_genes"

meta.data.MI_pcw6.5_nr8 <- readRDS(file = "Heart/pcw6.5_nr8/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_pcw6.5_nr8$trait_gene_list <- "MI_all_genes"

meta.data.MI_pcw6.5_nr8_top <- readRDS(file = "Heart/pcw6.5_nr8/p_value_distribution/pval.distribution_MI_top60_genes.RDS")
meta.data.MI_pcw6.5_nr8_top$trait_gene_list <- "MI_top60_genes"

#Merge
heart_human_pcw6.5_nr8 <- rbind(meta.data.CAD_pcw6.5_nr8,meta.data.CAD_pcw6.5_nr8_top)
heart_human_pcw6.5_nr8 <- rbind(heart_human_pcw6.5_nr8,meta.data.CHD_pcw6.5_nr8)
heart_human_pcw6.5_nr8 <- rbind(heart_human_pcw6.5_nr8,meta.data.CHD_pcw6.5_nr8_top)
heart_human_pcw6.5_nr8 <- rbind(heart_human_pcw6.5_nr8,meta.data.LDL_pcw6.5_nr8)
heart_human_pcw6.5_nr8 <- rbind(heart_human_pcw6.5_nr8,meta.data.MI_pcw6.5_nr8)
heart_human_pcw6.5_nr8 <- rbind(heart_human_pcw6.5_nr8,meta.data.MI_pcw6.5_nr8_top)

#Add dataset name
heart_human_pcw6.5_nr8$dataset <- "heart_human_pcw6.5_nr8"

#Reorder
heart_human_pcw6.5_nr8 <- heart_human_pcw6.5_nr8[,c(11:9,1:8)]

```


```{r}
#_pcw9_nr16
meta.data.CAD_pcw9_nr16 <- readRDS(file = "Heart/pcw9_nr16/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_pcw9_nr16$trait_gene_list <- "CAD_all_genes"

meta.data.CAD_pcw9_nr16_top <- readRDS(file = "Heart/pcw9_nr16/p_value_distribution/pval.distribution_CAD_top50_genes.RDS")
meta.data.CAD_pcw9_nr16_top$trait_gene_list <- "CAD_top50_genes"

meta.data.CHD_pcw9_nr16 <- readRDS(file = "Heart/pcw9_nr16/p_value_distribution/pval.distribution_CHD_all_genes.RDS")
meta.data.CHD_pcw9_nr16$trait_gene_list <- "CHD_all_genes"

meta.data.CHD_pcw9_nr16_top <- readRDS(file = "Heart/pcw9_nr16/p_value_distribution/pval.distribution_CHD_top50_genes.RDS")
meta.data.CHD_pcw9_nr16_top$trait_gene_list <- "CHD_top50_genes"

meta.data.LDL_pcw9_nr16 <- readRDS(file = "Heart/pcw9_nr16/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_pcw9_nr16$`median(score_drugs)` <- "N/A"
meta.data.LDL_pcw9_nr16$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_pcw9_nr16$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_pcw9_nr16 <- meta.data.LDL_pcw9_nr16[,c(1:5,7:9,6)]
meta.data.LDL_pcw9_nr16$trait_gene_list <- "LDL_all_genes"

meta.data.MI_pcw9_nr16 <- readRDS(file = "Heart/pcw9_nr16/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_pcw9_nr16$trait_gene_list <- "MI_all_genes"

#Merge
heart_human_pcw9_nr16 <- rbind(meta.data.CAD_pcw9_nr16,meta.data.CAD_pcw9_nr16_top)
heart_human_pcw9_nr16 <- rbind(heart_human_pcw9_nr16,meta.data.CHD_pcw9_nr16)
heart_human_pcw9_nr16 <- rbind(heart_human_pcw9_nr16,meta.data.CHD_pcw9_nr16_top)
heart_human_pcw9_nr16 <- rbind(heart_human_pcw9_nr16,meta.data.LDL_pcw9_nr16)
heart_human_pcw9_nr16 <- rbind(heart_human_pcw9_nr16,meta.data.MI_pcw9_nr16)

#Add dataset name
heart_human_pcw9_nr16$dataset <- "heart_human_pcw9_nr16"

#Reorder
heart_human_pcw9_nr16 <- heart_human_pcw9_nr16[,c(11:9,1:8)]

```


# Intestine datasets
```{r}
##adult_HFGA_A1
meta.data.CD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_CD_all_genes.RDS")
meta.data.CD_adult_HFGA_A1$trait_gene_list <- "CD_all_genes"

meta.data.CD_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_CD_top130_genes.RDS")
meta.data.CD_adult_HFGA_A1_top$trait_gene_list <- "CD_top130_genes"

meta.data.IBD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_IBD_all_genes.RDS")
meta.data.IBD_adult_HFGA_A1$trait_gene_list <- "IBD_all_genes"

meta.data.IBD_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_IBD_top80_genes.RDS")
meta.data.IBD_adult_HFGA_A1_top$trait_gene_list <- "IBD_top80_genes"

meta.data.LID_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_LID_all_genes.RDS")
meta.data.LID_adult_HFGA_A1$trait_gene_list <- "LID_all_genes"

meta.data.LID_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_LID_top140_genes.RDS")
meta.data.LID_adult_HFGA_A1_top$trait_gene_list <- "LID_top140_genes"

meta.data.UC_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_UC_all_genes.RDS")
meta.data.UC_adult_HFGA_A1$trait_gene_list <- "UC_all_genes"

meta.data.UC_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_UC_top60_genes.RDS")
meta.data.UC_adult_HFGA_A1_top$trait_gene_list <- "UC_top60_genes"

#Merge
intestine_human_adult_HFGA_A1 <- rbind(meta.data.CD_adult_HFGA_A1,meta.data.CD_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.IBD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.IBD_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.LID_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.LID_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.UC_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.UC_adult_HFGA_A1_top)

#Add dataset name
intestine_human_adult_HFGA_A1$dataset <- "intestine_human_adult_HFGA_A1"

#Reorder
intestine_human_adult_HFGA_A1 <- intestine_human_adult_HFGA_A1[,c(11:9,1:8)]

```



```{r}
##adult_RRST_349_B1
meta.data.CD_adult_RRST_349_B1 <- readRDS(file = "Intestine/adult_RRST_349_B1/p_value_distribution/pval.distribution_CD_all_genes.RDS")
meta.data.CD_adult_RRST_349_B1$trait_gene_list <- "CD_all_genes"

meta.data.CD_adult_RRST_349_B1_top <- readRDS(file = "Intestine/adult_RRST_349_B1/p_value_distribution/pval.distribution_CD_top160_genes.RDS")
meta.data.CD_adult_RRST_349_B1_top$trait_gene_list <- "CD_top160_genes"

meta.data.IBD_adult_RRST_349_B1 <- readRDS(file = "Intestine/adult_RRST_349_B1/p_value_distribution/pval.distribution_IBD_all_genes.RDS")
meta.data.IBD_adult_RRST_349_B1$trait_gene_list <- "IBD_all_genes"

meta.data.IBD_adult_RRST_349_B1_top <- readRDS(file = "Intestine/adult_RRST_349_B1/p_value_distribution/pval.distribution_IBD_top110_genes.RDS")
meta.data.IBD_adult_RRST_349_B1_top$trait_gene_list <- "IBD_top110_genes"

meta.data.LID_adult_RRST_349_B1 <- readRDS(file = "Intestine/adult_RRST_349_B1/p_value_distribution/pval.distribution_LID_all_genes.RDS")
meta.data.LID_adult_RRST_349_B1$trait_gene_list <- "LID_all_genes"

meta.data.LID_adult_RRST_349_B1_top <- readRDS(file = "Intestine/adult_RRST_349_B1/p_value_distribution/pval.distribution_LID_top80_genes.RDS")
meta.data.LID_adult_RRST_349_B1_top$trait_gene_list <- "LID_top80_genes"

meta.data.UC_adult_RRST_349_B1 <- readRDS(file = "Intestine/adult_RRST_349_B1/p_value_distribution/pval.distribution_UC_all_genes.RDS")
meta.data.UC_adult_RRST_349_B1$trait_gene_list <- "UC_all_genes"

meta.data.UC_adult_RRST_349_B1_top <- readRDS(file = "Intestine/adult_RRST_349_B1/p_value_distribution/pval.distribution_UC_top170_genes.RDS")
meta.data.UC_adult_RRST_349_B1_top$trait_gene_list <- "UC_top170_genes"

#Merge
intestine_human_adult_RRST_349_B1 <- rbind(meta.data.CD_adult_RRST_349_B1,meta.data.CD_adult_RRST_349_B1_top)
intestine_human_adult_RRST_349_B1 <- rbind(intestine_human_adult_RRST_349_B1,meta.data.IBD_adult_RRST_349_B1)
intestine_human_adult_RRST_349_B1 <- rbind(intestine_human_adult_RRST_349_B1,meta.data.IBD_adult_RRST_349_B1_top)
intestine_human_adult_RRST_349_B1 <- rbind(intestine_human_adult_RRST_349_B1,meta.data.LID_adult_RRST_349_B1)
intestine_human_adult_RRST_349_B1 <- rbind(intestine_human_adult_RRST_349_B1,meta.data.LID_adult_RRST_349_B1_top)
intestine_human_adult_RRST_349_B1 <- rbind(intestine_human_adult_RRST_349_B1,meta.data.UC_adult_RRST_349_B1)
intestine_human_adult_RRST_349_B1 <- rbind(intestine_human_adult_RRST_349_B1,meta.data.UC_adult_RRST_349_B1_top)

#Add dataset name
intestine_human_adult_RRST_349_B1$dataset <- "intestine_human_adult_RRST_349_B1"

#Reorder
intestine_human_adult_RRST_349_B1 <- intestine_human_adult_RRST_349_B1[,c(11:9,1:8)]

```


```{r}
##pcw12_HFGA_A8
meta.data.CD_pcw12_HFGA_A8 <- readRDS(file = "Intestine/pcw12_HFGA_A8/p_value_distribution/pval.distribution_CD_all_genes.RDS")
meta.data.CD_pcw12_HFGA_A8$trait_gene_list <- "CD_all_genes"

meta.data.IBD_pcw12_HFGA_A8 <- readRDS(file = "Intestine/pcw12_HFGA_A8/p_value_distribution/pval.distribution_IBD_all_genes.RDS")
meta.data.IBD_pcw12_HFGA_A8$trait_gene_list <- "IBD_all_genes"

meta.data.LID_pcw12_HFGA_A8 <- readRDS(file = "Intestine/pcw12_HFGA_A8/p_value_distribution/pval.distribution_LID_all_genes.RDS")
meta.data.LID_pcw12_HFGA_A8$trait_gene_list <- "LID_all_genes"

meta.data.LID_pcw12_HFGA_A8_top <- readRDS(file = "Intestine/pcw12_HFGA_A8/p_value_distribution/pval.distribution_LID_top330_genes.RDS")
meta.data.LID_pcw12_HFGA_A8_top$trait_gene_list <- "LID_top330_genes"

meta.data.UC_pcw12_HFGA_A8 <- readRDS(file = "Intestine/pcw12_HFGA_A8/p_value_distribution/pval.distribution_UC_all_genes.RDS")
meta.data.UC_pcw12_HFGA_A8$trait_gene_list <- "UC_all_genes"

meta.data.UC_pcw12_HFGA_A8_top <- readRDS(file = "Intestine/pcw12_HFGA_A8/p_value_distribution/pval.distribution_UC_top50_genes.RDS")
meta.data.UC_pcw12_HFGA_A8_top$trait_gene_list <- "UC_top50_genes"

#Merge
intestine_human_pcw12_HFGA_A8 <- rbind(meta.data.CD_pcw12_HFGA_A8,meta.data.IBD_pcw12_HFGA_A8)
intestine_human_pcw12_HFGA_A8 <- rbind(intestine_human_pcw12_HFGA_A8,meta.data.LID_pcw12_HFGA_A8)
intestine_human_pcw12_HFGA_A8 <- rbind(intestine_human_pcw12_HFGA_A8,meta.data.LID_pcw12_HFGA_A8_top)
intestine_human_pcw12_HFGA_A8 <- rbind(intestine_human_pcw12_HFGA_A8,meta.data.UC_pcw12_HFGA_A8)
intestine_human_pcw12_HFGA_A8 <- rbind(intestine_human_pcw12_HFGA_A8,meta.data.UC_pcw12_HFGA_A8_top)

#Add dataset name
intestine_human_pcw12_HFGA_A8$dataset <- "intestine_human_pcw12_HFGA_A8"

#Reorder
intestine_human_pcw12_HFGA_A8 <- intestine_human_pcw12_HFGA_A8[,c(11:9,1:8)]

```


```{r}
##pcw19_HFGA_A4
meta.data.CD_pcw19_HFGA_A4 <- readRDS(file = "Intestine/pcw19_HFGA_A4/p_value_distribution/pval.distribution_CD_all_genes.RDS")
meta.data.CD_pcw19_HFGA_A4$trait_gene_list <- "CD_all_genes"

meta.data.IBD_pcw19_HFGA_A4 <- readRDS(file = "Intestine/pcw19_HFGA_A4/p_value_distribution/pval.distribution_IBD_all_genes.RDS")
meta.data.IBD_pcw19_HFGA_A4$trait_gene_list <- "IBD_all_genes"

meta.data.LID_pcw19_HFGA_A4 <- readRDS(file = "Intestine/pcw19_HFGA_A4/p_value_distribution/pval.distribution_LID_all_genes.RDS")
meta.data.LID_pcw19_HFGA_A4$trait_gene_list <- "LID_all_genes"

meta.data.LID_pcw19_HFGA_A4_top <- readRDS(file = "Intestine/pcw19_HFGA_A4/p_value_distribution/pval.distribution_LID_top160_genes.RDS")
meta.data.LID_pcw19_HFGA_A4_top$trait_gene_list <- "LID_top160_genes"

meta.data.UC_pcw19_HFGA_A4 <- readRDS(file = "Intestine/pcw19_HFGA_A4/p_value_distribution/pval.distribution_UC_all_genes.RDS")
meta.data.UC_pcw19_HFGA_A4$trait_gene_list <- "UC_all_genes"

meta.data.UC_pcw19_HFGA_A4_top <- readRDS(file = "Intestine/pcw19_HFGA_A4/p_value_distribution/pval.distribution_UC_top190_genes.RDS")
meta.data.UC_pcw19_HFGA_A4_top$trait_gene_list <- "UC_top190_genes"

#Merge
intestine_human_pcw19_HFGA_A4 <- rbind(meta.data.CD_pcw19_HFGA_A4,meta.data.IBD_pcw19_HFGA_A4)
intestine_human_pcw19_HFGA_A4 <- rbind(intestine_human_pcw19_HFGA_A4,meta.data.LID_pcw19_HFGA_A4)
intestine_human_pcw19_HFGA_A4 <- rbind(intestine_human_pcw19_HFGA_A4,meta.data.LID_pcw19_HFGA_A4_top)
intestine_human_pcw19_HFGA_A4 <- rbind(intestine_human_pcw19_HFGA_A4,meta.data.UC_pcw19_HFGA_A4)
intestine_human_pcw19_HFGA_A4 <- rbind(intestine_human_pcw19_HFGA_A4,meta.data.UC_pcw19_HFGA_A4_top)

#Add dataset name
intestine_human_pcw19_HFGA_A4$dataset <- "intestine_human_pcw19_HFGA_A4"

#Reorder
intestine_human_pcw19_HFGA_A4 <- intestine_human_pcw19_HFGA_A4[,c(11:9,1:8)]

```


```{r}
##mouse_healing_ctrl
meta.data.CD_mouse_healing_ctrl <- readRDS(file = "Intestine/mouse_healing_ctrl/p_value_distribution/pval.distribution_CD_all_genes.RDS")
meta.data.CD_mouse_healing_ctrl$trait_gene_list <- "CD_all_genes"

meta.data.CD_mouse_healing_ctrl_top <- readRDS(file = "Intestine/mouse_healing_ctrl/p_value_distribution/pval.distribution_CD_top190_genes.RDS")
meta.data.CD_mouse_healing_ctrl_top$trait_gene_list <- "CD_top190_genes"

meta.data.IBD_mouse_healing_ctrl <- readRDS(file = "Intestine/mouse_healing_ctrl/p_value_distribution/pval.distribution_IBD_all_genes.RDS")
meta.data.IBD_mouse_healing_ctrl$trait_gene_list <- "IBD_all_genes"

meta.data.IBD_mouse_healing_ctrl_top <- readRDS(file = "Intestine/mouse_healing_ctrl/p_value_distribution/pval.distribution_IBD_top100_genes.RDS")
meta.data.IBD_mouse_healing_ctrl_top$trait_gene_list <- "IBD_top100_genes"

meta.data.LID_mouse_healing_ctrl <- readRDS(file = "Intestine/mouse_healing_ctrl/p_value_distribution/pval.distribution_LID_all_genes.RDS")
meta.data.LID_mouse_healing_ctrl$trait_gene_list <- "LID_all_genes"

meta.data.LID_mouse_healing_ctrl_top <- readRDS(file = "Intestine/mouse_healing_ctrl/p_value_distribution/pval.distribution_LID_top170_genes.RDS")
meta.data.LID_mouse_healing_ctrl_top$trait_gene_list <- "LID_top170_genes"

meta.data.UC_mouse_healing_ctrl <- readRDS(file = "Intestine/mouse_healing_ctrl/p_value_distribution/pval.distribution_UC_all_genes.RDS")
meta.data.UC_mouse_healing_ctrl$trait_gene_list <- "UC_all_genes"

meta.data.UC_mouse_healing_ctrl_top <- readRDS(file = "Intestine/mouse_healing_ctrl/p_value_distribution/pval.distribution_UC_top210_genes.RDS")
meta.data.UC_mouse_healing_ctrl_top$trait_gene_list <- "UC_top210_genes"

#Merge
intestine_mouse_healing_ctrl <- rbind(meta.data.CD_mouse_healing_ctrl,meta.data.CD_mouse_healing_ctrl_top)
intestine_mouse_healing_ctrl <- rbind(intestine_mouse_healing_ctrl,meta.data.IBD_mouse_healing_ctrl)
intestine_mouse_healing_ctrl <- rbind(intestine_mouse_healing_ctrl,meta.data.IBD_mouse_healing_ctrl_top)
intestine_mouse_healing_ctrl <- rbind(intestine_mouse_healing_ctrl,meta.data.LID_mouse_healing_ctrl)
intestine_mouse_healing_ctrl <- rbind(intestine_mouse_healing_ctrl,meta.data.LID_mouse_healing_ctrl_top)
intestine_mouse_healing_ctrl <- rbind(intestine_mouse_healing_ctrl,meta.data.UC_mouse_healing_ctrl)
intestine_mouse_healing_ctrl <- rbind(intestine_mouse_healing_ctrl,meta.data.UC_mouse_healing_ctrl_top)

#Add dataset name
intestine_mouse_healing_ctrl$dataset <- "intestine_mouse_healing_ctrl"

#Reorder
intestine_mouse_healing_ctrl <- intestine_mouse_healing_ctrl[,c(11:9,1:8)]


```


# Kidney datasets
```{r}
##human_JCI
meta.data.CKD_human_JCI <- readRDS(file = "Kidney/human_JCI/p_value_distribution/pval.distribution_CKD_all_genes.RDS")
meta.data.CKD_human_JCI$trait_gene_list <- "CKD_all_genes"

meta.data.CKD_human_JCI_top <- readRDS(file = "Kidney/human_JCI/p_value_distribution/pval.distribution_CKD_top70_genes.RDS")
meta.data.CKD_human_JCI_top$trait_gene_list <- "CKD_top70_genes"

meta.data.IKD_human_JCI <- readRDS(file = "Kidney/human_JCI/p_value_distribution/pval.distribution_IKD_all_genes.RDS")
meta.data.IKD_human_JCI$trait_gene_list <- "IKD_all_genes"

meta.data.IKD_human_JCI_top <- readRDS(file = "Kidney/human_JCI/p_value_distribution/pval.distribution_IKD_top80_genes.RDS")
meta.data.IKD_human_JCI_top$trait_gene_list <- "IKD_top80_genes"

#Merge
kidney_human_JCI <- rbind(meta.data.CKD_human_JCI,meta.data.CKD_human_JCI_top)
kidney_human_JCI <- rbind(kidney_human_JCI,meta.data.IKD_human_JCI)
kidney_human_JCI <- rbind(kidney_human_JCI,meta.data.IKD_human_JCI_top)

#Add dataset name
kidney_human_JCI$dataset <- "kidney_human_JCI"

#Reorder
kidney_human_JCI <- kidney_human_JCI[,c(11:9,1:8)]

```

```{r}
##mouse_10X_coronal
meta.data.CKD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_CKD_all_genes.RDS")
meta.data.CKD_mouse_10X_coronal$trait_gene_list <- "CKD_all_genes"

meta.data.CKD_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_CKD_top120_genes.RDS")
meta.data.CKD_mouse_10X_coronal_top$trait_gene_list <- "CKD_top120_genes"

meta.data.IKD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_IKD_all_genes.RDS")
meta.data.IKD_mouse_10X_coronal$trait_gene_list <- "IKD_all_genes"

meta.data.IKD_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_IKD_top230_genes.RDS")
meta.data.IKD_mouse_10X_coronal_top$trait_gene_list <- "IKD_top230_genes"

#Merge
kidney_mouse_10X <- rbind(meta.data.CKD_mouse_10X_coronal,meta.data.CKD_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.IKD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.IKD_mouse_10X_coronal_top)

#Add dataset name
kidney_mouse_10X$dataset <- "kidney_mouse_10X"

#Reorder
kidney_mouse_10X <- kidney_mouse_10X[,c(11:9,1:8)]

```

```{r}
##mouse_JCI
meta.data.CKD_mouse_JCI <- readRDS(file = "Kidney/mouse_JCI/p_value_distribution/pval.distribution_CKD_all_genes.RDS")
meta.data.CKD_mouse_JCI$trait_gene_list <- "CKD_all_genes"

meta.data.CKD_mouse_JCI_top <- readRDS(file = "Kidney/mouse_JCI/p_value_distribution/pval.distribution_CKD_top60_genes.RDS")
meta.data.CKD_mouse_JCI_top$trait_gene_list <- "CKD_top60_genes"

meta.data.IKD_mouse_JCI <- readRDS(file = "Kidney/mouse_JCI/p_value_distribution/pval.distribution_IKD_all_genes.RDS")
meta.data.IKD_mouse_JCI$trait_gene_list <- "IKD_all_genes"

meta.data.IKD_mouse_JCI_top <- readRDS(file = "Kidney/mouse_JCI/p_value_distribution/pval.distribution_IKD_top70_genes.RDS")
meta.data.IKD_mouse_JCI_top$trait_gene_list <- "IKD_top70_genes"

#Merge
kidney_mouse_JCI <- rbind(meta.data.CKD_mouse_JCI,meta.data.CKD_mouse_JCI_top)
kidney_mouse_JCI <- rbind(kidney_mouse_JCI,meta.data.IKD_mouse_JCI)
kidney_mouse_JCI <- rbind(kidney_mouse_JCI,meta.data.IKD_mouse_JCI_top)

#Add dataset name
kidney_mouse_JCI$dataset <- "kidney_mouse_JCI"

#Reorder
kidney_mouse_JCI <- kidney_mouse_JCI[,c(11:9,1:8)]

```


# Liver datasets
```{r}
##human_JBO0018
meta.data.CAD_human_JBO0018 <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_human_JBO0018$trait_gene_list <- "CAD_all_genes"

meta.data.CAD_human_JBO0018_top <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_CAD_top50_genes.RDS")
meta.data.CAD_human_JBO0018_top$trait_gene_list <- "CAD_top50_genes"

meta.data.CHOL_human_JBO0018 <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_CHOL_all_genes.RDS")
meta.data.CHOL_human_JBO0018$`median(score_drugs)` <- "N/A"
meta.data.CHOL_human_JBO0018$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_human_JBO0018$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_human_JBO0018 <- meta.data.CHOL_human_JBO0018[,c(1:5,7:9,6)]
meta.data.CHOL_human_JBO0018$trait_gene_list <- "CHOL_all_genes"

meta.data.CHOL_human_JBO0018_top <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_CHOL_top90_genes.RDS")
meta.data.CHOL_human_JBO0018_top$`median(score_drugs)` <- "N/A"
meta.data.CHOL_human_JBO0018_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_human_JBO0018_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_human_JBO0018_top <- meta.data.CHOL_human_JBO0018_top[,c(1:5,7:9,6)]
meta.data.CHOL_human_JBO0018_top$trait_gene_list <- "CHOL_top90_genes"

meta.data.CIRR_human_JBO0018 <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_CIRR_all_genes.RDS")
meta.data.CIRR_human_JBO0018$trait_gene_list <- "CIRR_all_genes"

meta.data.CIRR_human_JBO0018_top <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_CIRR_top60_genes.RDS")
meta.data.CIRR_human_JBO0018_top$trait_gene_list <- "CIRR_top60_genes"

meta.data.LD_human_JBO0018 <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_LD_all_genes.RDS")
meta.data.LD_human_JBO0018$trait_gene_list <- "LD_all_genes"

meta.data.LD_human_JBO0018_top <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_LD_top90_genes.RDS")
meta.data.LD_human_JBO0018_top$trait_gene_list <- "LD_top90_genes"

meta.data.LDL_human_JBO0018 <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_human_JBO0018$`median(score_drugs)` <- "N/A"
meta.data.LDL_human_JBO0018$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_human_JBO0018$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_human_JBO0018 <- meta.data.LDL_human_JBO0018[,c(1:5,7:9,6)]
meta.data.LDL_human_JBO0018$trait_gene_list <- "LDL_all_genes"

meta.data.LDL_human_JBO0018_top <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_LDL_top120_genes.RDS")
meta.data.LDL_human_JBO0018_top$`median(score_drugs)` <- "N/A"
meta.data.LDL_human_JBO0018_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_human_JBO0018_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_human_JBO0018_top <- meta.data.LDL_human_JBO0018_top[,c(1:5,7:9,6)]
meta.data.LDL_human_JBO0018_top$trait_gene_list <- "LDL_top120_genes"

meta.data.MI_human_JBO0018 <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_human_JBO0018$trait_gene_list <- "MI_all_genes"

meta.data.MI_human_JBO0018_top <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_MI_top80_genes.RDS")
meta.data.MI_human_JBO0018_top$trait_gene_list <- "MI_top80_genes"

meta.data.NAFLD_human_JBO0018 <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_NAFLD_all_genes.RDS")
meta.data.NAFLD_human_JBO0018$trait_gene_list <- "NAFLD_all_genes"

meta.data.NAFLD_human_JBO0018_top <- readRDS(file = "Liver/human_JBO0018/p_value_distribution/pval.distribution_NAFLD_top70_genes.RDS")
meta.data.NAFLD_human_JBO0018_top$trait_gene_list <- "NAFLD_top70_genes"

#Merge
liver_human_JBO0018 <- rbind(meta.data.CAD_human_JBO0018,meta.data.CAD_human_JBO0018_top)
liver_human_JBO0018 <- rbind(liver_human_JBO0018,meta.data.CHOL_human_JBO0018)
liver_human_JBO0018 <- rbind(liver_human_JBO0018,meta.data.CHOL_human_JBO0018_top)
liver_human_JBO0018 <- rbind(liver_human_JBO0018,meta.data.CIRR_human_JBO0018)
liver_human_JBO0018 <- rbind(liver_human_JBO0018,meta.data.CIRR_human_JBO0018_top)
liver_human_JBO0018 <- rbind(liver_human_JBO0018,meta.data.LD_human_JBO0018)
liver_human_JBO0018 <- rbind(liver_human_JBO0018,meta.data.LD_human_JBO0018_top)
liver_human_JBO0018 <- rbind(liver_human_JBO0018,meta.data.LDL_human_JBO0018)
liver_human_JBO0018 <- rbind(liver_human_JBO0018,meta.data.LDL_human_JBO0018_top)
liver_human_JBO0018 <- rbind(liver_human_JBO0018,meta.data.MI_human_JBO0018)
liver_human_JBO0018 <- rbind(liver_human_JBO0018,meta.data.MI_human_JBO0018_top)
liver_human_JBO0018 <- rbind(liver_human_JBO0018,meta.data.NAFLD_human_JBO0018)
liver_human_JBO0018 <- rbind(liver_human_JBO0018,meta.data.NAFLD_human_JBO0018_top)

#Add dataset name
liver_human_JBO0018$dataset <- "liver_human_JBO0018"

#Reorder
liver_human_JBO0018 <- liver_human_JBO0018[,c(11:9,1:8)]

```


```{r}
##human_JBO0022
meta.data.CAD_human_JBO0022 <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_human_JBO0022$trait_gene_list <- "CAD_all_genes"

meta.data.CAD_human_JBO0022_top <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_CAD_top50_genes.RDS")
meta.data.CAD_human_JBO0022_top$trait_gene_list <- "CAD_top50_genes"

meta.data.CHOL_human_JBO0022 <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_CHOL_all_genes.RDS")
meta.data.CHOL_human_JBO0022$`median(score_drugs)` <- "N/A"
meta.data.CHOL_human_JBO0022$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_human_JBO0022$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_human_JBO0022 <- meta.data.CHOL_human_JBO0022[,c(1:5,7:9,6)]
meta.data.CHOL_human_JBO0022$trait_gene_list <- "CHOL_all_genes"

meta.data.CHOL_human_JBO0022_top <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_CHOL_top90_genes.RDS")
meta.data.CHOL_human_JBO0022_top$`median(score_drugs)` <- "N/A"
meta.data.CHOL_human_JBO0022_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_human_JBO0022_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_human_JBO0022_top <- meta.data.CHOL_human_JBO0022_top[,c(1:5,7:9,6)]
meta.data.CHOL_human_JBO0022_top$trait_gene_list <- "CHOL_top90_genes"

meta.data.CIRR_human_JBO0022 <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_CIRR_all_genes.RDS")
meta.data.CIRR_human_JBO0022$trait_gene_list <- "CIRR_all_genes"

meta.data.LD_human_JBO0022 <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_LD_all_genes.RDS")
meta.data.LD_human_JBO0022$trait_gene_list <- "LD_all_genes"

meta.data.LD_human_JBO0022_top <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_LD_top80_genes.RDS")
meta.data.LD_human_JBO0022_top$trait_gene_list <- "LD_top80_genes"

meta.data.LDL_human_JBO0022 <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_human_JBO0022$`median(score_drugs)` <- "N/A"
meta.data.LDL_human_JBO0022$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_human_JBO0022$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_human_JBO0022 <- meta.data.LDL_human_JBO0022[,c(1:5,7:9,6)]
meta.data.LDL_human_JBO0022$trait_gene_list <- "LDL_all_genes"

meta.data.LDL_human_JBO0022_top <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_LDL_top90_genes.RDS")
meta.data.LDL_human_JBO0022_top$`median(score_drugs)` <- "N/A"
meta.data.LDL_human_JBO0022_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_human_JBO0022_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_human_JBO0022_top <- meta.data.LDL_human_JBO0022_top[,c(1:5,7:9,6)]
meta.data.LDL_human_JBO0022_top$trait_gene_list <- "LDL_top90_genes"

meta.data.MI_human_JBO0022 <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_human_JBO0022$trait_gene_list <- "MI_all_genes"

meta.data.MI_human_JBO0022_top <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_MI_top60_genes.RDS")
meta.data.MI_human_JBO0022_top$trait_gene_list <- "MI_top60_genes"

meta.data.NAFLD_human_JBO0022 <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_NAFLD_all_genes.RDS")
meta.data.NAFLD_human_JBO0022$trait_gene_list <- "NAFLD_all_genes"

meta.data.NAFLD_human_JBO0022_top <- readRDS(file = "Liver/human_JBO0022/p_value_distribution/pval.distribution_NAFLD_top80_genes.RDS")
meta.data.NAFLD_human_JBO0022_top$trait_gene_list <- "NAFLD_top80_genes"

#Merge
liver_human_JBO0022 <- rbind(meta.data.CAD_human_JBO0022,meta.data.CAD_human_JBO0022_top)
liver_human_JBO0022 <- rbind(liver_human_JBO0022,meta.data.CHOL_human_JBO0022)
liver_human_JBO0022 <- rbind(liver_human_JBO0022,meta.data.CHOL_human_JBO0022_top)
liver_human_JBO0022 <- rbind(liver_human_JBO0022,meta.data.CIRR_human_JBO0022)
liver_human_JBO0022 <- rbind(liver_human_JBO0022,meta.data.LD_human_JBO0022)
liver_human_JBO0022 <- rbind(liver_human_JBO0022,meta.data.LD_human_JBO0022_top)
liver_human_JBO0022 <- rbind(liver_human_JBO0022,meta.data.LDL_human_JBO0022)
liver_human_JBO0022 <- rbind(liver_human_JBO0022,meta.data.LDL_human_JBO0022_top)
liver_human_JBO0022 <- rbind(liver_human_JBO0022,meta.data.MI_human_JBO0022)
liver_human_JBO0022 <- rbind(liver_human_JBO0022,meta.data.MI_human_JBO0022_top)
liver_human_JBO0022 <- rbind(liver_human_JBO0022,meta.data.NAFLD_human_JBO0022)
liver_human_JBO0022 <- rbind(liver_human_JBO0022,meta.data.NAFLD_human_JBO0022_top)

#Add dataset name
liver_human_JBO0022$dataset <- "liver_human_JBO0022"

#Reorder
liver_human_JBO0022 <- liver_human_JBO0022[,c(11:9,1:8)]

```


```{r}
##mouse_JBO002
meta.data.CAD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_mouse_JBO002$trait_gene_list <- "CAD_all_genes"

meta.data.CAD_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_CAD_top70_genes.RDS")
meta.data.CAD_mouse_JBO002_top$trait_gene_list <- "CAD_top70_genes"

meta.data.CHOL_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_CHOL_all_genes.RDS")
meta.data.CHOL_mouse_JBO002$`median(score_drugs)` <- "N/A"
meta.data.CHOL_mouse_JBO002$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_mouse_JBO002$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_mouse_JBO002 <- meta.data.CHOL_mouse_JBO002[,c(1:5,7:9,6)]
meta.data.CHOL_mouse_JBO002$trait_gene_list <- "CHOL_all_genes"

meta.data.CHOL_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_CHOL_top70_genes.RDS")
meta.data.CHOL_mouse_JBO002_top$`median(score_drugs)` <- "N/A"
meta.data.CHOL_mouse_JBO002_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_mouse_JBO002_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_mouse_JBO002_top <- meta.data.CHOL_mouse_JBO002_top[,c(1:5,7:9,6)]
meta.data.CHOL_mouse_JBO002_top$trait_gene_list <- "CHOL_top70_genes"

meta.data.CIRR_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_CIRR_all_genes.RDS")
meta.data.CIRR_mouse_JBO002$trait_gene_list <- "CIRR_all_genes"

meta.data.LD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_LD_all_genes.RDS")
meta.data.LD_mouse_JBO002$trait_gene_list <- "LD_all_genes"

meta.data.LD_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_LD_top60_genes.RDS")
meta.data.LD_mouse_JBO002_top$trait_gene_list <- "LD_top60_genes"

meta.data.LDL_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_mouse_JBO002$`median(score_drugs)` <- "N/A"
meta.data.LDL_mouse_JBO002$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_mouse_JBO002$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_mouse_JBO002 <- meta.data.LDL_mouse_JBO002[,c(1:5,7:9,6)]
meta.data.LDL_mouse_JBO002$trait_gene_list <- "LDL_all_genes"

meta.data.LDL_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_LDL_top90_genes.RDS")
meta.data.LDL_mouse_JBO002_top$`median(score_drugs)` <- "N/A"
meta.data.LDL_mouse_JBO002_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_mouse_JBO002_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_mouse_JBO002_top <- meta.data.LDL_mouse_JBO002_top[,c(1:5,7:9,6)]
meta.data.LDL_mouse_JBO002_top$trait_gene_list <- "LDL_top90_genes"

meta.data.MI_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_mouse_JBO002$trait_gene_list <- "MI_all_genes"

meta.data.MI_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_MI_top50_genes.RDS")
meta.data.MI_mouse_JBO002_top$trait_gene_list <- "MI_top50_genes"

meta.data.NAFLD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_NAFLD_all_genes.RDS")
meta.data.NAFLD_mouse_JBO002$trait_gene_list <- "NAFLD_all_genes"

meta.data.NAFLD_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_NAFLD_top50_genes.RDS")
meta.data.NAFLD_mouse_JBO002_top$trait_gene_list <- "NAFLD_top50_genes"

#Merge
liver_mouse_JBO002 <- rbind(meta.data.CAD_mouse_JBO002,meta.data.CAD_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.CHOL_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.CHOL_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.CIRR_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.LD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.LD_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.LDL_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.LDL_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.MI_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.MI_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.NAFLD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.NAFLD_mouse_JBO002_top)

#Add dataset name
liver_mouse_JBO002$dataset <- "liver_mouse_JBO002"

#Reorder
liver_mouse_JBO002 <- liver_mouse_JBO002[,c(11:9,1:8)]

```


```{r}
##mouse_zonation_C1
meta.data.CAD_mouse_zonation_C1 <- readRDS(file = "Liver/mouse_zonation_C1/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_mouse_zonation_C1$trait_gene_list <- "CAD_all_genes"

meta.data.CAD_mouse_zonation_C1_top <- readRDS(file = "Liver/mouse_zonation_C1/p_value_distribution/pval.distribution_CAD_top60_genes.RDS")
meta.data.CAD_mouse_zonation_C1_top$trait_gene_list <- "CAD_top60_genes"

meta.data.CHOL_mouse_zonation_C1 <- readRDS(file = "Liver/mouse_zonation_C1/p_value_distribution/pval.distribution_CHOL_all_genes.RDS")
meta.data.CHOL_mouse_zonation_C1$`median(score_drugs)` <- "N/A"
meta.data.CHOL_mouse_zonation_C1$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_mouse_zonation_C1$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_mouse_zonation_C1 <- meta.data.CHOL_mouse_zonation_C1[,c(1:5,7:9,6)]
meta.data.CHOL_mouse_zonation_C1$trait_gene_list <- "CHOL_all_genes"

meta.data.CHOL_mouse_zonation_C1_top <- readRDS(file = "Liver/mouse_zonation_C1/p_value_distribution/pval.distribution_CHOL_top70_genes.RDS")
meta.data.CHOL_mouse_zonation_C1_top$`median(score_drugs)` <- "N/A"
meta.data.CHOL_mouse_zonation_C1_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_mouse_zonation_C1_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_mouse_zonation_C1_top <- meta.data.CHOL_mouse_zonation_C1_top[,c(1:5,7:9,6)]
meta.data.CHOL_mouse_zonation_C1_top$trait_gene_list <- "CHOL_top70_genes"

meta.data.CIRR_mouse_zonation_C1 <- readRDS(file = "Liver/mouse_zonation_C1/p_value_distribution/pval.distribution_CIRR_all_genes.RDS")
meta.data.CIRR_mouse_zonation_C1$trait_gene_list <- "CIRR_all_genes"

meta.data.LD_mouse_zonation_C1 <- readRDS(file = "Liver/mouse_zonation_C1/p_value_distribution/pval.distribution_LD_all_genes.RDS")
meta.data.LD_mouse_zonation_C1$trait_gene_list <- "LD_all_genes"

meta.data.LD_mouse_zonation_C1_top <- readRDS(file = "Liver/mouse_zonation_C1/p_value_distribution/pval.distribution_LD_top70_genes.RDS")
meta.data.LD_mouse_zonation_C1_top$trait_gene_list <- "LD_top70_genes"

meta.data.LDL_mouse_zonation_C1 <- readRDS(file = "Liver/mouse_zonation_C1/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_mouse_zonation_C1$`median(score_drugs)` <- "N/A"
meta.data.LDL_mouse_zonation_C1$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_mouse_zonation_C1$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_mouse_zonation_C1 <- meta.data.LDL_mouse_zonation_C1[,c(1:5,7:9,6)]
meta.data.LDL_mouse_zonation_C1$trait_gene_list <- "LDL_all_genes"

meta.data.LDL_mouse_zonation_C1_top <- readRDS(file = "Liver/mouse_zonation_C1/p_value_distribution/pval.distribution_LDL_top70_genes.RDS")
meta.data.LDL_mouse_zonation_C1_top$`median(score_drugs)` <- "N/A"
meta.data.LDL_mouse_zonation_C1_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_mouse_zonation_C1_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_mouse_zonation_C1_top <- meta.data.LDL_mouse_zonation_C1_top[,c(1:5,7:9,6)]
meta.data.LDL_mouse_zonation_C1_top$trait_gene_list <- "LDL_top70_genes"

meta.data.MI_mouse_zonation_C1 <- readRDS(file = "Liver/mouse_zonation_C1/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_mouse_zonation_C1$trait_gene_list <- "MI_all_genes"

meta.data.MI_mouse_zonation_C1_top <- readRDS(file = "Liver/mouse_zonation_C1/p_value_distribution/pval.distribution_MI_top50_genes.RDS")
meta.data.MI_mouse_zonation_C1_top$trait_gene_list <- "MI_top50_genes"

meta.data.NAFLD_mouse_zonation_C1 <- readRDS(file = "Liver/mouse_zonation_C1/p_value_distribution/pval.distribution_NAFLD_all_genes.RDS")
meta.data.NAFLD_mouse_zonation_C1$trait_gene_list <- "NAFLD_all_genes"

#Merge
liver_mouse_zonation_C1 <- rbind(meta.data.CAD_mouse_zonation_C1,meta.data.CAD_mouse_zonation_C1_top)
liver_mouse_zonation_C1 <- rbind(liver_mouse_zonation_C1,meta.data.CHOL_mouse_zonation_C1)
liver_mouse_zonation_C1 <- rbind(liver_mouse_zonation_C1,meta.data.CHOL_mouse_zonation_C1_top)
liver_mouse_zonation_C1 <- rbind(liver_mouse_zonation_C1,meta.data.CIRR_mouse_zonation_C1)
liver_mouse_zonation_C1 <- rbind(liver_mouse_zonation_C1,meta.data.LD_mouse_zonation_C1)
liver_mouse_zonation_C1 <- rbind(liver_mouse_zonation_C1,meta.data.LD_mouse_zonation_C1_top)
liver_mouse_zonation_C1 <- rbind(liver_mouse_zonation_C1,meta.data.LDL_mouse_zonation_C1)
liver_mouse_zonation_C1 <- rbind(liver_mouse_zonation_C1,meta.data.LDL_mouse_zonation_C1_top)
liver_mouse_zonation_C1 <- rbind(liver_mouse_zonation_C1,meta.data.MI_mouse_zonation_C1)
liver_mouse_zonation_C1 <- rbind(liver_mouse_zonation_C1,meta.data.MI_mouse_zonation_C1_top)
liver_mouse_zonation_C1 <- rbind(liver_mouse_zonation_C1,meta.data.NAFLD_mouse_zonation_C1)

#Add dataset name
liver_mouse_zonation_C1$dataset <- "liver_mouse_zonation_C1"

#Reorder
liver_mouse_zonation_C1 <- liver_mouse_zonation_C1[,c(11:9,1:8)]

```


# Lung datasets
```{r}
##HLA_Bronchi_A42_311
meta.data.AST_HLA_Bronchi_A42_311 <- readRDS(file = "Lung/HLA_Bronchi_A42_311/p_value_distribution/pval.distribution_AST_all_genes.RDS")
meta.data.AST_HLA_Bronchi_A42_311$trait_gene_list <- "AST_all_genes"

meta.data.BRD_HLA_Bronchi_A42_311 <- readRDS(file = "Lung/HLA_Bronchi_A42_311/p_value_distribution/pval.distribution_BRD_all_genes.RDS")
meta.data.BRD_HLA_Bronchi_A42_311$trait_gene_list <- "BRD_all_genes"

meta.data.COPD_HLA_Bronchi_A42_311 <- readRDS(file = "Lung/HLA_Bronchi_A42_311/p_value_distribution/pval.distribution_COPD_all_genes.RDS")
meta.data.COPD_HLA_Bronchi_A42_311$trait_gene_list <- "COPD_all_genes"

meta.data.COPD_HLA_Bronchi_A42_311_top <- readRDS(file = "Lung/HLA_Bronchi_A42_311/p_value_distribution/pval.distribution_COPD_top80_genes.RDS")
meta.data.COPD_HLA_Bronchi_A42_311_top$trait_gene_list <- "COPD_top80_genes"

meta.data.LUD_HLA_Bronchi_A42_311 <- readRDS(file = "Lung/HLA_Bronchi_A42_311/p_value_distribution/pval.distribution_LUD_all_genes.RDS")
meta.data.LUD_HLA_Bronchi_A42_311$trait_gene_list <- "LUD_all_genes"

meta.data.LUD_HLA_Bronchi_A42_311_top <- readRDS(file = "Lung/HLA_Bronchi_A42_311/p_value_distribution/pval.distribution_LUD_top90_genes.RDS")
meta.data.LUD_HLA_Bronchi_A42_311_top$trait_gene_list <- "LUD_top90_genes"

#Merge
lung_bronchi_human_A42 <- rbind(meta.data.AST_HLA_Bronchi_A42_311,meta.data.BRD_HLA_Bronchi_A42_311)
lung_bronchi_human_A42 <- rbind(lung_bronchi_human_A42,meta.data.COPD_HLA_Bronchi_A42_311)
lung_bronchi_human_A42 <- rbind(lung_bronchi_human_A42,meta.data.COPD_HLA_Bronchi_A42_311_top)
lung_bronchi_human_A42 <- rbind(lung_bronchi_human_A42,meta.data.LUD_HLA_Bronchi_A42_311)
lung_bronchi_human_A42 <- rbind(lung_bronchi_human_A42,meta.data.LUD_HLA_Bronchi_A42_311_top)

#Add dataset name
lung_bronchi_human_A42$dataset <- "lung_bronchi_human_A42"

#Reorder
lung_bronchi_human_A42 <- lung_bronchi_human_A42[,c(11:9,1:8)]

```


```{r}
##HLA_Bronchi_A50_467
meta.data.AST_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_AST_all_genes.RDS")
meta.data.AST_HLA_Bronchi_A50_467$trait_gene_list <- "AST_all_genes"

meta.data.AST_HLA_Bronchi_A50_467_top <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_AST_top160_genes.RDS")
meta.data.AST_HLA_Bronchi_A50_467_top$trait_gene_list <- "AST_top160_genes"

meta.data.BRD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_BRD_all_genes.RDS")
meta.data.BRD_HLA_Bronchi_A50_467$trait_gene_list <- "BRD_all_genes"

meta.data.BRD_HLA_Bronchi_A50_467_top <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_BRD_top90_genes.RDS")
meta.data.BRD_HLA_Bronchi_A50_467_top$trait_gene_list <- "BRD_top90_genes"

meta.data.COPD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_COPD_all_genes.RDS")
meta.data.COPD_HLA_Bronchi_A50_467$trait_gene_list <- "COPD_all_genes"

meta.data.LUD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_LUD_all_genes.RDS")
meta.data.LUD_HLA_Bronchi_A50_467$trait_gene_list <- "LUD_all_genes"

meta.data.LUD_HLA_Bronchi_A50_467_top <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_LUD_top60_genes.RDS")
meta.data.LUD_HLA_Bronchi_A50_467_top$trait_gene_list <- "LUD_top60_genes"

#Merge
lung_bronchi_human_A50 <- rbind(meta.data.AST_HLA_Bronchi_A50_467,meta.data.AST_HLA_Bronchi_A50_467_top)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.BRD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.BRD_HLA_Bronchi_A50_467_top)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.COPD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.LUD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.LUD_HLA_Bronchi_A50_467_top)

#Add dataset name
lung_bronchi_human_A50$dataset <- "lung_bronchi_human_A50"

#Reorder
lung_bronchi_human_A50 <- lung_bronchi_human_A50[,c(11:9,1:8)]

```


```{r}
##HLA_Parenchyma_A37_347
meta.data.AST_HLA_Parenchyma_A37_347 <- readRDS(file = "Lung/HLA_Parenchyma_A37_347/p_value_distribution/pval.distribution_AST_all_genes.RDS")
meta.data.AST_HLA_Parenchyma_A37_347$trait_gene_list <- "AST_all_genes"

meta.data.BRD_HLA_Parenchyma_A37_347 <- readRDS(file = "Lung/HLA_Parenchyma_A37_347/p_value_distribution/pval.distribution_BRD_all_genes.RDS")
meta.data.BRD_HLA_Parenchyma_A37_347$trait_gene_list <- "BRD_all_genes"

meta.data.COPD_HLA_Parenchyma_A37_347 <- readRDS(file = "Lung/HLA_Parenchyma_A37_347/p_value_distribution/pval.distribution_COPD_all_genes.RDS")
meta.data.COPD_HLA_Parenchyma_A37_347$trait_gene_list <- "COPD_all_genes"

meta.data.COPD_HLA_Parenchyma_A37_347_top <- readRDS(file = "Lung/HLA_Parenchyma_A37_347/p_value_distribution/pval.distribution_COPD_top70_genes.RDS")
meta.data.COPD_HLA_Parenchyma_A37_347_top$trait_gene_list <- "COPD_top70_genes"

meta.data.LUD_HLA_Parenchyma_A37_347 <- readRDS(file = "Lung/HLA_Parenchyma_A37_347/p_value_distribution/pval.distribution_LUD_all_genes.RDS")
meta.data.LUD_HLA_Parenchyma_A37_347$trait_gene_list <- "LUD_all_genes"

meta.data.LUD_HLA_Parenchyma_A37_347_top <- readRDS(file = "Lung/HLA_Parenchyma_A37_347/p_value_distribution/pval.distribution_LUD_top60_genes.RDS")
meta.data.LUD_HLA_Parenchyma_A37_347_top$trait_gene_list <- "LUD_top60_genes"

#Merge
lung_parenchyma_human_A37 <- rbind(meta.data.AST_HLA_Parenchyma_A37_347,meta.data.BRD_HLA_Parenchyma_A37_347)
lung_parenchyma_human_A37 <- rbind(lung_parenchyma_human_A37,meta.data.COPD_HLA_Parenchyma_A37_347)
lung_parenchyma_human_A37 <- rbind(lung_parenchyma_human_A37,meta.data.COPD_HLA_Parenchyma_A37_347_top)
lung_parenchyma_human_A37 <- rbind(lung_parenchyma_human_A37,meta.data.LUD_HLA_Parenchyma_A37_347)
lung_parenchyma_human_A37 <- rbind(lung_parenchyma_human_A37,meta.data.LUD_HLA_Parenchyma_A37_347_top)

#Add dataset name
lung_parenchyma_human_A37$dataset <- "lung_parenchyma_human_A37"

#Reorder
lung_parenchyma_human_A37 <- lung_parenchyma_human_A37[,c(11:9,1:8)]

```


```{r}
##HLA_Parenchyma_A48_345
meta.data.AST_HLA_Parenchyma_A48_345 <- readRDS(file = "Lung/HLA_Parenchyma_A48_345/p_value_distribution/pval.distribution_AST_all_genes.RDS")
meta.data.AST_HLA_Parenchyma_A48_345$trait_gene_list <- "AST_all_genes"

meta.data.BRD_HLA_Parenchyma_A48_345 <- readRDS(file = "Lung/HLA_Parenchyma_A48_345/p_value_distribution/pval.distribution_BRD_all_genes.RDS")
meta.data.BRD_HLA_Parenchyma_A48_345$trait_gene_list <- "BRD_all_genes"

meta.data.COPD_HLA_Parenchyma_A48_345 <- readRDS(file = "Lung/HLA_Parenchyma_A48_345/p_value_distribution/pval.distribution_COPD_all_genes.RDS")
meta.data.COPD_HLA_Parenchyma_A48_345$trait_gene_list <- "COPD_all_genes"

meta.data.LUD_HLA_Parenchyma_A48_345 <- readRDS(file = "Lung/HLA_Parenchyma_A48_345/p_value_distribution/pval.distribution_LUD_all_genes.RDS")
meta.data.LUD_HLA_Parenchyma_A48_345$trait_gene_list <- "LUD_all_genes"

meta.data.LUD_HLA_Parenchyma_A48_345_top <- readRDS(file = "Lung/HLA_Parenchyma_A48_345/p_value_distribution/pval.distribution_LUD_top50_genes.RDS")
meta.data.LUD_HLA_Parenchyma_A48_345_top$trait_gene_list <- "LUD_top50_genes"

#Merge
lung_parenchyma_human_A48 <- rbind(meta.data.AST_HLA_Parenchyma_A48_345,meta.data.BRD_HLA_Parenchyma_A48_345)
lung_parenchyma_human_A48 <- rbind(lung_parenchyma_human_A48,meta.data.COPD_HLA_Parenchyma_A48_345)
lung_parenchyma_human_A48 <- rbind(lung_parenchyma_human_A48,meta.data.LUD_HLA_Parenchyma_A48_345)
lung_parenchyma_human_A48 <- rbind(lung_parenchyma_human_A48,meta.data.LUD_HLA_Parenchyma_A48_345_top)

#Add dataset name
lung_parenchyma_human_A48$dataset <- "lung_parenchyma_human_A48"

#Reorder
lung_parenchyma_human_A48 <- lung_parenchyma_human_A48[,c(11:9,1:8)]

```


# Pancreas datasets
```{r}
##pancreas_human_15PCW_S1
meta.data.T1D_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_T1DM_all_genes.RDS")
meta.data.T1D_pancreas_human_15PCW_S1$trait_gene_list <- "T1D_all_genes"

meta.data.T1D_pancreas_human_15PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_T1DM_top130_genes.RDS")
meta.data.T1D_pancreas_human_15PCW_S1_top$trait_gene_list <- "T1D_top130_genes"

meta.data.T2D_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_T2DM_all_genes.RDS")
meta.data.T2D_pancreas_human_15PCW_S1$trait_gene_list <- "T2D_all_genes"

meta.data.T2D_pancreas_human_15PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_T2DM_top50_genes.RDS")
meta.data.T2D_pancreas_human_15PCW_S1_top$trait_gene_list <- "T2D_top50_genes"

#Merge
pancreas_human_15PCW_S1 <- rbind(meta.data.T1D_pancreas_human_15PCW_S1,meta.data.T1D_pancreas_human_15PCW_S1_top)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.T2D_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.T2D_pancreas_human_15PCW_S1_top)

#Add dataset name
pancreas_human_15PCW_S1$dataset <- "pancreas_human_15PCW_S1"

#Reorder
pancreas_human_15PCW_S1 <- pancreas_human_15PCW_S1[,c(11:9,1:8)]

```


```{r}
##pancreas_human_18PCW_S1
meta.data.T1D_pancreas_human_18PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_18PCW_S1/p_value_distribution/pval.distribution_T1DM_all_genes.RDS")
meta.data.T1D_pancreas_human_18PCW_S1$trait_gene_list <- "T1D_all_genes"

meta.data.T1D_pancreas_human_18PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_18PCW_S1/p_value_distribution/pval.distribution_T1DM_top130_genes.RDS")
meta.data.T1D_pancreas_human_18PCW_S1_top$trait_gene_list <- "T1D_top130_genes"

meta.data.T2D_pancreas_human_18PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_18PCW_S1/p_value_distribution/pval.distribution_T2DM_all_genes.RDS")
meta.data.T2D_pancreas_human_18PCW_S1$trait_gene_list <- "T2D_all_genes"

meta.data.T2D_pancreas_human_18PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_18PCW_S1/p_value_distribution/pval.distribution_T2DM_top90_genes.RDS")
meta.data.T2D_pancreas_human_18PCW_S1_top$trait_gene_list <- "T2D_top90_genes"

#Merge
pancreas_human_18PCW_S1 <- rbind(meta.data.T1D_pancreas_human_18PCW_S1,meta.data.T1D_pancreas_human_18PCW_S1_top)
pancreas_human_18PCW_S1 <- rbind(pancreas_human_18PCW_S1,meta.data.T2D_pancreas_human_18PCW_S1)
pancreas_human_18PCW_S1 <- rbind(pancreas_human_18PCW_S1,meta.data.T2D_pancreas_human_18PCW_S1_top)

#Add dataset name
pancreas_human_18PCW_S1$dataset <- "pancreas_human_18PCW_S1"

#Reorder
pancreas_human_18PCW_S1 <- pancreas_human_18PCW_S1[,c(11:9,1:8)]

```


```{r}
##pancreas_human_20PCW_S1
meta.data.T1D_pancreas_human_20PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_20PCW_S1/p_value_distribution/pval.distribution_T1DM_all_genes.RDS")
meta.data.T1D_pancreas_human_20PCW_S1$trait_gene_list <- "T1D_all_genes"

meta.data.T1D_pancreas_human_20PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_20PCW_S1/p_value_distribution/pval.distribution_T1DM_top130_genes.RDS")
meta.data.T1D_pancreas_human_20PCW_S1_top$trait_gene_list <- "T1D_top130_genes"

meta.data.T2D_pancreas_human_20PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_20PCW_S1/p_value_distribution/pval.distribution_T2DM_all_genes.RDS")
meta.data.T2D_pancreas_human_20PCW_S1$trait_gene_list <- "T2D_all_genes"

meta.data.T2D_pancreas_human_20PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_20PCW_S1/p_value_distribution/pval.distribution_T2DM_top90_genes.RDS")
meta.data.T2D_pancreas_human_20PCW_S1_top$trait_gene_list <- "T2D_top90_genes"

#Merge
pancreas_human_20PCW_S1 <- rbind(meta.data.T1D_pancreas_human_20PCW_S1,meta.data.T1D_pancreas_human_20PCW_S1_top)
pancreas_human_20PCW_S1 <- rbind(pancreas_human_20PCW_S1,meta.data.T2D_pancreas_human_20PCW_S1)
pancreas_human_20PCW_S1 <- rbind(pancreas_human_20PCW_S1,meta.data.T2D_pancreas_human_20PCW_S1_top)

#Add dataset name
pancreas_human_20PCW_S1$dataset <- "pancreas_human_20PCW_S1"

#Reorder
pancreas_human_20PCW_S1 <- pancreas_human_20PCW_S1[,c(11:9,1:8)]

```


# Spinal cord datasets
```{r}
##w5_V10T03_302B1
meta.data.AHD_w5_V10T03_302B1 <- readRDS(file = "Spinal_cord/w5_V10T03_302B1/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_w5_V10T03_302B1$trait_gene_list <- "AHD_all_genes"

meta.data.ALS_w5_V10T03_302B1 <- readRDS(file = "Spinal_cord/w5_V10T03_302B1/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_w5_V10T03_302B1$trait_gene_list <- "ALS_all_genes"

meta.data.MS_w5_V10T03_302B1 <- readRDS(file = "Spinal_cord/w5_V10T03_302B1/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_w5_V10T03_302B1$trait_gene_list <- "MS_all_genes"

#Merge
spinal_cord_human_pcw5_302B1 <- rbind(meta.data.AHD_w5_V10T03_302B1,meta.data.ALS_w5_V10T03_302B1)
spinal_cord_human_pcw5_302B1 <- rbind(spinal_cord_human_pcw5_302B1,meta.data.MS_w5_V10T03_302B1)

#Add dataset name
spinal_cord_human_pcw5_302B1$dataset <- "spinal_cord_human_pcw5_302B1"

#Reorder
spinal_cord_human_pcw5_302B1 <- spinal_cord_human_pcw5_302B1[,c(11:9,1:8)]

```


```{r}
##w8_V10F24_107B1
meta.data.AHD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_w8_V10F24_107B1$trait_gene_list <- "AHD_all_genes"

meta.data.AHD_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_AHD_top50_genes.RDS")
meta.data.AHD_w8_V10F24_107B1_top$trait_gene_list <- "AHD_top50_genes"

meta.data.ALS_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_w8_V10F24_107B1$trait_gene_list <- "ALS_all_genes"

meta.data.ALS_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_ALS_top70_genes.RDS")
meta.data.ALS_w8_V10F24_107B1_top$trait_gene_list <- "ALS_top70_genes"

meta.data.MS_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_w8_V10F24_107B1$trait_gene_list <- "MS_all_genes"

#Merge
spinal_cord_human_pcw8_107B1 <- rbind(meta.data.AHD_w8_V10F24_107B1,meta.data.AHD_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.ALS_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.ALS_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.MS_w8_V10F24_107B1)

#Add dataset name
spinal_cord_human_pcw8_107B1$dataset <- "spinal_cord_human_pcw8_107B1"

#Reorder
spinal_cord_human_pcw8_107B1 <- spinal_cord_human_pcw8_107B1[,c(11:9,1:8)]

```


```{r}
##w9_V10T03_288A1
meta.data.AHD_w9_V10T03_288A1 <- readRDS(file = "Spinal_cord/w9_V10T03_288A1/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_w9_V10T03_288A1$trait_gene_list <- "AHD_all_genes"

meta.data.AHD_w9_V10T03_288A1_top <- readRDS(file = "Spinal_cord/w9_V10T03_288A1/p_value_distribution/pval.distribution_AHD_top90_genes.RDS")
meta.data.AHD_w9_V10T03_288A1_top$trait_gene_list <- "AHD_top90_genes"

meta.data.ALS_w9_V10T03_288A1 <- readRDS(file = "Spinal_cord/w9_V10T03_288A1/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_w9_V10T03_288A1$trait_gene_list <- "ALS_all_genes"

meta.data.ALS_w9_V10T03_288A1_top <- readRDS(file = "Spinal_cord/w9_V10T03_288A1/p_value_distribution/pval.distribution_ALS_top70_genes.RDS")
meta.data.ALS_w9_V10T03_288A1_top$trait_gene_list <- "ALS_top70_genes"

meta.data.MS_w9_V10T03_288A1 <- readRDS(file = "Spinal_cord/w9_V10T03_288A1/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_w9_V10T03_288A1$trait_gene_list <- "MS_all_genes"

meta.data.MS_w9_V10T03_288A1_top <- readRDS(file = "Spinal_cord/w9_V10T03_288A1/p_value_distribution/pval.distribution_MS_top110_genes.RDS")
meta.data.MS_w9_V10T03_288A1_top$trait_gene_list <- "MS_top110_genes"

#Merge
spinal_cord_human_pcw9_288A1 <- rbind(meta.data.AHD_w9_V10T03_288A1,meta.data.AHD_w9_V10T03_288A1_top)
spinal_cord_human_pcw9_288A1 <- rbind(spinal_cord_human_pcw9_288A1,meta.data.ALS_w9_V10T03_288A1)
spinal_cord_human_pcw9_288A1 <- rbind(spinal_cord_human_pcw9_288A1,meta.data.ALS_w9_V10T03_288A1_top)
spinal_cord_human_pcw9_288A1 <- rbind(spinal_cord_human_pcw9_288A1,meta.data.MS_w9_V10T03_288A1)
spinal_cord_human_pcw9_288A1 <- rbind(spinal_cord_human_pcw9_288A1,meta.data.MS_w9_V10T03_288A1_top)

#Add dataset name
spinal_cord_human_pcw9_288A1$dataset <- "spinal_cord_human_pcw9_288A1"

#Reorder
spinal_cord_human_pcw9_288A1 <- spinal_cord_human_pcw9_288A1[,c(11:9,1:8)]

```


```{r}
##w12_V10T03_290D1
meta.data.AHD_w12_V10T03_290D1 <- readRDS(file = "Spinal_cord/w12_V10T03_290D1/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_w12_V10T03_290D1$trait_gene_list <- "AHD_all_genes"

meta.data.ALS_w12_V10T03_290D1 <- readRDS(file = "Spinal_cord/w12_V10T03_290D1/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_w12_V10T03_290D1$trait_gene_list <- "ALS_all_genes"

meta.data.ALS_w12_V10T03_290D1_top <- readRDS(file = "Spinal_cord/w12_V10T03_290D1/p_value_distribution/pval.distribution_ALS_top80_genes.RDS")
meta.data.ALS_w12_V10T03_290D1_top$trait_gene_list <- "ALS_top80_genes"

meta.data.MS_w12_V10T03_290D1 <- readRDS(file = "Spinal_cord/w12_V10T03_290D1/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_w12_V10T03_290D1$trait_gene_list <- "MS_all_genes"

#Merge
spinal_cord_human_pcw12_290D1 <- rbind(meta.data.AHD_w12_V10T03_290D1,meta.data.ALS_w12_V10T03_290D1)
spinal_cord_human_pcw12_290D1 <- rbind(spinal_cord_human_pcw12_290D1,meta.data.ALS_w12_V10T03_290D1_top)
spinal_cord_human_pcw12_290D1 <- rbind(spinal_cord_human_pcw12_290D1,meta.data.MS_w12_V10T03_290D1)

#Add dataset name
spinal_cord_human_pcw12_290D1$dataset <- "spinal_cord_human_pcw12_290D1"

#Reorder
spinal_cord_human_pcw12_290D1 <- spinal_cord_human_pcw12_290D1[,c(11:9,1:8)]

```

#Save
```{r}
#Merge all
pval_data <- rbind(brain_human_151509,brain_human_151673)
pval_data <- rbind(pval_data,brain_mouse_10X)
pval_data <- rbind(pval_data,brain_mouse_cell2location)
pval_data <- rbind(pval_data,heart_human_adult_ACH003)
pval_data <- rbind(pval_data,heart_human_adult_ACH004)
pval_data <- rbind(pval_data,heart_human_pcw6.5_nr8)
pval_data <- rbind(pval_data,heart_human_pcw9_nr16)
pval_data <- rbind(pval_data,intestine_human_adult_HFGA_A1)
pval_data <- rbind(pval_data,intestine_human_adult_RRST_349_B1)
pval_data <- rbind(pval_data,intestine_human_pcw12_HFGA_A8)
pval_data <- rbind(pval_data,intestine_human_pcw19_HFGA_A4)
pval_data <- rbind(pval_data,intestine_mouse_healing_ctrl)
pval_data <- rbind(pval_data,kidney_human_JCI)
pval_data <- rbind(pval_data,kidney_mouse_10X)
pval_data <- rbind(pval_data,kidney_mouse_JCI)
pval_data <- rbind(pval_data,liver_human_JBO0018)
pval_data <- rbind(pval_data,liver_human_JBO0022)
pval_data <- rbind(pval_data,liver_mouse_JBO002)
pval_data <- rbind(pval_data,liver_mouse_zonation_C1)
pval_data <- rbind(pval_data,lung_bronchi_human_A42)
pval_data <- rbind(pval_data,lung_bronchi_human_A50)
pval_data <- rbind(pval_data,lung_parenchyma_human_A37)
pval_data <- rbind(pval_data,lung_parenchyma_human_A48)
pval_data <- rbind(pval_data,pancreas_human_15PCW_S1)
pval_data <- rbind(pval_data,pancreas_human_18PCW_S1)
pval_data <- rbind(pval_data,pancreas_human_20PCW_S1)
pval_data <- rbind(pval_data,spinal_cord_human_pcw5_302B1)
pval_data <- rbind(pval_data,spinal_cord_human_pcw8_107B1)
pval_data <- rbind(pval_data,spinal_cord_human_pcw9_288A1)
pval_data <- rbind(pval_data,spinal_cord_human_pcw12_290D1)
```


```{r}
names(pval_data)

colnames(pval_data) <-c("dataset","trait_gene_list","cluster","median.genes","median.umi","median.score_genetic","neg.log10.p.val_genetic","neg.log10.p.val.adj_genetic","median.score_drugs","neg.log10.p.val_drugs","neg.log10.p.val.adj_drugs")

names(pval_data)
```


p-values all genes
```{r}
pval_data_all <- pval_data[!grepl("top", pval_data$trait_gene_list), ]
```

p-values top genes
```{r}
pval_data_top <- pval_data[grepl("top", pval_data$trait_gene_list), ]

pval_data_top$median.score_drugs <- "N/A"
pval_data_top$neg.log10.p.val_drugs <- "N/A"
pval_data_top$neg.log10.p.val.adj_drugs <- "N/A"
```

Merge
```{r}
pval_data <- rbind(pval_data_all,pval_data_top)
```

Separate
```{r}
pval_data <- separate(pval_data, trait_gene_list, into = c("trait", "gene_list"), sep = "_", extra = "merge")
```


```{r}
write.table(pval_data,file="pval_distribution_[all_datasets]_summary_selected_tissue_trait_pairs.csv",row.names = F,sep = ";")
```


# Notes
```{r}
sessionInfo()
```

