---
title: "pval_distribution_[all_datasets]_summary_non_selected_tissue_trait_pairs"
author: "Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
 html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

NOTE: Creates a summary file for all calculated p-values of all non-selected tissue-trait pairs.

#Load libraries
```{r}
library(dplyr)
library(tidyr)
```


# Brain datasets

```{r}
##_10X_Visium_mouse_brain_coronal
meta.data.AST_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_AST_all_genes.RDS")
meta.data.AST_10X_Visium_mouse_brain_coronal$trait_gene_list <- "AST_all_genes"

meta.data.BRD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_BRD_all_genes.RDS")
meta.data.BRD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "BRD_all_genes"

meta.data.CAD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "CAD_all_genes"

meta.data.CAD_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_CAD_top80_genes.RDS")
meta.data.CAD_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "CAD_top80_genes"

meta.data.CD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_CD_all_genes.RDS")
meta.data.CD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "CD_all_genes"

meta.data.CHD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_CHD_all_genes.RDS")
meta.data.CHD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "CHD_all_genes"

meta.data.CHD_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_CHD_top80_genes.RDS")
meta.data.CHD_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "CHD_top80_genes"

meta.data.CHOL_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_CHOL_all_genes.RDS")
meta.data.CHOL_10X_Visium_mouse_brain_coronal$`median(score_drugs)` <- "N/A"
meta.data.CHOL_10X_Visium_mouse_brain_coronal$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_10X_Visium_mouse_brain_coronal$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_10X_Visium_mouse_brain_coronal <- meta.data.CHOL_10X_Visium_mouse_brain_coronal[,c(1:5,7:9,6)]
meta.data.CHOL_10X_Visium_mouse_brain_coronal$trait_gene_list <- "CHOL_all_genes"

meta.data.CHOL_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_CHOL_top80_genes.RDS")
meta.data.CHOL_10X_Visium_mouse_brain_coronal_top$`median(score_drugs)` <- "N/A"
meta.data.CHOL_10X_Visium_mouse_brain_coronal_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_10X_Visium_mouse_brain_coronal_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_10X_Visium_mouse_brain_coronal_top <- meta.data.CHOL_10X_Visium_mouse_brain_coronal_top[,c(1:5,7:9,6)]
meta.data.CHOL_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "CHOL_top80_genes"

meta.data.CIRR_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_CIRR_all_genes.RDS")
meta.data.CIRR_10X_Visium_mouse_brain_coronal$trait_gene_list <- "CIRR_all_genes"

meta.data.CKD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_CKD_all_genes.RDS")
meta.data.CKD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "CKD_all_genes"

meta.data.CKD_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_CKD_top120_genes.RDS")
meta.data.CKD_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "CKD_top120_genes"

meta.data.COPD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_COPD_all_genes.RDS")
meta.data.COPD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "COPD_all_genes"

meta.data.COPD_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_COPD_top80_genes.RDS")
meta.data.COPD_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "COPD_top80_genes"

meta.data.IBD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_IBD_all_genes.RDS")
meta.data.IBD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "IBD_all_genes"

meta.data.IKD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_IKD_all_genes.RDS")
meta.data.IKD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "IKD_all_genes"

meta.data.IKD_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_IKD_top50_genes.RDS")
meta.data.IKD_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "IKD_top50_genes"

meta.data.LD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_LD_all_genes.RDS")
meta.data.LD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "LD_all_genes"

meta.data.LD_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_LD_top70_genes.RDS")
meta.data.LD_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "LD_top70_genes"

meta.data.LDL_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_10X_Visium_mouse_brain_coronal$`median(score_drugs)` <- "N/A"
meta.data.LDL_10X_Visium_mouse_brain_coronal$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_10X_Visium_mouse_brain_coronal$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_10X_Visium_mouse_brain_coronal <- meta.data.LDL_10X_Visium_mouse_brain_coronal[,c(1:5,7:9,6)]
meta.data.LDL_10X_Visium_mouse_brain_coronal$trait_gene_list <- "LDL_all_genes"

meta.data.LDL_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_LDL_top100_genes.RDS")
meta.data.LDL_10X_Visium_mouse_brain_coronal_top$`median(score_drugs)` <- "N/A"
meta.data.LDL_10X_Visium_mouse_brain_coronal_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_10X_Visium_mouse_brain_coronal_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_10X_Visium_mouse_brain_coronal_top <- meta.data.LDL_10X_Visium_mouse_brain_coronal_top[,c(1:5,7:9,6)]
meta.data.LDL_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "LDL_top100_genes"

meta.data.LID_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_LID_all_genes.RDS")
meta.data.LID_10X_Visium_mouse_brain_coronal$trait_gene_list <- "LID_all_genes"

meta.data.LID_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_LID_top170_genes.RDS")
meta.data.LID_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "LID_top170_genes"

meta.data.LUD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_LUD_all_genes.RDS")
meta.data.LUD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "LUD_all_genes"

meta.data.LUD_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_LUD_top170_genes.RDS")
meta.data.LUD_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "LUD_top170_genes"

meta.data.MI_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_10X_Visium_mouse_brain_coronal$trait_gene_list <- "MI_all_genes"

meta.data.MI_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_MI_top80_genes.RDS")
meta.data.MI_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "MI_top80_genes"

meta.data.NAFLD_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_NAFLD_all_genes.RDS")
meta.data.NAFLD_10X_Visium_mouse_brain_coronal$trait_gene_list <- "NAFLD_all_genes"

meta.data.NAFLD_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_NAFLD_top90_genes.RDS")
meta.data.NAFLD_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "NAFLD_top90_genes"

meta.data.T1D_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_T1D_all_genes.RDS")
meta.data.T1D_10X_Visium_mouse_brain_coronal$trait_gene_list <- "T1D_all_genes"

meta.data.T1D_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_T1D_top50_genes.RDS")
meta.data.T1D_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "T1D_top50_genes"

meta.data.T2D_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_T2D_all_genes.RDS")
meta.data.T2D_10X_Visium_mouse_brain_coronal$trait_gene_list <- "T2D_all_genes"

meta.data.T2D_10X_Visium_mouse_brain_coronal_top <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_T2D_top50_genes.RDS")
meta.data.T2D_10X_Visium_mouse_brain_coronal_top$trait_gene_list <- "T2D_top50_genes"

meta.data.UC_10X_Visium_mouse_brain_coronal <- readRDS(file = "Brain/10X_Visium_mouse_brain_coronal/p_value_distribution/pval.distribution_UC_all_genes.RDS")
meta.data.UC_10X_Visium_mouse_brain_coronal$trait_gene_list <- "UC_all_genes"

#Merge
brain_mouse_10X <- rbind(meta.data.AST_10X_Visium_mouse_brain_coronal,meta.data.BRD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.CAD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.CAD_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.CD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.CHD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.CHD_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.CHOL_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.CHOL_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.CIRR_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.CKD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.CKD_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.COPD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.COPD_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.IBD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.IKD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.IKD_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.LD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.LD_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.LDL_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.LDL_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.LID_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.LID_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.LUD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.LUD_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.MI_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.MI_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.NAFLD_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.NAFLD_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.T1D_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.T1D_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.T2D_10X_Visium_mouse_brain_coronal)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.T2D_10X_Visium_mouse_brain_coronal_top)
brain_mouse_10X <- rbind(brain_mouse_10X,meta.data.UC_10X_Visium_mouse_brain_coronal)

#Add dataset name
brain_mouse_10X$dataset <- "brain_mouse_10X"

#Reorder
brain_mouse_10X <- brain_mouse_10X[,c(11:9,1:8)]

```


# Heart datasets
```{r}
##adult_ACH003
meta.data.ADHD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_ADHD_all_genes.RDS")
meta.data.ADHD_adult_ACH003$trait_gene_list <- "ADHD_all_genes"

meta.data.AHD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_adult_ACH003$trait_gene_list <- "AHD_all_genes"

meta.data.ALS_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_adult_ACH003$trait_gene_list <- "ALS_all_genes"

meta.data.ALZ_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_ALZ_all_genes.RDS")
meta.data.ALZ_adult_ACH003$trait_gene_list <- "ALZ_all_genes"

meta.data.ALZ_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_ALZ_top60_genes.RDS")
meta.data.ALZ_adult_ACH003_top$trait_gene_list <- "ALZ_top60_genes"

meta.data.ASD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_ASD_all_genes.RDS")
meta.data.ASD_adult_ACH003$trait_gene_list <- "ASD_all_genes"

meta.data.AST_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_AST_all_genes.RDS")
meta.data.AST_adult_ACH003$trait_gene_list <- "AST_all_genes"

meta.data.BIP_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_BIP_all_genes.RDS")
meta.data.BIP_adult_ACH003$trait_gene_list <- "BIP_all_genes"

meta.data.BRD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_BRD_all_genes.RDS")
meta.data.BRD_adult_ACH003$trait_gene_list <- "BRD_all_genes"

meta.data.BRD_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_BRD_top70_genes.RDS")
meta.data.BRD_adult_ACH003_top$trait_gene_list <- "BRD_top70_genes"

meta.data.CD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_CD_all_genes.RDS")
meta.data.CD_adult_ACH003$trait_gene_list <- "CD_all_genes"

meta.data.CD_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_CD_top150_genes.RDS")
meta.data.CD_adult_ACH003_top$trait_gene_list <- "CD_top150_genes"

meta.data.CHOL_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_CHOL_all_genes.RDS")
meta.data.CHOL_adult_ACH003$`median(score_drugs)` <- "N/A"
meta.data.CHOL_adult_ACH003$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_adult_ACH003$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_adult_ACH003 <- meta.data.CHOL_adult_ACH003[,c(1:5,7:9,6)]
meta.data.CHOL_adult_ACH003$trait_gene_list <- "CHOL_all_genes"

meta.data.CHOL_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_CHOL_top80_genes.RDS")
meta.data.CHOL_adult_ACH003_top$`median(score_drugs)` <- "N/A"
meta.data.CHOL_adult_ACH003_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_adult_ACH003_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_adult_ACH003_top <- meta.data.CHOL_adult_ACH003_top[,c(1:5,7:9,6)]
meta.data.CHOL_adult_ACH003_top$trait_gene_list <- "CHOL_top80_genes"

meta.data.CIRR_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_CIRR_all_genes.RDS")
meta.data.CIRR_adult_ACH003$trait_gene_list <- "CIRR_all_genes"

meta.data.CKD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_CKD_all_genes.RDS")
meta.data.CKD_adult_ACH003$trait_gene_list <- "CKD_all_genes"

meta.data.COPD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_COPD_all_genes.RDS")
meta.data.COPD_adult_ACH003$trait_gene_list <- "COPD_all_genes"

meta.data.EPI_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_EPI_all_genes.RDS")
meta.data.EPI_adult_ACH003$trait_gene_list <- "EPI_all_genes"

meta.data.EPI_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_EPI_top160_genes.RDS")
meta.data.EPI_adult_ACH003_top$trait_gene_list <- "EPI_top160_genes"

meta.data.IBD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_IBD_all_genes.RDS")
meta.data.IBD_adult_ACH003$trait_gene_list <- "IBD_all_genes"

meta.data.IBD_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_IBD_top210_genes.RDS")
meta.data.IBD_adult_ACH003_top$trait_gene_list <- "IBD_top210_genes"

meta.data.IKD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_IKD_all_genes.RDS")
meta.data.IKD_adult_ACH003$trait_gene_list <- "IKD_all_genes"

meta.data.IKD_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_IKD_top250_genes.RDS")
meta.data.IKD_adult_ACH003_top$trait_gene_list <- "IKD_top250_genes"

meta.data.INS_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_INS_all_genes.RDS")
meta.data.INS_adult_ACH003$trait_gene_list <- "INS_all_genes"

meta.data.LD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_LD_all_genes.RDS")
meta.data.LD_adult_ACH003$trait_gene_list <- "LD_all_genes"

meta.data.LID_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_LID_all_genes.RDS")
meta.data.LID_adult_ACH003$trait_gene_list <- "LID_all_genes"

meta.data.LID_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_LID_top130_genes.RDS")
meta.data.LID_adult_ACH003_top$trait_gene_list <- "LID_top130_genes"

meta.data.LUD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_LUD_all_genes.RDS")
meta.data.LUD_adult_ACH003$trait_gene_list <- "LUD_all_genes"

meta.data.MDD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_MDD_all_genes.RDS")
meta.data.MDD_adult_ACH003$trait_gene_list <- "MDD_all_genes"

meta.data.MS_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_adult_ACH003$trait_gene_list <- "MS_all_genes"

meta.data.NAFLD_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_NAFLD_all_genes.RDS")
meta.data.NAFLD_adult_ACH003$trait_gene_list <- "NAFLD_all_genes"

meta.data.PAR_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_PAR_all_genes.RDS")
meta.data.PAR_adult_ACH003$trait_gene_list <- "PAR_all_genes"

meta.data.PAR_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_PAR_top90_genes.RDS")
meta.data.PAR_adult_ACH003_top$trait_gene_list <- "PAR_top90_genes"

meta.data.SCZ_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_SCZ_all_genes.RDS")
meta.data.SCZ_adult_ACH003$trait_gene_list <- "SCZ_all_genes"

meta.data.T1D_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_T1D_all_genes.RDS")
meta.data.T1D_adult_ACH003$trait_gene_list <- "T1D_all_genes"

meta.data.T1D_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_T1D_top210_genes.RDS")
meta.data.T1D_adult_ACH003_top$trait_gene_list <- "T1D_top210_genes"

meta.data.T2D_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_T2D_all_genes.RDS")
meta.data.T2D_adult_ACH003$trait_gene_list <- "T2D_all_genes"

meta.data.UC_adult_ACH003 <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_UC_all_genes.RDS")
meta.data.UC_adult_ACH003$trait_gene_list <- "UC_all_genes"

meta.data.UC_adult_ACH003_top <- readRDS(file = "Heart/adult_ACH003/p_value_distribution/pval.distribution_UC_top90_genes.RDS")
meta.data.UC_adult_ACH003_top$trait_gene_list <- "UC_top90_genes"

#Merge
heart_human_adult_ACH003 <- rbind(meta.data.ADHD_adult_ACH003,meta.data.AHD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.ALS_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.ALZ_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.ALZ_adult_ACH003_top)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.ASD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.AST_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.BIP_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.BRD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.BRD_adult_ACH003_top)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.CD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.CD_adult_ACH003_top)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.CHOL_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.CHOL_adult_ACH003_top)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.CIRR_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.CKD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.COPD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.EPI_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.IBD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.IBD_adult_ACH003_top)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.IKD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.IKD_adult_ACH003_top)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.INS_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.LD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.LID_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.LID_adult_ACH003_top)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.LUD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.MDD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.MS_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.NAFLD_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.PAR_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.PAR_adult_ACH003_top)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.SCZ_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.T1D_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.T1D_adult_ACH003_top)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.T2D_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.UC_adult_ACH003)
heart_human_adult_ACH003 <- rbind(heart_human_adult_ACH003,meta.data.UC_adult_ACH003_top)

#Add dataset name
heart_human_adult_ACH003$dataset <- "heart_human_adult_ACH003"

#Reorder
heart_human_adult_ACH003 <- heart_human_adult_ACH003[,c(11:9,1:8)]

```


# Intestine datasets
```{r}
##adult_HFGA_A1
meta.data.ADHD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_ADHD_all_genes.RDS")
meta.data.ADHD_adult_HFGA_A1$trait_gene_list <- "ADHD_all_genes"

meta.data.AHD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_adult_HFGA_A1$trait_gene_list <- "AHD_all_genes"

meta.data.ALS_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_adult_HFGA_A1$trait_gene_list <- "ALS_all_genes"

meta.data.ALZ_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_ALZ_all_genes.RDS")
meta.data.ALZ_adult_HFGA_A1$trait_gene_list <- "ALZ_all_genes"

meta.data.ALZ_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_ALZ_top60_genes.RDS")
meta.data.ALZ_adult_HFGA_A1_top$trait_gene_list <- "ALZ_top60_genes"

meta.data.ASD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_ASD_all_genes.RDS")
meta.data.ASD_adult_HFGA_A1$trait_gene_list <- "ASD_all_genes"

meta.data.AST_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_AST_all_genes.RDS")
meta.data.AST_adult_HFGA_A1$trait_gene_list <- "AST_all_genes"

meta.data.AST_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_AST_top150_genes.RDS")
meta.data.AST_adult_HFGA_A1_top$trait_gene_list <- "AST_top150_genes"

meta.data.BIP_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_BIP_all_genes.RDS")
meta.data.BIP_adult_HFGA_A1$trait_gene_list <- "BIP_all_genes"

meta.data.BIP_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_BIP_top230_genes.RDS")
meta.data.BIP_adult_HFGA_A1_top$trait_gene_list <- "BIP_top230_genes"

meta.data.BRD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_BRD_all_genes.RDS")
meta.data.BRD_adult_HFGA_A1$trait_gene_list <- "BRD_all_genes"

meta.data.CAD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_adult_HFGA_A1$trait_gene_list <- "CAD_all_genes"

meta.data.CAD_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_CAD_top60_genes.RDS")
meta.data.CAD_adult_HFGA_A1_top$trait_gene_list <- "CAD_top60_genes"

meta.data.CHD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_CHD_all_genes.RDS")
meta.data.CHD_adult_HFGA_A1$trait_gene_list <- "CHD_all_genes"

meta.data.CHD_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_CHD_top50_genes.RDS")
meta.data.CHD_adult_HFGA_A1_top$trait_gene_list <- "CHD_top50_genes"

meta.data.CHOL_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_CHOL_all_genes.RDS")
meta.data.CHOL_adult_HFGA_A1$`median(score_drugs)` <- "N/A"
meta.data.CHOL_adult_HFGA_A1$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_adult_HFGA_A1$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_adult_HFGA_A1 <- meta.data.CHOL_adult_HFGA_A1[,c(1:5,7:9,6)]
meta.data.CHOL_adult_HFGA_A1$trait_gene_list <- "CHOL_all_genes"

meta.data.CHOL_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_CHOL_top70_genes.RDS")
meta.data.CHOL_adult_HFGA_A1_top$`median(score_drugs)` <- "N/A"
meta.data.CHOL_adult_HFGA_A1_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_adult_HFGA_A1_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_adult_HFGA_A1_top <- meta.data.CHOL_adult_HFGA_A1_top[,c(1:5,7:9,6)]
meta.data.CHOL_adult_HFGA_A1_top$trait_gene_list <- "CHOL_top70_genes"

meta.data.CIRR_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_CIRR_all_genes.RDS")
meta.data.CIRR_adult_HFGA_A1$trait_gene_list <- "CIRR_all_genes"

meta.data.CIRR_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_CIRR_top70_genes.RDS")
meta.data.CIRR_adult_HFGA_A1_top$trait_gene_list <- "CIRR_top70_genes"

meta.data.CKD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_CKD_all_genes.RDS")
meta.data.CKD_adult_HFGA_A1$trait_gene_list <- "CKD_all_genes"

meta.data.COPD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_COPD_all_genes.RDS")
meta.data.COPD_adult_HFGA_A1$trait_gene_list <- "COPD_all_genes"

meta.data.EPI_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_EPI_all_genes.RDS")
meta.data.EPI_adult_HFGA_A1$trait_gene_list <- "EPI_all_genes"

meta.data.EPI_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_EPI_top130_genes.RDS")
meta.data.EPI_adult_HFGA_A1_top$trait_gene_list <- "EPI_top130_genes"

meta.data.IKD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_IKD_all_genes.RDS")
meta.data.IKD_adult_HFGA_A1$trait_gene_list <- "IKD_all_genes"

meta.data.IKD_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_IKD_top240_genes.RDS")
meta.data.IKD_adult_HFGA_A1_top$trait_gene_list <- "IKD_top240_genes"

meta.data.INS_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_INS_all_genes.RDS")
meta.data.INS_adult_HFGA_A1$trait_gene_list <- "INS_all_genes"

meta.data.LD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_LD_all_genes.RDS")
meta.data.LD_adult_HFGA_A1$trait_gene_list <- "LD_all_genes"

meta.data.LD_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_LD_top120_genes.RDS")
meta.data.LD_adult_HFGA_A1_top$trait_gene_list <- "LD_top120_genes"

meta.data.LDL_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_adult_HFGA_A1$`median(score_drugs)` <- "N/A"
meta.data.LDL_adult_HFGA_A1$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_adult_HFGA_A1$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_adult_HFGA_A1 <- meta.data.LDL_adult_HFGA_A1[,c(1:5,7:9,6)]
meta.data.LDL_adult_HFGA_A1$trait_gene_list <- "LDL_all_genes"

meta.data.LDL_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_LDL_top70_genes.RDS")
meta.data.LDL_adult_HFGA_A1_top$`median(score_drugs)` <- "N/A"
meta.data.LDL_adult_HFGA_A1_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_adult_HFGA_A1_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_adult_HFGA_A1_top <- meta.data.LDL_adult_HFGA_A1_top[,c(1:5,7:9,6)]
meta.data.LDL_adult_HFGA_A1_top$trait_gene_list <- "LDL_top70_genes"

meta.data.LUD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_LUD_all_genes.RDS")
meta.data.LUD_adult_HFGA_A1$trait_gene_list <- "LUD_all_genes"

meta.data.LUD_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_LUD_top190_genes.RDS")
meta.data.LUD_adult_HFGA_A1_top$trait_gene_list <- "LUD_top190_genes"

meta.data.MDD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_MDD_all_genes.RDS")
meta.data.MDD_adult_HFGA_A1$trait_gene_list <- "MDD_all_genes"

meta.data.MI_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_adult_HFGA_A1$trait_gene_list <- "MI_all_genes"

meta.data.MS_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_adult_HFGA_A1$trait_gene_list <- "MS_all_genes"

meta.data.NAFLD_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_NAFLD_all_genes.RDS")
meta.data.NAFLD_adult_HFGA_A1$trait_gene_list <- "NAFLD_all_genes"

meta.data.PAR_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_PAR_all_genes.RDS")
meta.data.PAR_adult_HFGA_A1$trait_gene_list <- "PAR_all_genes"

meta.data.PAR_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_PAR_top80_genes.RDS")
meta.data.PAR_adult_HFGA_A1_top$trait_gene_list <- "PAR_top80_genes"

meta.data.SCZ_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_SCZ_all_genes.RDS")
meta.data.SCZ_adult_HFGA_A1$trait_gene_list <- "SCZ_all_genes"

meta.data.T1D_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_T1D_all_genes.RDS")
meta.data.T1D_adult_HFGA_A1$trait_gene_list <- "T1D_all_genes"

meta.data.T1D_adult_HFGA_A1_top <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_T1D_top90_genes.RDS")
meta.data.T1D_adult_HFGA_A1_top$trait_gene_list <- "T1D_top90_genes"

meta.data.T2D_adult_HFGA_A1 <- readRDS(file = "Intestine/adult_HFGA_A1/p_value_distribution/pval.distribution_T2D_all_genes.RDS")
meta.data.T2D_adult_HFGA_A1$trait_gene_list <- "T2D_all_genes"

#Merge
intestine_human_adult_HFGA_A1 <- rbind(meta.data.ADHD_adult_HFGA_A1,meta.data.AHD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.ALS_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.ALZ_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.ALZ_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.ASD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.AST_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.AST_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.BIP_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.BIP_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.BRD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.CAD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.CAD_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.CHD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.CHD_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.CHOL_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.CHOL_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.CIRR_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.CIRR_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.CKD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.COPD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.EPI_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.EPI_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.IKD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.IKD_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.INS_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.LD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.LD_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.LDL_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.LDL_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.LUD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.LUD_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.MDD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.MI_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.MS_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.NAFLD_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.PAR_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.PAR_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.SCZ_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.T1D_adult_HFGA_A1)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.T1D_adult_HFGA_A1_top)
intestine_human_adult_HFGA_A1 <- rbind(intestine_human_adult_HFGA_A1,meta.data.T2D_adult_HFGA_A1)


#Add dataset name
intestine_human_adult_HFGA_A1$dataset <- "intestine_human_adult_HFGA_A1"

#Reorder
intestine_human_adult_HFGA_A1 <- intestine_human_adult_HFGA_A1[,c(11:9,1:8)]

```


# Kidney datasets

```{r}
##mouse_10X_coronal
meta.data.ADHD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_ADHD_all_genes.RDS")
meta.data.ADHD_mouse_10X_coronal$trait_gene_list <- "ADHD_all_genes"

meta.data.AHD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_mouse_10X_coronal$trait_gene_list <- "AHD_all_genes"

meta.data.AHD_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_AHD_top120_genes.RDS")
meta.data.AHD_mouse_10X_coronal_top$trait_gene_list <- "AHD_top120_genes"

meta.data.ALS_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_mouse_10X_coronal$trait_gene_list <- "ALS_all_genes"

meta.data.ALS_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_ALS_top90_genes.RDS")
meta.data.ALS_mouse_10X_coronal_top$trait_gene_list <- "ALS_top90_genes"

meta.data.ALZ_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_ALZ_all_genes.RDS")
meta.data.ALZ_mouse_10X_coronal$trait_gene_list <- "ALZ_all_genes"

meta.data.ALZ_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_ALZ_top60_genes.RDS")
meta.data.ALZ_mouse_10X_coronal_top$trait_gene_list <- "ALZ_top60_genes"

meta.data.ASD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_ASD_all_genes.RDS")
meta.data.ASD_mouse_10X_coronal$trait_gene_list <- "ASD_all_genes"

meta.data.AST_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_AST_all_genes.RDS")
meta.data.AST_mouse_10X_coronal$trait_gene_list <- "AST_all_genes"

meta.data.BIP_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_BIP_all_genes.RDS")
meta.data.BIP_mouse_10X_coronal$trait_gene_list <- "BIP_all_genes"

meta.data.BRD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_BRD_all_genes.RDS")
meta.data.BRD_mouse_10X_coronal$trait_gene_list <- "BRD_all_genes"

meta.data.CAD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_mouse_10X_coronal$trait_gene_list <- "CAD_all_genes"

meta.data.CAD_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_CAD_top90_genes.RDS")
meta.data.CAD_mouse_10X_coronal_top$trait_gene_list <- "CAD_top90_genes"

meta.data.CD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_CD_all_genes.RDS")
meta.data.CD_mouse_10X_coronal$trait_gene_list <- "CD_all_genes"

meta.data.CD_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_CD_top310_genes.RDS")
meta.data.CD_mouse_10X_coronal_top$trait_gene_list <- "CD_top310_genes"

meta.data.CHD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_CHD_all_genes.RDS")
meta.data.CHD_mouse_10X_coronal$trait_gene_list <- "CHD_all_genes"

meta.data.CHD_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_CHD_top50_genes.RDS")
meta.data.CHD_mouse_10X_coronal_top$trait_gene_list <- "CHD_top50_genes"

meta.data.CHOL_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_CHOL_all_genes.RDS")
meta.data.CHOL_mouse_10X_coronal$`median(score_drugs)` <- "N/A"
meta.data.CHOL_mouse_10X_coronal$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_mouse_10X_coronal$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_mouse_10X_coronal <- meta.data.CHOL_mouse_10X_coronal[,c(1:5,7:9,6)]
meta.data.CHOL_mouse_10X_coronal$trait_gene_list <- "CHOL_all_genes"

meta.data.CHOL_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_CHOL_top50_genes.RDS")
meta.data.CHOL_mouse_10X_coronal_top$`median(score_drugs)` <- "N/A"
meta.data.CHOL_mouse_10X_coronal_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_mouse_10X_coronal_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_mouse_10X_coronal_top <- meta.data.CHOL_mouse_10X_coronal_top[,c(1:5,7:9,6)]
meta.data.CHOL_mouse_10X_coronal_top$trait_gene_list <- "CHOL_top50_genes"

meta.data.CIRR_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_CIRR_all_genes.RDS")
meta.data.CIRR_mouse_10X_coronal$trait_gene_list <- "CIRR_all_genes"

meta.data.CIRR_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_CIRR_top50_genes.RDS")
meta.data.CIRR_mouse_10X_coronal_top$trait_gene_list <- "CIRR_top50_genes"

meta.data.COPD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_COPD_all_genes.RDS")
meta.data.COPD_mouse_10X_coronal$trait_gene_list <- "COPD_all_genes"

meta.data.EPI_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_EPI_all_genes.RDS")
meta.data.EPI_mouse_10X_coronal$trait_gene_list <- "EPI_all_genes"

meta.data.EPI_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_EPI_top190_genes.RDS")
meta.data.EPI_mouse_10X_coronal_top$trait_gene_list <- "EPI_top190_genes"

meta.data.IBD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_IBD_all_genes.RDS")
meta.data.IBD_mouse_10X_coronal$trait_gene_list <- "IBD_all_genes"

meta.data.INS_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_INS_all_genes.RDS")
meta.data.INS_mouse_10X_coronal$trait_gene_list <- "INS_all_genes"

meta.data.LD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_LD_all_genes.RDS")
meta.data.LD_mouse_10X_coronal$trait_gene_list <- "LD_all_genes"

meta.data.LD_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_LD_top70_genes.RDS")
meta.data.LD_mouse_10X_coronal_top$trait_gene_list <- "LD_top70_genes"

meta.data.LDL_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_mouse_10X_coronal$`median(score_drugs)` <- "N/A"
meta.data.LDL_mouse_10X_coronal$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_mouse_10X_coronal$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_mouse_10X_coronal <- meta.data.LDL_mouse_10X_coronal[,c(1:5,7:9,6)]
meta.data.LDL_mouse_10X_coronal$trait_gene_list <- "LDL_all_genes"

meta.data.LDL_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_LDL_top150_genes.RDS")
meta.data.LDL_mouse_10X_coronal_top$`median(score_drugs)` <- "N/A"
meta.data.LDL_mouse_10X_coronal_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_mouse_10X_coronal_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_mouse_10X_coronal_top <- meta.data.LDL_mouse_10X_coronal_top[,c(1:5,7:9,6)]
meta.data.LDL_mouse_10X_coronal_top$trait_gene_list <- "LDL_top150_genes"

meta.data.LID_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_LID_all_genes.RDS")
meta.data.LID_mouse_10X_coronal$trait_gene_list <- "LID_all_genes"

meta.data.LUD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_LUD_all_genes.RDS")
meta.data.LUD_mouse_10X_coronal$trait_gene_list <- "LUD_all_genes"

meta.data.LUD_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_LUD_top90_genes.RDS")
meta.data.LUD_mouse_10X_coronal_top$trait_gene_list <- "LUD_top90_genes"

meta.data.MDD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_MDD_all_genes.RDS")
meta.data.MDD_mouse_10X_coronal$trait_gene_list <- "MDD_all_genes"

meta.data.MI_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_mouse_10X_coronal$trait_gene_list <- "MI_all_genes"

meta.data.MI_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_MI_top50_genes.RDS")
meta.data.MI_mouse_10X_coronal_top$trait_gene_list <- "MI_top50_genes"

meta.data.MS_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_mouse_10X_coronal$trait_gene_list <- "MS_all_genes"

meta.data.MS_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_MS_top50_genes.RDS")
meta.data.MS_mouse_10X_coronal_top$trait_gene_list <- "MS_top50_genes"

meta.data.NAFLD_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_NAFLD_all_genes.RDS")
meta.data.NAFLD_mouse_10X_coronal$trait_gene_list <- "NAFLD_all_genes"

meta.data.NAFLD_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_NAFLD_top60_genes.RDS")
meta.data.NAFLD_mouse_10X_coronal_top$trait_gene_list <- "NAFLD_top60_genes"

meta.data.PAR_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_PAR_all_genes.RDS")
meta.data.PAR_mouse_10X_coronal$trait_gene_list <- "PAR_all_genes"

meta.data.PAR_mouse_10X_coronal_top <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_PAR_top100_genes.RDS")
meta.data.PAR_mouse_10X_coronal_top$trait_gene_list <- "PAR_top100_genes"

meta.data.SCZ_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_SCZ_all_genes.RDS")
meta.data.SCZ_mouse_10X_coronal$trait_gene_list <- "SCZ_all_genes"

meta.data.T1D_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_T1D_all_genes.RDS")
meta.data.T1D_mouse_10X_coronal$trait_gene_list <- "T1D_all_genes"

meta.data.T2D_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_T2D_all_genes.RDS")
meta.data.T2D_mouse_10X_coronal$trait_gene_list <- "T2D_all_genes"

meta.data.UC_mouse_10X_coronal <- readRDS(file = "Kidney/mouse_10X_coronal/p_value_distribution/pval.distribution_UC_all_genes.RDS")
meta.data.UC_mouse_10X_coronal$trait_gene_list <- "UC_all_genes"

#Merge
kidney_mouse_10X <- rbind(meta.data.ADHD_mouse_10X_coronal,meta.data.AHD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.AHD_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.ALS_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.ALS_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.ALZ_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.ALZ_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.ASD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.AST_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.BIP_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.BRD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.CAD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.CAD_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.CD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.CD_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.CHD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.CHD_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.CHOL_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.CHOL_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.CIRR_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.CIRR_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.COPD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.EPI_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.EPI_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.IBD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.INS_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.LD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.LD_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.LDL_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.LDL_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.LID_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.LUD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.LUD_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.MDD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.MI_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.MI_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.MS_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.MS_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.NAFLD_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.NAFLD_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.PAR_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.PAR_mouse_10X_coronal_top)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.SCZ_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.T1D_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.T2D_mouse_10X_coronal)
kidney_mouse_10X <- rbind(kidney_mouse_10X,meta.data.UC_mouse_10X_coronal)

#Add dataset name
kidney_mouse_10X$dataset <- "kidney_mouse_10X"

#Reorder
kidney_mouse_10X <- kidney_mouse_10X[,c(11:9,1:8)]

```


# Liver datasets

```{r}
##mouse_JBO002
meta.data.ADHD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_ADHD_all_genes.RDS")
meta.data.ADHD_mouse_JBO002$trait_gene_list <- "ADHD_all_genes"

meta.data.AHD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_mouse_JBO002$trait_gene_list <- "AHD_all_genes"

meta.data.AHD_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_AHD_top70_genes.RDS")
meta.data.AHD_mouse_JBO002_top$trait_gene_list <- "AHD_top70_genes"

meta.data.ALS_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_mouse_JBO002$trait_gene_list <- "ALS_all_genes"

meta.data.ALS_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_ALS_top50_genes.RDS")
meta.data.ALS_mouse_JBO002_top$trait_gene_list <- "ALS_top50_genes"

meta.data.ALZ_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_ALZ_all_genes.RDS")
meta.data.ALZ_mouse_JBO002$trait_gene_list <- "ALZ_all_genes"

meta.data.ALZ_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_ALZ_top70_genes.RDS")
meta.data.ALZ_mouse_JBO002_top$trait_gene_list <- "ALZ_top70_genes"

meta.data.ASD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_ASD_all_genes.RDS")
meta.data.ASD_mouse_JBO002$trait_gene_list <- "ASD_all_genes"

meta.data.AST_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_AST_all_genes.RDS")
meta.data.AST_mouse_JBO002$trait_gene_list <- "AST_all_genes"

meta.data.BIP_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_BIP_all_genes.RDS")
meta.data.BIP_mouse_JBO002$trait_gene_list <- "BIP_all_genes"

meta.data.BRD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_BRD_all_genes.RDS")
meta.data.BRD_mouse_JBO002$trait_gene_list <- "BRD_all_genes"

meta.data.CD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_CD_all_genes.RDS")
meta.data.CD_mouse_JBO002$trait_gene_list <- "CD_all_genes"

meta.data.CHD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_CHD_all_genes.RDS")
meta.data.CHD_mouse_JBO002$trait_gene_list <- "CHD_all_genes"

meta.data.CKD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_CKD_all_genes.RDS")
meta.data.CKD_mouse_JBO002$trait_gene_list <- "CKD_all_genes"

meta.data.CKD_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_CKD_top80_genes.RDS")
meta.data.CKD_mouse_JBO002_top$trait_gene_list <- "CKD_top80_genes"

meta.data.COPD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_COPD_all_genes.RDS")
meta.data.COPD_mouse_JBO002$trait_gene_list <- "COPD_all_genes"

meta.data.COPD_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_COPD_top50_genes.RDS")
meta.data.COPD_mouse_JBO002_top$trait_gene_list <- "COPD_top50_genes"

meta.data.EPI_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_EPI_all_genes.RDS")
meta.data.EPI_mouse_JBO002$trait_gene_list <- "EPI_all_genes"

meta.data.EPI_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_EPI_top190_genes.RDS")
meta.data.EPI_mouse_JBO002_top$trait_gene_list <- "EPI_top190_genes"

meta.data.IBD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_IBD_all_genes.RDS")
meta.data.IBD_mouse_JBO002$trait_gene_list <- "IBD_all_genes"

meta.data.IKD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_IKD_all_genes.RDS")
meta.data.IKD_mouse_JBO002$trait_gene_list <- "IKD_all_genes"

meta.data.IKD_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_IKD_top130_genes.RDS")
meta.data.IKD_mouse_JBO002_top$trait_gene_list <- "IKD_top130_genes"

meta.data.INS_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_INS_all_genes.RDS")
meta.data.INS_mouse_JBO002$trait_gene_list <- "INS_all_genes"

meta.data.LID_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_LID_all_genes.RDS")
meta.data.LID_mouse_JBO002$trait_gene_list <- "LID_all_genes"

meta.data.LUD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_LUD_all_genes.RDS")
meta.data.LUD_mouse_JBO002$trait_gene_list <- "LUD_all_genes"

meta.data.MDD_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_MDD_all_genes.RDS")
meta.data.MDD_mouse_JBO002$trait_gene_list <- "MDD_all_genes"

meta.data.MS_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_mouse_JBO002$trait_gene_list <- "MS_all_genes"

meta.data.PAR_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_PAR_all_genes.RDS")
meta.data.PAR_mouse_JBO002$trait_gene_list <- "PAR_all_genes"

meta.data.PAR_mouse_JBO002_top <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_PAR_top80_genes.RDS")
meta.data.PAR_mouse_JBO002_top$trait_gene_list <- "PAR_top80_genes"

meta.data.SCZ_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_SCZ_all_genes.RDS")
meta.data.SCZ_mouse_JBO002$trait_gene_list <- "SCZ_all_genes"

meta.data.T1D_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_T1D_all_genes.RDS")
meta.data.T1D_mouse_JBO002$trait_gene_list <- "T1D_all_genes"

meta.data.T2D_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_T2D_all_genes.RDS")
meta.data.T2D_mouse_JBO002$trait_gene_list <- "T2D_all_genes"

meta.data.UC_mouse_JBO002 <- readRDS(file = "Liver/mouse_JBO002/p_value_distribution/pval.distribution_UC_all_genes.RDS")
meta.data.UC_mouse_JBO002$trait_gene_list <- "UC_all_genes"

#Merge
liver_mouse_JBO002 <- rbind(meta.data.ADHD_mouse_JBO002,meta.data.AHD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.AHD_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.ALS_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.ALS_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.ALZ_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.ALZ_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.ASD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.AST_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.BIP_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.BRD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.CD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.CHD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.CKD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.CKD_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.COPD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.COPD_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.EPI_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.EPI_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.IBD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.IKD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.IKD_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.INS_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.LID_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.LUD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.MDD_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.MS_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.PAR_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.PAR_mouse_JBO002_top)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.SCZ_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.T1D_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.T2D_mouse_JBO002)
liver_mouse_JBO002 <- rbind(liver_mouse_JBO002,meta.data.UC_mouse_JBO002)

#Add dataset name
liver_mouse_JBO002$dataset <- "liver_mouse_JBO002"

#Reorder
liver_mouse_JBO002 <- liver_mouse_JBO002[,c(11:9,1:8)]

```


# Lung datasets

```{r}
##HLA_Bronchi_A50_467
meta.data.ADHD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_ADHD_all_genes.RDS")
meta.data.ADHD_HLA_Bronchi_A50_467$trait_gene_list <- "ADHD_all_genes"

meta.data.AHD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_HLA_Bronchi_A50_467$trait_gene_list <- "AHD_all_genes"

meta.data.ALS_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_HLA_Bronchi_A50_467$trait_gene_list <- "ALS_all_genes"

meta.data.ALZ_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_ALZ_all_genes.RDS")
meta.data.ALZ_HLA_Bronchi_A50_467$trait_gene_list <- "ALZ_all_genes"

meta.data.ALZ_HLA_Bronchi_A50_467_top <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_ALZ_top50_genes.RDS")
meta.data.ALZ_HLA_Bronchi_A50_467_top$trait_gene_list <- "ALZ_top50_genes"

meta.data.ASD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_ASD_all_genes.RDS")
meta.data.ASD_HLA_Bronchi_A50_467$trait_gene_list <- "ASD_all_genes"

meta.data.BIP_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_BIP_all_genes.RDS")
meta.data.BIP_HLA_Bronchi_A50_467$trait_gene_list <- "BIP_all_genes"

meta.data.CAD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_HLA_Bronchi_A50_467$trait_gene_list <- "CAD_all_genes"

meta.data.CD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_CD_all_genes.RDS")
meta.data.CD_HLA_Bronchi_A50_467$trait_gene_list <- "CD_all_genes"

meta.data.CHD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_CHD_all_genes.RDS")
meta.data.CHD_HLA_Bronchi_A50_467$trait_gene_list <- "CHD_all_genes"

meta.data.CHOL_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_CHOL_all_genes.RDS")
meta.data.CHOL_HLA_Bronchi_A50_467$`median(score_drugs)` <- "N/A"
meta.data.CHOL_HLA_Bronchi_A50_467$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_HLA_Bronchi_A50_467$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_HLA_Bronchi_A50_467 <- meta.data.CHOL_HLA_Bronchi_A50_467[,c(1:5,7:9,6)]
meta.data.CHOL_HLA_Bronchi_A50_467$trait_gene_list <- "CHOL_all_genes"

meta.data.CIRR_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_CIRR_all_genes.RDS")
meta.data.CIRR_HLA_Bronchi_A50_467$trait_gene_list <- "CIRR_all_genes"

meta.data.CKD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_CKD_all_genes.RDS")
meta.data.CKD_HLA_Bronchi_A50_467$trait_gene_list <- "CKD_all_genes"

meta.data.EPI_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_EPI_all_genes.RDS")
meta.data.EPI_HLA_Bronchi_A50_467$trait_gene_list <- "EPI_all_genes"

meta.data.EPI_HLA_Bronchi_A50_467_top <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_EPI_top120_genes.RDS")
meta.data.EPI_HLA_Bronchi_A50_467_top$trait_gene_list <- "EPI_top120_genes"

meta.data.IBD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_IBD_all_genes.RDS")
meta.data.IBD_HLA_Bronchi_A50_467$trait_gene_list <- "IBD_all_genes"

meta.data.IKD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_IKD_all_genes.RDS")
meta.data.IKD_HLA_Bronchi_A50_467$trait_gene_list <- "IKD_all_genes"

meta.data.IKD_HLA_Bronchi_A50_467_top <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_IKD_top100_genes.RDS")
meta.data.IKD_HLA_Bronchi_A50_467_top$trait_gene_list <- "IKD_top100_genes"

meta.data.INS_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_INS_all_genes.RDS")
meta.data.INS_HLA_Bronchi_A50_467$trait_gene_list <- "INS_all_genes"

meta.data.LD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_LD_all_genes.RDS")
meta.data.LD_HLA_Bronchi_A50_467$trait_gene_list <- "LD_all_genes"

meta.data.LD_HLA_Bronchi_A50_467_top <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_LD_top70_genes.RDS")
meta.data.LD_HLA_Bronchi_A50_467_top$trait_gene_list <- "LD_top70_genes"

meta.data.LDL_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_HLA_Bronchi_A50_467$`median(score_drugs)` <- "N/A"
meta.data.LDL_HLA_Bronchi_A50_467$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_HLA_Bronchi_A50_467$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_HLA_Bronchi_A50_467 <- meta.data.LDL_HLA_Bronchi_A50_467[,c(1:5,7:9,6)]
meta.data.LDL_HLA_Bronchi_A50_467$trait_gene_list <- "LDL_all_genes"

meta.data.LDL_HLA_Bronchi_A50_467_top <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_LDL_top70_genes.RDS")
meta.data.LDL_HLA_Bronchi_A50_467_top$`median(score_drugs)` <- "N/A"
meta.data.LDL_HLA_Bronchi_A50_467_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_HLA_Bronchi_A50_467_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_HLA_Bronchi_A50_467_top <- meta.data.LDL_HLA_Bronchi_A50_467_top[,c(1:5,7:9,6)]
meta.data.LDL_HLA_Bronchi_A50_467_top$trait_gene_list <- "LDL_top70_genes"

meta.data.LID_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_LID_all_genes.RDS")
meta.data.LID_HLA_Bronchi_A50_467$trait_gene_list <- "LID_all_genes"

meta.data.LID_HLA_Bronchi_A50_467_top <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_LID_top110_genes.RDS")
meta.data.LID_HLA_Bronchi_A50_467_top$trait_gene_list <- "LID_top110_genes"

meta.data.MDD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_MDD_all_genes.RDS")
meta.data.MDD_HLA_Bronchi_A50_467$trait_gene_list <- "MDD_all_genes"

meta.data.MI_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_HLA_Bronchi_A50_467$trait_gene_list <- "MI_all_genes"

meta.data.MI_HLA_Bronchi_A50_467_top <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_MI_top50_genes.RDS")
meta.data.MI_HLA_Bronchi_A50_467_top$trait_gene_list <- "MI_top50_genes"

meta.data.MS_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_HLA_Bronchi_A50_467$trait_gene_list <- "MS_all_genes"

meta.data.NAFLD_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_NAFLD_all_genes.RDS")
meta.data.NAFLD_HLA_Bronchi_A50_467$trait_gene_list <- "NAFLD_all_genes"

meta.data.PAR_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_PAR_all_genes.RDS")
meta.data.PAR_HLA_Bronchi_A50_467$trait_gene_list <- "PAR_all_genes"

meta.data.PAR_HLA_Bronchi_A50_467_top <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_PAR_top80_genes.RDS")
meta.data.PAR_HLA_Bronchi_A50_467_top$trait_gene_list <- "PAR_top80_genes"

meta.data.SCZ_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_SCZ_all_genes.RDS")
meta.data.SCZ_HLA_Bronchi_A50_467$trait_gene_list <- "SCZ_all_genes"

meta.data.T1D_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_T1D_all_genes.RDS")
meta.data.T1D_HLA_Bronchi_A50_467$trait_gene_list <- "T1D_all_genes"

meta.data.T2D_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_T2D_all_genes.RDS")
meta.data.T2D_HLA_Bronchi_A50_467$trait_gene_list <- "T2D_all_genes"

meta.data.UC_HLA_Bronchi_A50_467 <- readRDS(file = "Lung/HLA_Bronchi_A50_467/p_value_distribution/pval.distribution_UC_all_genes.RDS")
meta.data.UC_HLA_Bronchi_A50_467$trait_gene_list <- "UC_all_genes"

#Merge
lung_bronchi_human_A50 <- rbind(meta.data.ADHD_HLA_Bronchi_A50_467,meta.data.AHD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.ALS_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.ALZ_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.ALZ_HLA_Bronchi_A50_467_top)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.ASD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.BIP_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.CAD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.CD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.CHD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.CHOL_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.CIRR_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.CKD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.EPI_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.EPI_HLA_Bronchi_A50_467_top)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.IBD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.IKD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.IKD_HLA_Bronchi_A50_467_top)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.INS_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.LD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.LD_HLA_Bronchi_A50_467_top)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.LDL_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.LDL_HLA_Bronchi_A50_467_top)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.LID_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.LID_HLA_Bronchi_A50_467_top)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.MDD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.MI_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.MI_HLA_Bronchi_A50_467_top)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.MS_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.NAFLD_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.PAR_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.PAR_HLA_Bronchi_A50_467_top)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.SCZ_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.T1D_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.T2D_HLA_Bronchi_A50_467)
lung_bronchi_human_A50 <- rbind(lung_bronchi_human_A50,meta.data.UC_HLA_Bronchi_A50_467)

#Add dataset name
lung_bronchi_human_A50$dataset <- "lung_bronchi_human_A50"

#Reorder
lung_bronchi_human_A50 <- lung_bronchi_human_A50[,c(11:9,1:8)]

```


# Pancreas datasets
```{r}
##pancreas_human_15PCW_S1
meta.data.ADHD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_ADHD_all_genes.RDS")
meta.data.ADHD_pancreas_human_15PCW_S1$trait_gene_list <- "ADHD_all_genes"

meta.data.AHD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_AHD_all_genes.RDS")
meta.data.AHD_pancreas_human_15PCW_S1$trait_gene_list <- "AHD_all_genes"

meta.data.AHD_pancreas_human_15PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_AHD_top60_genes.RDS")
meta.data.AHD_pancreas_human_15PCW_S1_top$trait_gene_list <- "AHD_top60_genes"

meta.data.ALS_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_ALS_all_genes.RDS")
meta.data.ALS_pancreas_human_15PCW_S1$trait_gene_list <- "ALS_all_genes"

meta.data.ALS_pancreas_human_15PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_ALS_top60_genes.RDS")
meta.data.ALS_pancreas_human_15PCW_S1_top$trait_gene_list <- "ALS_top60_genes"

meta.data.ALZ_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_ALZ_all_genes.RDS")
meta.data.ALZ_pancreas_human_15PCW_S1$trait_gene_list <- "ALZ_all_genes"

meta.data.ASD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_ASD_all_genes.RDS")
meta.data.ASD_pancreas_human_15PCW_S1$trait_gene_list <- "ASD_all_genes"

meta.data.AST_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_AST_all_genes.RDS")
meta.data.AST_pancreas_human_15PCW_S1$trait_gene_list <- "AST_all_genes"

meta.data.BIP_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_BIP_all_genes.RDS")
meta.data.BIP_pancreas_human_15PCW_S1$trait_gene_list <- "BIP_all_genes"

meta.data.BRD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_BRD_all_genes.RDS")
meta.data.BRD_pancreas_human_15PCW_S1$trait_gene_list <- "BRD_all_genes"

meta.data.CAD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_pancreas_human_15PCW_S1$trait_gene_list <- "CAD_all_genes"

meta.data.CAD_pancreas_human_15PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_CAD_top50_genes.RDS")
meta.data.CAD_pancreas_human_15PCW_S1_top$trait_gene_list <- "CAD_top50_genes"

meta.data.CD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_CD_all_genes.RDS")
meta.data.CD_pancreas_human_15PCW_S1$trait_gene_list <- "CD_all_genes"

meta.data.CHD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_CHD_all_genes.RDS")
meta.data.CHD_pancreas_human_15PCW_S1$trait_gene_list <- "CHD_all_genes"

meta.data.CHD_pancreas_human_15PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_CHD_top50_genes.RDS")
meta.data.CHD_pancreas_human_15PCW_S1_top$trait_gene_list <- "CHD_top50_genes"

meta.data.CHOL_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_CHOL_all_genes.RDS")
meta.data.CHOL_pancreas_human_15PCW_S1$`median(score_drugs)` <- "N/A"
meta.data.CHOL_pancreas_human_15PCW_S1$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_pancreas_human_15PCW_S1$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_pancreas_human_15PCW_S1 <- meta.data.CHOL_pancreas_human_15PCW_S1[,c(1:5,7:9,6)]
meta.data.CHOL_pancreas_human_15PCW_S1$trait_gene_list <- "CHOL_all_genes"

meta.data.CHOL_pancreas_human_15PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_CHOL_top70_genes.RDS")
meta.data.CHOL_pancreas_human_15PCW_S1_top$`median(score_drugs)` <- "N/A"
meta.data.CHOL_pancreas_human_15PCW_S1_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_pancreas_human_15PCW_S1_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_pancreas_human_15PCW_S1_top <- meta.data.CHOL_pancreas_human_15PCW_S1_top[,c(1:5,7:9,6)]
meta.data.CHOL_pancreas_human_15PCW_S1_top$trait_gene_list <- "CHOL_top70_genes"

meta.data.CIRR_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_CIRR_all_genes.RDS")
meta.data.CIRR_pancreas_human_15PCW_S1$trait_gene_list <- "CIRR_all_genes"

meta.data.CKD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_CKD_all_genes.RDS")
meta.data.CKD_pancreas_human_15PCW_S1$trait_gene_list <- "CKD_all_genes"

meta.data.CKD_pancreas_human_15PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_CKD_top90_genes.RDS")
meta.data.CKD_pancreas_human_15PCW_S1_top$trait_gene_list <- "CKD_top90_genes"

meta.data.COPD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_COPD_all_genes.RDS")
meta.data.COPD_pancreas_human_15PCW_S1$trait_gene_list <- "COPD_all_genes"

meta.data.EPI_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_EPI_all_genes.RDS")
meta.data.EPI_pancreas_human_15PCW_S1$trait_gene_list <- "EPI_all_genes"

meta.data.EPI_pancreas_human_15PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_EPI_top210_genes.RDS")
meta.data.EPI_pancreas_human_15PCW_S1_top$trait_gene_list <- "EPI_top210_genes"

meta.data.IBD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_IBD_all_genes.RDS")
meta.data.IBD_pancreas_human_15PCW_S1$trait_gene_list <- "IBD_all_genes"

meta.data.IKD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_IKD_all_genes.RDS")
meta.data.IKD_pancreas_human_15PCW_S1$trait_gene_list <- "IKD_all_genes"

meta.data.IKD_pancreas_human_15PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_IKD_top90_genes.RDS")
meta.data.IKD_pancreas_human_15PCW_S1_top$trait_gene_list <- "IKD_top90_genes"

meta.data.INS_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_INS_all_genes.RDS")
meta.data.INS_pancreas_human_15PCW_S1$trait_gene_list <- "INS_all_genes"

meta.data.LD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_LD_all_genes.RDS")
meta.data.LD_pancreas_human_15PCW_S1$trait_gene_list <- "LD_all_genes"

meta.data.LDL_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_pancreas_human_15PCW_S1$`median(score_drugs)` <- "N/A"
meta.data.LDL_pancreas_human_15PCW_S1$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_pancreas_human_15PCW_S1$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_pancreas_human_15PCW_S1 <- meta.data.LDL_pancreas_human_15PCW_S1[,c(1:5,7:9,6)]
meta.data.LDL_pancreas_human_15PCW_S1$trait_gene_list <- "LDL_all_genes"

meta.data.LID_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_LID_all_genes.RDS")
meta.data.LID_pancreas_human_15PCW_S1$trait_gene_list <- "LID_all_genes"

meta.data.LUD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_LUD_all_genes.RDS")
meta.data.LUD_pancreas_human_15PCW_S1$trait_gene_list <- "LUD_all_genes"

meta.data.MDD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_MDD_all_genes.RDS")
meta.data.MDD_pancreas_human_15PCW_S1$trait_gene_list <- "MDD_all_genes"

meta.data.MI_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_pancreas_human_15PCW_S1$trait_gene_list <- "MI_all_genes"

meta.data.MS_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_MS_all_genes.RDS")
meta.data.MS_pancreas_human_15PCW_S1$trait_gene_list <- "MS_all_genes"

meta.data.NAFLD_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_NAFLD_all_genes.RDS")
meta.data.NAFLD_pancreas_human_15PCW_S1$trait_gene_list <- "NAFLD_all_genes"

meta.data.PAR_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_PAR_all_genes.RDS")
meta.data.PAR_pancreas_human_15PCW_S1$trait_gene_list <- "PAR_all_genes"

meta.data.PAR_pancreas_human_15PCW_S1_top <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_PAR_top90_genes.RDS")
meta.data.PAR_pancreas_human_15PCW_S1_top$trait_gene_list <- "PAR_top90_genes"

meta.data.SCZ_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_SCZ_all_genes.RDS")
meta.data.SCZ_pancreas_human_15PCW_S1$trait_gene_list <- "SCZ_all_genes"

meta.data.UC_pancreas_human_15PCW_S1 <- readRDS(file = "Pancreas/pancreas_human_15PCW_S1/p_value_distribution/pval.distribution_UC_all_genes.RDS")
meta.data.UC_pancreas_human_15PCW_S1$trait_gene_list <- "UC_all_genes"

#Merge
pancreas_human_15PCW_S1 <- rbind(meta.data.ADHD_pancreas_human_15PCW_S1,meta.data.AHD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.AHD_pancreas_human_15PCW_S1_top)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.ALS_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.ALS_pancreas_human_15PCW_S1_top)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.ALZ_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.ASD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.AST_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.BIP_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.BRD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.CAD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.CAD_pancreas_human_15PCW_S1_top)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.CD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.CHD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.CHD_pancreas_human_15PCW_S1_top)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.CHOL_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.CHOL_pancreas_human_15PCW_S1_top)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.CIRR_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.CKD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.CKD_pancreas_human_15PCW_S1_top)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.COPD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.EPI_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.EPI_pancreas_human_15PCW_S1_top)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.IBD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.IKD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.IKD_pancreas_human_15PCW_S1_top)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.INS_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.LD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.LDL_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.LID_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.LUD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.MDD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.MI_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.MS_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.NAFLD_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.PAR_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.PAR_pancreas_human_15PCW_S1_top)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.SCZ_pancreas_human_15PCW_S1)
pancreas_human_15PCW_S1 <- rbind(pancreas_human_15PCW_S1,meta.data.UC_pancreas_human_15PCW_S1)

#Add dataset name
pancreas_human_15PCW_S1$dataset <- "pancreas_human_15PCW_S1"

#Reorder
pancreas_human_15PCW_S1 <- pancreas_human_15PCW_S1[,c(11:9,1:8)]

```


# Spinal cord datasets

```{r}
##w8_V10F24_107B1
meta.data.ADHD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_ADHD_all_genes.RDS")
meta.data.ADHD_w8_V10F24_107B1$trait_gene_list <- "ADHD_all_genes"

meta.data.ADHD_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_ADHD_top100_genes.RDS")
meta.data.ADHD_w8_V10F24_107B1_top$trait_gene_list <- "ADHD_top100_genes"

meta.data.ALZ_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_ALZ_all_genes.RDS")
meta.data.ALZ_w8_V10F24_107B1$trait_gene_list <- "ALZ_all_genes"

meta.data.ASD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_ASD_all_genes.RDS")
meta.data.ASD_w8_V10F24_107B1$trait_gene_list <- "ASD_all_genes"

meta.data.ASD_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_ASD_top70_genes.RDS")
meta.data.ASD_w8_V10F24_107B1_top$trait_gene_list <- "ASD_top70_genes"

meta.data.AST_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_AST_all_genes.RDS")
meta.data.AST_w8_V10F24_107B1$trait_gene_list <- "AST_all_genes"

meta.data.BIP_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_BIP_all_genes.RDS")
meta.data.BIP_w8_V10F24_107B1$trait_gene_list <- "BIP_all_genes"

meta.data.BRD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_BRD_all_genes.RDS")
meta.data.BRD_w8_V10F24_107B1$trait_gene_list <- "BRD_all_genes"

meta.data.CAD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_CAD_all_genes.RDS")
meta.data.CAD_w8_V10F24_107B1$trait_gene_list <- "CAD_all_genes"

meta.data.CD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_CD_all_genes.RDS")
meta.data.CD_w8_V10F24_107B1$trait_gene_list <- "CD_all_genes"

meta.data.CHD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_CHD_all_genes.RDS")
meta.data.CHD_w8_V10F24_107B1$trait_gene_list <- "CHD_all_genes"

meta.data.CHD_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_CHD_top70_genes.RDS")
meta.data.CHD_w8_V10F24_107B1_top$trait_gene_list <- "CHD_top70_genes"

meta.data.CHOL_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_CHOL_all_genes.RDS")
meta.data.CHOL_w8_V10F24_107B1$`median(score_drugs)` <- "N/A"
meta.data.CHOL_w8_V10F24_107B1$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_w8_V10F24_107B1$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_w8_V10F24_107B1 <- meta.data.CHOL_w8_V10F24_107B1[,c(1:5,7:9,6)]
meta.data.CHOL_w8_V10F24_107B1$trait_gene_list <- "CHOL_all_genes"

meta.data.CHOL_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_CHOL_top280_genes.RDS")
meta.data.CHOL_w8_V10F24_107B1_top$`median(score_drugs)` <- "N/A"
meta.data.CHOL_w8_V10F24_107B1_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.CHOL_w8_V10F24_107B1_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.CHOL_w8_V10F24_107B1_top <- meta.data.CHOL_w8_V10F24_107B1_top[,c(1:5,7:9,6)]
meta.data.CHOL_w8_V10F24_107B1_top$trait_gene_list <- "CHOL_top280_genes"

meta.data.CIRR_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_CIRR_all_genes.RDS")
meta.data.CIRR_w8_V10F24_107B1$trait_gene_list <- "CIRR_all_genes"

meta.data.CKD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_CKD_all_genes.RDS")
meta.data.CKD_w8_V10F24_107B1$trait_gene_list <- "CKD_all_genes"

meta.data.COPD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_COPD_all_genes.RDS")
meta.data.COPD_w8_V10F24_107B1$trait_gene_list <- "COPD_all_genes"

meta.data.COPD_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_COPD_top140_genes.RDS")
meta.data.COPD_w8_V10F24_107B1_top$trait_gene_list <- "COPD_top140_genes"

meta.data.EPI_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_EPI_all_genes.RDS")
meta.data.EPI_w8_V10F24_107B1$trait_gene_list <- "EPI_all_genes"

meta.data.EPI_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_EPI_top210_genes.RDS")
meta.data.EPI_w8_V10F24_107B1_top$trait_gene_list <- "EPI_top210_genes"

meta.data.IBD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_IBD_all_genes.RDS")
meta.data.IBD_w8_V10F24_107B1$trait_gene_list <- "IBD_all_genes"

meta.data.IBD_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_IBD_top250_genes.RDS")
meta.data.IBD_w8_V10F24_107B1_top$trait_gene_list <- "IBD_top250_genes"

meta.data.IKD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_IKD_all_genes.RDS")
meta.data.IKD_w8_V10F24_107B1$trait_gene_list <- "IKD_all_genes"

meta.data.IKD_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_IKD_top270_genes.RDS")
meta.data.IKD_w8_V10F24_107B1_top$trait_gene_list <- "IKD_top270_genes"

meta.data.INS_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_INS_all_genes.RDS")
meta.data.INS_w8_V10F24_107B1$trait_gene_list <- "INS_all_genes"

meta.data.LD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_LD_all_genes.RDS")
meta.data.LD_w8_V10F24_107B1$trait_gene_list <- "LD_all_genes"

meta.data.LD_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_LD_top190_genes.RDS")
meta.data.LD_w8_V10F24_107B1_top$trait_gene_list <- "LD_top190_genes"

meta.data.LDL_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_LDL_all_genes.RDS")
meta.data.LDL_w8_V10F24_107B1$`median(score_drugs)` <- "N/A"
meta.data.LDL_w8_V10F24_107B1$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_w8_V10F24_107B1$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_w8_V10F24_107B1 <- meta.data.LDL_w8_V10F24_107B1[,c(1:5,7:9,6)]
meta.data.LDL_w8_V10F24_107B1$trait_gene_list <- "LDL_all_genes"

meta.data.LDL_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_LDL_top190_genes.RDS")
meta.data.LDL_w8_V10F24_107B1_top$`median(score_drugs)` <- "N/A"
meta.data.LDL_w8_V10F24_107B1_top$`-log10(p.val_drugs)` <- "N/A"
meta.data.LDL_w8_V10F24_107B1_top$`-log10(p.val.adj_drugs)` <- "N/A"
meta.data.LDL_w8_V10F24_107B1_top <- meta.data.LDL_w8_V10F24_107B1_top[,c(1:5,7:9,6)]
meta.data.LDL_w8_V10F24_107B1_top$trait_gene_list <- "LDL_top190_genes"

meta.data.LID_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_LID_all_genes.RDS")
meta.data.LID_w8_V10F24_107B1$trait_gene_list <- "LID_all_genes"

meta.data.LID_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_LID_top140_genes.RDS")
meta.data.LID_w8_V10F24_107B1_top$trait_gene_list <- "LID_top140_genes"

meta.data.LUD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_LUD_all_genes.RDS")
meta.data.LUD_w8_V10F24_107B1$trait_gene_list <- "LUD_all_genes"

meta.data.LUD_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_LUD_top230_genes.RDS")
meta.data.LUD_w8_V10F24_107B1_top$trait_gene_list <- "LUD_top230_genes"

meta.data.MDD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_MDD_all_genes.RDS")
meta.data.MDD_w8_V10F24_107B1$trait_gene_list <- "MDD_all_genes"

meta.data.MI_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_MI_all_genes.RDS")
meta.data.MI_w8_V10F24_107B1$trait_gene_list <- "MI_all_genes"

meta.data.MI_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_MI_top100_genes.RDS")
meta.data.MI_w8_V10F24_107B1_top$trait_gene_list <- "MI_top100_genes"

meta.data.NAFLD_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_NAFLD_all_genes.RDS")
meta.data.NAFLD_w8_V10F24_107B1$trait_gene_list <- "NAFLD_all_genes"

meta.data.PAR_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_PAR_all_genes.RDS")
meta.data.PAR_w8_V10F24_107B1$trait_gene_list <- "PAR_all_genes"

meta.data.PAR_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_PAR_top100_genes.RDS")
meta.data.PAR_w8_V10F24_107B1_top$trait_gene_list <- "PAR_top100_genes"

meta.data.SCZ_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_SCZ_all_genes.RDS")
meta.data.SCZ_w8_V10F24_107B1$trait_gene_list <- "SCZ_all_genes"

meta.data.SCZ_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_SCZ_top110_genes.RDS")
meta.data.SCZ_w8_V10F24_107B1_top$trait_gene_list <- "SCZ_top110_genes"

meta.data.T1D_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_T1D_all_genes.RDS")
meta.data.T1D_w8_V10F24_107B1$trait_gene_list <- "T1D_all_genes"

meta.data.T2D_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_T2D_all_genes.RDS")
meta.data.T2D_w8_V10F24_107B1$trait_gene_list <- "T2D_all_genes"

meta.data.UC_w8_V10F24_107B1 <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_UC_all_genes.RDS")
meta.data.UC_w8_V10F24_107B1$trait_gene_list <- "UC_all_genes"

meta.data.UC_w8_V10F24_107B1_top <- readRDS(file = "Spinal_cord/w8_V10F24_107B1/p_value_distribution/pval.distribution_UC_top170_genes.RDS")
meta.data.UC_w8_V10F24_107B1_top$trait_gene_list <- "UC_top170_genes"


#Merge
spinal_cord_human_pcw8_107B1 <- rbind(meta.data.ADHD_w8_V10F24_107B1,meta.data.ADHD_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.ALZ_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.ASD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.ASD_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.AST_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.BIP_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.BRD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.CAD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.CD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.CHD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.CHD_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.CHOL_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.CHOL_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.CIRR_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.CKD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.COPD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.COPD_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.EPI_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.EPI_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.IBD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.IBD_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.IKD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.IKD_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.INS_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.LD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.LD_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.LDL_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.LDL_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.LID_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.LID_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.LUD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.LUD_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.MDD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.MI_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.MI_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.NAFLD_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.PAR_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.PAR_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.SCZ_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.SCZ_w8_V10F24_107B1_top)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.T1D_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.T2D_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.UC_w8_V10F24_107B1)
spinal_cord_human_pcw8_107B1 <- rbind(spinal_cord_human_pcw8_107B1,meta.data.UC_w8_V10F24_107B1_top)

#Add dataset name
spinal_cord_human_pcw8_107B1$dataset <- "spinal_cord_human_pcw8_107B1"

#Reorder
spinal_cord_human_pcw8_107B1 <- spinal_cord_human_pcw8_107B1[,c(11:9,1:8)]

```

#Save
```{r}
#Merge all
pval_data <- rbind(brain_mouse_10X,heart_human_adult_ACH003)
pval_data <- rbind(pval_data,intestine_human_adult_HFGA_A1)
pval_data <- rbind(pval_data,kidney_mouse_10X)
pval_data <- rbind(pval_data,liver_mouse_JBO002)
pval_data <- rbind(pval_data,lung_bronchi_human_A50)
pval_data <- rbind(pval_data,pancreas_human_15PCW_S1)
pval_data <- rbind(pval_data,spinal_cord_human_pcw8_107B1)
```


```{r}
names(pval_data)

colnames(pval_data) <-c("dataset","trait_gene_list","cluster","median.genes","median.umi","median.score_genetic","neg.log10.p.val_genetic","neg.log10.p.val.adj_genetic","median.score_drugs","neg.log10.p.val_drugs","neg.log10.p.val.adj_drugs")

names(pval_data)
```


p-values all genes
```{r}
pval_data_all <- pval_data[!grepl("top", pval_data$trait_gene_list), ]
```

p-values top genes
```{r}
pval_data_top <- pval_data[grepl("top", pval_data$trait_gene_list), ]

pval_data_top$median.score_drugs <- "N/A"
pval_data_top$neg.log10.p.val_drugs <- "N/A"
pval_data_top$neg.log10.p.val.adj_drugs <- "N/A"
```

Merge
```{r}
pval_data <- rbind(pval_data_all,pval_data_top)
```

Separate
```{r}
pval_data <- separate(pval_data, trait_gene_list, into = c("trait", "gene_list"), sep = "_", extra = "merge")
```


```{r}
write.table(pval_data,file="pval_distribution_[all_datasets]_summary_non_selected_tissue_trait_pairs.csv",row.names = F,sep = ";")
```


# Notes
```{r}
sessionInfo()
```

