---
title: "Step4.Calculate_DEGs"
author: "Linda Kvastad"
output: html_document
date: '`r format(Sys.Date(), "%B %d, %Y")`'
---

Load libraries
```{r}
library(Seurat)
library(SeuratObject)
library(dplyr)
```


Load SC se object:
```{r}
se <- readRDS("Seurat_objects/Metacell_normalized.rds")
se
table(se$subclass_label)
```


Collect QC metrics
```{r}
se[["percent.mt"]] <- PercentageFeatureSet(se, pattern = "^mt-")
se[["percent.rb"]] <- PercentageFeatureSet(se, pattern = "^Rpl|^Rps")
```


Plot QC metrics
```{r, fig.width=10, fig.height=20}
VlnPlot(se, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rb"), ncol = 1, group.by = "subclass_label")
```


```{r, fig.width=10, fig.height=20}
RidgePlot(se, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rb"), ncol = 1, group.by = "subclass_label")
```


DE analysis, for all clusters
```{r}
se
DefaultAssay(se) <- "RNA"
se

#se <- JoinLayers(se)
#se

se <- se %>%
  NormalizeData() %>%
  ScaleData() 

se <- SetIdent(se, value = "subclass_label")
N.markers <- FindAllMarkers(se, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25,slot = "data")
```


Save N.markers
```{r, eval=T}
write.table(N.markers,file="DEG_output/DE_genes.csv", col.names = T, row.names = F,quote = FALSE,sep = ";")
```


Select top N genes to plot
```{r}
N <- 10

topN <- N.markers %>% 
            group_by(cluster) %>% 
            arrange(cluster,p_val_adj) %>%
            slice_head(n=N)
topN
```


Plot heat map of top N genes in each cluster:
```{r, fig.height=40, fig.width=20}
DoHeatmap(se, features = topN$gene)
```



PDF
```{r, eval=T}
pdf(file = "DEG_output/DEG_Heatmap_top10.pdf", height = 40, width = 20)

DoHeatmap(se, features = topN$gene)

dev.off()
```


SessionInfo
```{r}
sessionInfo()
```

