---
title: "Expressed_genes_plots_[10X_Visium_mouse_brain_coronal]"
author: "Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
 html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

NOTE: Plots Figure 4c.

# Load and Normalize data

Load libraries:
```{r, message=FALSE}
library(STutility)
```

Load ST data:
```{r}

infoTable <- read.csv("spatial_data/infoTable.csv", sep = ";")


se <- InputFromTable(infotable = infoTable, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

```


Load image:
```{r}
se <- LoadImages(se, time.resolve = FALSE)
```

View image:
```{r, fig.width=5, fig.height=4}
ImagePlot(se, method = "raster", annotate = F)
```

# Expressed genes plots  {.tabset}

Normalize data: se <- SCTransform(se,return.only.var.genes = T)
```{r, message=FALSE, include=FALSE}
se <- SCTransform(se,return.only.var.genes = T)
```

## Tcf7l2
```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "Tcf7l2", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)
```

## Bin1
```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "Bin1", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)
```

## Lonrf1
```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "Lonrf1", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)
```

## Tnrc6b
```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "Tnrc6b", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)
```

## Pde1a
```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "Pde1a", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)
```

## Stx1a
```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "Stx1a", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)
```

# Notes
Session info
```{r}
sessionInfo()
```

