---
title: "pval_correlation_steam_gsMap"
author: "Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
---

```{r}
library(ComplexHeatmap)
library(circlize)
```



```{r}
merged_results <- read.csv2(file = "merged_results_mouse_brain_[10X].csv")
```


```{r}
merged_results_all_genes <- subset(
  merged_results,
  apply(merged_results, 1, function(row) any(grepl("all_genes", row)))
)

```

Remove clusters missing in gsMap for this analysis.
```{r}
merged_results_all_genes <- merged_results_all_genes[1:17,]
```


```{r}
plot(merged_results_all_genes$ALZ.steam_pval,merged_results_all_genes$ALZ.gsMap_pval)
plot(merged_results_all_genes$ADHD.steam_pval,merged_results_all_genes$ADHD.gsMap_pval)
plot(merged_results_all_genes$ASD.steam_pval,merged_results_all_genes$ASD.gsMap_pval)
plot(merged_results_all_genes$BIP.steam_pval,merged_results_all_genes$BIP.gsMap_pval)
plot(merged_results_all_genes$SCZ.steam_pval,merged_results_all_genes$SCZ.gsMap_pval)
```


```{r}
cor(merged_results_all_genes$ALZ.steam_pval,merged_results_all_genes$ALZ.gsMap_pval, method = "spearman")
cor(merged_results_all_genes$ADHD.steam_pval,merged_results_all_genes$ADHD.gsMap_pval, method = "spearman")
cor(merged_results_all_genes$ASD.steam_pval,merged_results_all_genes$ASD.gsMap_pval, method = "spearman")
cor(merged_results_all_genes$BIP.steam_pval,merged_results_all_genes$BIP.gsMap_pval, method = "spearman")
cor(merged_results_all_genes$SCZ.steam_pval,merged_results_all_genes$SCZ.gsMap_pval, method = "spearman")
```


```{r}
# Select only columns ending with '_pval'
pval_data <- merged_results_all_genes[, grep("_pval$", names(merged_results_all_genes))]
```


```{r}
corr_matrix <- cor(pval_data, method = "spearman")
```




```{r}
# ---- Define color palette for correlation values ----
col_fun <- colorRamp2(c(-1, 0, 1), c("blue", "white", "red"))

# ---- Create top annotation (STEAM vs gsMap) ----
method_type <- ifelse(grepl("steam", colnames(corr_matrix), ignore.case = TRUE),
                      "STEAM", "gsMap")

ann_col <- HeatmapAnnotation(
  Method = method_type,
  col = list(Method = c(STEAM = "#1f78b4", gsMap = "#ff7f00"))
)

# ---- Build the heatmap ----
p <- Heatmap(
  corr_matrix,
  name = "Spearman",
  col = col_fun,
  top_annotation = ann_col,
  column_names_rot = 45,
  row_names_side = "left",
  cluster_rows = TRUE,
  cluster_columns = TRUE,
  column_title = "Correlation Heatmap of Nominal p-values",
  row_title = "Methods × Disorders",
  heatmap_legend_param = list(
    title_position = "topleft",   # title above color bar
    legend_direction = "vertical"   # keep color bar vertical
  )
)

# ---- Draw stacked legends vertically ----
draw(
  p,
  merge_legends = TRUE,             # combine heatmap + annotation legends
  heatmap_legend_side = "right",    # legend on the right
  annotation_legend_side = "right"  # annotation legend also on the right
)


```



PDF
```{r}
pdf(file = "plots/mouse_brain_[10X]_pval_cor.pdf", height = 5, width = 6)

draw(
  p,
  merge_legends = TRUE,             # combine heatmap + annotation legends
  heatmap_legend_side = "right",    # legend on the right
  annotation_legend_side = "right"  # annotation legend also on the right
)


dev.off()

```


Notes
```{r}
sessionInfo()
```

