---
title: "OpenTarget_gene_sets_all_traits"
output: html_document
author: "Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
---



Load libraries
```{r}
library(dplyr)
library(tidyverse)
library(reshape2)
```


Load genes lists
```{r}
ALZ_genes <- read.table(file = "Drug_repurposing_genetic_screen_output/Drug_repurposing_genetic_screen_mouse_brain_10X_ALZ_top70.csv", sep = ";",header = T)
ALZ_genes <- ALZ_genes$Potential_new_drug_targets

ADHD_genes <- read.table(file = "Drug_repurposing_genetic_screen_output/Drug_repurposing_genetic_screen_mouse_brain_10X_ADHD_top200.csv", sep = ";",header = T)
ADHD_genes <- ADHD_genes$Potential_new_drug_targets

ASD_genes <- read.table(file = "Drug_repurposing_genetic_screen_output/Drug_repurposing_genetic_screen_mouse_brain_10X_ASD_top130.csv", sep = ";",header = T)
ASD_genes <- ASD_genes$Potential_new_drug_targets

BIP_genes <- read.table(file = "Drug_repurposing_genetic_screen_output/Drug_repurposing_genetic_screen_mouse_brain_10X_BIP_top80.csv", sep = ";",header = T)
BIP_genes <- BIP_genes$Potential_new_drug_targets

SCZ_genes <- read.table(file = "Drug_repurposing_genetic_screen_output/Drug_repurposing_genetic_screen_mouse_brain_10X_SCZ_top140.csv", sep = ";",header = T)
SCZ_genes <- SCZ_genes$Potential_new_drug_targets

```

Combine lists
```{r}
all_gene_sets <- list(ALZ_genes=ALZ_genes, ADHD_genes=ADHD_genes, ASD_genes=ASD_genes, BIP_genes=BIP_genes, SCZ_genes=SCZ_genes)
```



Jaccard function:
```{r}
jaccard <- function(a, b) {
  intersection = length(intersect(a, b))
  union = length(a) + length(b) - intersection
  return (intersection/union)
}
```


Print all genes shared combinations:
```{r}
# två for-loopar
# Börja med att skapa en tom matrix med lika många kolumner som rader
# kolumn- och rad-namn ska vara samma som namnen på hallmark gene sets
length.mat <- matrix(data = NA, 
                  nrow = length(all_gene_sets), 
                  ncol = length(all_gene_sets), 
                  dimnames = list(names(all_gene_sets), 
                                  names(all_gene_sets)))


# Iterera över två for-loopar, en för rader och en för kolumner
for (i in 1:length(all_gene_sets)) {
  for (j in 1:length(all_gene_sets)) {
    # Spara jaccard mellan par av gene sets
    length.mat[i, j] <- jaccard(all_gene_sets[[i]],all_gene_sets[[j]])
  }
}


```


```{r, fig.height=12, fig.width=14}
length.mat.df <- as.data.frame(length.mat)

library(tidyverse)

df2 <- length.mat.df %>%
  rownames_to_column() %>%
  gather(colname, value, -rowname)
head(df2)

df2$value <- ifelse(df2$rowname == df2$colname, NA, df2$value)

ggplot(df2, aes(x = rowname, y = colname, fill = value)) +
  geom_tile()
```

Re-format plot

```{r, fig.height=6, fig.width=7}
# Get lower triangle of the correlation matrix
  get_lower_tri<-function(length.mat){
    length.mat[upper.tri(length.mat)] <- NA
    return(length.mat)
  }
  # Get upper triangle of the correlation matrix
  get_upper_tri <- function(length.mat){
    length.mat[lower.tri(length.mat)]<- NA
    return(length.mat)
  }


# Reorder function
reorder_length.mat <- function(length.mat){
# Use correlation between variables as distance
dd <- as.dist((1-length.mat)/2)
hc <- hclust(dd)
length.mat <-length.mat[hc$order, hc$order]
}

# Reorder the correlation matrix
length.mat <- reorder_length.mat(length.mat)
#lower_tri <- get_lower_tri(length.mat)
# Melt the correlation matrix
melted_length.mat <- melt(length.mat, na.rm = TRUE)
melted_length.mat$value <- ifelse(melted_length.mat$Var1 == melted_length.mat$Var2, NA, melted_length.mat$value)
# Create a ggheatmap
ggheatmap <- ggplot(melted_length.mat, aes(Var2, Var1, fill = value))+
 geom_tile(color = "white")+
 scale_fill_gradient2(low = "blue", high = "red", mid = "white", 
   midpoint = 0, space = "Lab", 
    name="Jaccard index", limits=c(0,1)) +
  theme_minimal()+ # minimal theme
 theme(axis.text.x = element_text(angle = 45, vjust = 1, 
    size = 12, hjust = 1),axis.text.y = element_text(size = 12))+
 coord_fixed()+
  geom_text(aes(label = round(value, 2)),size = 5)

# Print the heatmap
ggheatmap + ggtitle("Potential Drug repurposing candidates")
```


PDF
```{r}
pdf(file = "Drug_repurposing_brain_Jaccard_index.pdf", width = 6, height = 7)

ggheatmap + ggtitle("Potential Drug repurposing candidates")

dev.off()
```

SessionInfo
```{r}
sessionInfo()
```

