---
title: "Step1: Preprocess gene list"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    number_sections: true
    theme: readable
vignette: >
  %\VignetteIndexEntry{My Standalone Vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---


# Load gene list

Load libraries.
```{r, message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
```

Load data.
```{r, message=FALSE, warning=FALSE}
data <- read_tsv("data/OT-MONDO_0005090-associated-targets-5_15_2026-v26_03_SCZ.tsv")
```


# Filter gene list

Select data columns and subset.
```{r}
# Here, gene names, Open Targets association scores, and  all columns containing genetic association scores from different databases
columns_genetic <- colnames(data[c(1:2,4:12)])
columns_genetic
data_sub <- subset(data, select = columns_genetic)
```


Remove rows containing 'No data' for genetic associations
```{r}
# Define the columns to check, here all columns containing genetic association scores from different databases
columns_to_check <- colnames(data_sub[3:11])

# Filter the data frame
data_sub_filtered <- data_sub %>%
  filter(!if_all(all_of(columns_to_check), ~ .x == "No data"))

head(data_sub_filtered)
```

# Save gene list

Save the ranked gene set. Ranking is based on the Open Targets globalScore.
```{r, eval=F}
ranked_gene_set <- data_sub_filtered$symbol

write.table(ranked_gene_set, file = "data/ranked_gene_sets/OT-MONDO_0005090-associated-targets-5_15_2026-v26_03_SCZ_genetic.csv", row.names = FALSE, col.names = FALSE, quote = FALSE, sep = ",")
```


<details>
  <summary>Click to show Session Info</summary>

```{r}
sessionInfo()
```

</details>
