---
title: "human_to_mouse"
author: "Aaron Kollotzek"
date: "2023-01-24"
output: html_document
---

NOTE: Example code for generating a file to convert human gene names to mouse.

## Libraries

```{r}
library(biomaRt)
library(dplyr)
library(tidyverse)
library(data.table)
```


```{r, download latest annotation of the human and gene gene names. Does not have Ensembl annotation}
url2 <- "https://www.informatics.jax.org/downloads/reports/HMD_HumanPhenotype.rpt"
raw.file2 <- "mouse_human_genes_HMD_HumanPhenotype.tsv"
dest.file2 <- "mouse_human_genes_feb_23.tsv"

download.file(url2, raw.file2 )
```

```{r, read table}
df2 <- read.table(raw.file2, sep ="\t", header = F)
df2$V6 <- NULL
df2$V5 <- NULL
columns <- c("hgnc_symbol",	"h_entrez_id", "mgi_symbol", "mgi_accession_id")
colnames(df2) <- columns
mts <- df2[df2$mgi_symbol %like% "mt-",]
df2[rownames(mts),]$hgnc_symbol <- paste0("MT-",df2[rownames(mts),]$hgnc_symbol)
df2[rownames(mts),]$hgnc_symbol
df2[df2$mgi_symbol %like% "mt-",]
```


```{r, biomaRt for ensembl gene ids}
human <- useMart('ensembl',dataset='hsapiens_gene_ensembl')
mouse <- useMart('ensembl',dataset='mmusculus_gene_ensembl')
human_genes <- getBM(attributes = c("ensembl_gene_id","hgnc_symbol"), mart = human)
mouse_genes <- getBM(attributes = c("ensembl_gene_id","mgi_symbol"), mart = mouse)
listEnsemblArchives()
```


```{r, merge symbols and ensembl gene ids}
df2 <- df2 %>%
  left_join(human_genes) %>%
  left_join(mouse_genes)
```

note that the dataset increases because there can be the same hgnc symbol for multiple ensembl gene ids apparently
```{r}
df2 <- df2 %>%
  distinct()
write.table(df2, dest.file2, row.names = F,  sep ="\t")
```











