---
title: "meta_data_pval_all_traits_[Human_brain_DLPFC_151673]"
author: "Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
 html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---



# Load data

Load libraries:
```{r, message=FALSE}
library(dplyr)
library(tidyverse)
library(STutility)
library(viridis)
```

Load ST data:
```{r}

infoTable <- read.csv("spatial_data/infoTable.csv", sep = ";")


se <- InputFromTable(infotable = infoTable, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

```

Load image:
```{r}
se <- LoadImages(se, time.resolve = FALSE)
```


Normalize data: se <- SCTransform(se,return.only.var.genes = T)
```{r, message=FALSE, include=FALSE}
se <- SCTransform(se,return.only.var.genes = T)
```


```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "KIF5B", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)

```


```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "CLU", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)

```


```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "KCNB1", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)

```



```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "KCNV1", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)

```



```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "CACNA2D1", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)

```

```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("Manuscript_plots/CLU.png"), res = png_res, width = 5*png_res, height = 4*png_res)
ST.FeaturePlot(se, features = "CLU", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)
dev.off()
```


```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("Manuscript_plots/KIF5B.png"), res = png_res, width = 5*png_res, height = 4*png_res)
ST.FeaturePlot(se, features = "KIF5B", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)
dev.off()
```

```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("Manuscript_plots/KCNB1.png"), res = png_res, width = 5*png_res, height = 4*png_res)
ST.FeaturePlot(se, features = "KCNB1", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)
dev.off()
```

```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("Manuscript_plots/KCNV1.png"), res = png_res, width = 5*png_res, height = 4*png_res)
ST.FeaturePlot(se, features = "KCNV1", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)
dev.off()
```

```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("Manuscript_plots/CACNA2D1.png"), res = png_res, width = 5*png_res, height = 4*png_res)
ST.FeaturePlot(se, features = "CACNA2D1", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)
dev.off()
```


Load cluster annotations
```{r}
seurat_clusters <- read.csv(file = "spatial_structures/seurat_clusters.csv", sep = ";")
```

Add annotations to seurat object
```{r}
rownames(seurat_clusters) <- seurat_clusters$Barcode
seurat_clusters$Barcode <- NULL
se$seurat_clusters <- seurat_clusters
se$seurat_clusters_plot <- as.factor(se$seurat_clusters) # For plotting of spatial structures
head(se[[]])
```

## Plot seurat_clusters
```{r, fig.height=4, fig.width=5}
library(RColorBrewer)

n <- 9
qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
col_vector[7] <- "darkmagenta"
col_vector[9] <- "deepskyblue"
  
col_vector <- col_vector[1:9]

se <- SetIdent(se, value = "seurat_clusters_plot")
ST.FeaturePlot(object = se, features = "seurat_clusters_plot", pt.size = 1, cols = col_vector)
```


```{r}
VlnPlot(se, features = c("KIF5B"), ncol = 1, group.by = "seurat_clusters", cols = col_vector) + geom_boxplot(width=0.4) + theme(plot.title = element_text(size = 12))
```


```{r}
VlnPlot(se, features = c("CLU"), ncol = 1, group.by = "seurat_clusters", cols = col_vector) + geom_boxplot(width=0.4) + theme(plot.title = element_text(size = 12))
```


```{r}
VlnPlot(se, features = c("KCNB1"), ncol = 1, group.by = "seurat_clusters", cols = col_vector) + geom_boxplot(width=0.4) + theme(plot.title = element_text(size = 12))
```

```{r}
VlnPlot(se, features = c("KCNV1"), ncol = 1, group.by = "seurat_clusters", cols = col_vector) + geom_boxplot(width=0.4) + theme(plot.title = element_text(size = 12))
```

```{r}
VlnPlot(se, features = c("CACNA2D1"), ncol = 1, group.by = "seurat_clusters", cols = col_vector) + geom_boxplot(width=0.4) + theme(plot.title = element_text(size = 12))
```


```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("Manuscript_plots/VlnPlot_KIF5B.png"), res = png_res, width = 6*png_res, height = 4*png_res)
VlnPlot(se, features = c("KIF5B"), ncol = 1, group.by = "seurat_clusters", cols = col_vector) + geom_boxplot(width=0.4) + theme(plot.title = element_text(size = 12))
dev.off()
```


```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("Manuscript_plots/VlnPlot_CLU.png"), res = png_res, width = 6*png_res, height = 4*png_res)
VlnPlot(se, features = c("CLU"), ncol = 1, group.by = "seurat_clusters", cols = col_vector) + geom_boxplot(width=0.4) + theme(plot.title = element_text(size = 12))
dev.off()
```


```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("Manuscript_plots/VlnPlot_KCNB1.png"), res = png_res, width = 6*png_res, height = 4*png_res)
VlnPlot(se, features = c("KCNB1"), ncol = 1, group.by = "seurat_clusters", cols = col_vector) + geom_boxplot(width=0.4) + theme(plot.title = element_text(size = 12))
dev.off()
```


```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("Manuscript_plots/VlnPlot_KCNV1.png"), res = png_res, width = 6*png_res, height = 4*png_res)
VlnPlot(se, features = c("KCNV1"), ncol = 1, group.by = "seurat_clusters", cols = col_vector) + geom_boxplot(width=0.4) + theme(plot.title = element_text(size = 12))
dev.off()
```


```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("Manuscript_plots/VlnPlot_CACNA2D1.png"), res = png_res, width = 6*png_res, height = 4*png_res)
VlnPlot(se, features = c("CACNA2D1"), ncol = 1, group.by = "seurat_clusters", cols = col_vector) + geom_boxplot(width=0.4) + theme(plot.title = element_text(size = 12))
dev.off()
```



# Notes
```{r}
sessionInfo()
```

