---
title: "OT_all_genes_in_datasets"
output: html_document
date: "2026-06-26"
---


```{r}
library(dplyr)
library(ggplot2)
```



```{r}
my_data <- read.csv(file = "OT_all_genes_in_datasets.csv", sep = ";")
```



```{r}
plot_data <- my_data %>%
  group_by(dataset, trait) %>%
  mutate(prop = nr_of_genes / sum(nr_of_genes))

plot_data$dataset <- factor(
  plot_data$dataset,
  levels = c("human_brain",
             "human_liver",
             "human_heart",
             "mouse_brain",
             "mouse_liver")
)


plot_data$trait <- factor(
  plot_data$trait,
  levels = c("ALZ",
             "ADHD",
             "ASD",
             "BIP",
             "SCZ")
)


ggplot(plot_data,
       aes(x = trait, y = prop, fill = category)) +
  geom_col(width = 0.8) +
  facet_wrap(~dataset, nrow = 2, ncol = 3) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = c("in dataset" = "blue",
                               "not in dataset" = "#E41A1C")) +
  labs(x = "Trait",
       y = "Proportion of genes",
       fill = "") +
  theme_bw() +
  theme(strip.background = element_rect(fill = "grey90"),
        axis.text.x = element_text(angle = 45, hjust = 1))
```



```{r, fig.width=10, fig.height=3}
plot_data <- my_data %>%
  group_by(dataset, trait) %>%
  mutate(prop = nr_of_genes / sum(nr_of_genes))

plot_data$dataset <- factor(
  plot_data$dataset,
  levels = c("human_brain",
             "mouse_brain",
             "human_liver",
             "mouse_liver",
             "human_heart")
)


plot_data$trait <- factor(
  plot_data$trait,
  levels = c("ALZ",
             "ADHD",
             "ASD",
             "BIP",
             "SCZ")
)


p <- ggplot(plot_data,
       aes(x = trait, y = prop, fill = category)) +
  geom_col(width = 0.8) +
  facet_wrap(~dataset, nrow = 1) +
  scale_y_continuous(labels = scales::percent) +
  scale_fill_manual(values = c("in dataset" = "mediumslateblue",
                               "not in dataset" = "orangered")) +
  labs(x = "Trait",
       y = "Proportion of genes",
       fill = "") +
  theme_bw() +
  theme(strip.background = element_rect(fill = "grey90"),
        axis.text.x = element_text(angle = 45, hjust = 1))

p
```


```{r}
pdf("OT_all_genes_in_datasets.pdf", width = 10, height = 3)

p

dev.off()

```



Notes
```{r}
sessionInfo()
```

