---
title: "meta_data_pval_all_traits_[Human_brain_DLPFC_151673]_ALZ"
author: "Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
 html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

NOTE: Plots SupFig 18 a and b.

# Load data

Load libraries:
```{r, message=FALSE}
library(dplyr)
library(tidyverse)
library(STutility)
library(viridis)
```

Load ST data:
```{r}

infoTable <- read.csv("spatial_data/infoTable.csv", sep = ";")


se <- InputFromTable(infotable = infoTable, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

```

Load image:
```{r}
se <- LoadImages(se, time.resolve = FALSE)
```

Load meta data:
```{r}
meta.data.ALZ <- readRDS(file = "Meta_data_pval/meta.data.pval_ALZ_all_genes.RDS")
meta.data.ALZ_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_ALZ_top60_genes.RDS")

rownames(meta.data.ALZ) <- meta.data.ALZ$CellID
rownames(meta.data.ALZ_topgenes) <- meta.data.ALZ_topgenes$CellID

nr_of_pvals <- 19*10
```


Merge meta data
```{r}

meta.data.ALZ$neg.log10.p.val.g_topgenes <- meta.data.ALZ_topgenes$neg.log10.p.val.g
meta.data.ALZ$neg.log10.p.val.adj.g_topgenes <- meta.data.ALZ_topgenes$neg.log10.p.val.adj.g

```

Re-name colnames
```{r}
meta.data.ALZ$neg.log10.p.val.g.ALZ <- meta.data.ALZ$neg.log10.p.val.g
meta.data.ALZ$neg.log10.p.val.adj.g.ALZ <- meta.data.ALZ$neg.log10.p.val.adj.g
meta.data.ALZ$neg.log10.p.val.d.ALZ <- meta.data.ALZ$neg.log10.p.val.d
meta.data.ALZ$neg.log10.p.val.adj.d.ALZ <- meta.data.ALZ$neg.log10.p.val.adj.d
meta.data.ALZ$neg.log10.p.val.g_topgenes.ALZ <- meta.data.ALZ$neg.log10.p.val.g_topgenes
meta.data.ALZ$neg.log10.p.val.adj.g_topgenes.ALZ <- meta.data.ALZ$neg.log10.p.val.adj.g_topgenes

```

Add meta data:
```{r}
se <- AddMetaData(se, metadata = meta.data.ALZ)

se$neg.log10.p.val.g <- NULL
se$neg.log10.p.val.adj.g <- NULL
se$neg.log10.p.val.g_topgenes <- NULL
se$neg.log10.p.val.adj.g_topgenes <- NULL
se$neg.log10.p.val.d <- NULL
se$neg.log10.p.val.adj.d <- NULL

head(se[[]])

```



Samplewise scaling
```{r, fig.height=4,fig.width=5}
ST.FeaturePlot(object = se, features = c("neg.log10.p.val.adj.g_topgenes.ALZ"), pt.size = 1.5, cols = viridis(nr_of_pvals))
```


PDF
```{r, eval=T}
pdf(file = "meta_data_pval_all_traits_[Human_brain_DLPFC_151673]_ALZ.pdf", height = 4, width = 5)

ST.FeaturePlot(object = se, features = c("neg.log10.p.val.adj.g_topgenes.ALZ"), pt.size = 1.5, cols = viridis(nr_of_pvals))
dev.off()
```


Normalize data: se <- SCTransform(se,return.only.var.genes = T)
```{r, message=FALSE, include=FALSE}
se <- SCTransform(se,return.only.var.genes = T)
```


```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "IGKC", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)

```


```{r, fig.width=5, fig.height=4}
ST.FeaturePlot(se, features = "BIN1", cols = c("lightgray", "mistyrose", "red", "dark red", "black"), pt.size = 1.3)

```

# Notes
```{r}
sessionInfo()
```

