---
title: "meta_data_pval_all_traits_[mouse_JBO002]"
author: "Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
 html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

For top genes NA, values were set to zero and colored grey manually. For drugs with no data, values were set to zero and plot removed manually.

# Load data

Load libraries:
```{r, message=FALSE}
library(dplyr)
library(tidyverse)
library(STutility)
library(viridis)
```

Load ST data:
```{r}

infoTable <- read.csv("spatial_data/infoTable.csv", sep = ";")


se <- InputFromTable(infotable = infoTable, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

```

Load image:
```{r}
se <- LoadImages(se, time.resolve = FALSE)
```

Load meta data:
```{r}
meta.data.CAD <- readRDS(file = "Meta_data_pval/meta.data.pval_CAD_all_genes.RDS")
meta.data.CAD_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_CAD_top70_genes.RDS")

rownames(meta.data.CAD) <- meta.data.CAD$CellID
rownames(meta.data.CAD_topgenes) <- meta.data.CAD_topgenes$CellID

meta.data.CIRR <- readRDS(file = "Meta_data_pval/meta.data.pval_CIRR_all_genes.RDS")
#meta.data.CIRR_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_CIRR_topGenes_genes.RDS") N/A

# N/A for top genes, set all to zero
rownames(meta.data.CIRR) <- meta.data.CIRR$CellID
meta.data.CIRR_topgenes <- meta.data.CIRR
meta.data.CIRR_topgenes$neg.log10.p.val.g <- 0
meta.data.CIRR_topgenes$neg.log10.p.val.adj.g <- 0
meta.data.CIRR_topgenes$neg.log10.p.val.d <- 0
meta.data.CIRR_topgenes$neg.log10.p.val.adj.d <- 0

meta.data.CHOL <- readRDS(file = "Meta_data_pval/meta.data.pval_CHOL_all_genes.RDS")
meta.data.CHOL_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_CHOL_top70_genes.RDS")

rownames(meta.data.CHOL) <- meta.data.CHOL$CellID
rownames(meta.data.CHOL_topgenes) <- meta.data.CHOL_topgenes$CellID

meta.data.CHOL$neg.log10.p.val.d <- 0
meta.data.CHOL$neg.log10.p.val.adj.d <- 0
meta.data.CHOL_topgenes$neg.log10.p.val.d <- 0
meta.data.CHOL_topgenes$neg.log10.p.val.adj.d <- 0
  
meta.data.LD <- readRDS(file = "Meta_data_pval/meta.data.pval_LD_all_genes.RDS")
meta.data.LD_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_LD_top60_genes.RDS")

rownames(meta.data.LD) <- meta.data.LD$CellID
rownames(meta.data.LD_topgenes) <- meta.data.LD_topgenes$CellID

meta.data.LDL <- readRDS(file = "Meta_data_pval/meta.data.pval_LDL_all_genes.RDS")
meta.data.LDL_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_LDL_top90_genes.RDS")

rownames(meta.data.LDL) <- meta.data.LDL$CellID
rownames(meta.data.LDL_topgenes) <- meta.data.LDL_topgenes$CellID

meta.data.LDL$neg.log10.p.val.d <- 0
meta.data.LDL$neg.log10.p.val.adj.d <- 0
meta.data.LDL_topgenes$neg.log10.p.val.d <- 0
meta.data.LDL_topgenes$neg.log10.p.val.adj.d <- 0

meta.data.MI <- readRDS(file = "Meta_data_pval/meta.data.pval_MI_all_genes.RDS")
meta.data.MI_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_MI_top50_genes.RDS")

rownames(meta.data.MI) <- meta.data.MI$CellID
rownames(meta.data.MI_topgenes) <- meta.data.MI_topgenes$CellID

meta.data.NAFLD <- readRDS(file = "Meta_data_pval/meta.data.pval_NAFLD_all_genes.RDS")
meta.data.NAFLD_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_NAFLD_top50_genes.RDS")

rownames(meta.data.NAFLD) <- meta.data.NAFLD$CellID
rownames(meta.data.NAFLD_topgenes) <- meta.data.NAFLD_topgenes$CellID

nr_of_pvals <- 6*7
```


Merge meta data
```{r}
meta.data.CAD$neg.log10.p.val.g_topgenes <- meta.data.CAD_topgenes$neg.log10.p.val.g
meta.data.CAD$neg.log10.p.val.adj.g_topgenes <- meta.data.CAD_topgenes$neg.log10.p.val.adj.g

meta.data.CIRR$neg.log10.p.val.g_topgenes <- meta.data.CIRR_topgenes$neg.log10.p.val.g
meta.data.CIRR$neg.log10.p.val.adj.g_topgenes <- meta.data.CIRR_topgenes$neg.log10.p.val.adj.g

meta.data.CHOL$neg.log10.p.val.g_topgenes <- meta.data.CHOL_topgenes$neg.log10.p.val.g
meta.data.CHOL$neg.log10.p.val.adj.g_topgenes <- meta.data.CHOL_topgenes$neg.log10.p.val.adj.g

meta.data.LD$neg.log10.p.val.g_topgenes <- meta.data.LD_topgenes$neg.log10.p.val.g
meta.data.LD$neg.log10.p.val.adj.g_topgenes <- meta.data.LD_topgenes$neg.log10.p.val.adj.g

meta.data.LDL$neg.log10.p.val.g_topgenes <- meta.data.LDL_topgenes$neg.log10.p.val.g
meta.data.LDL$neg.log10.p.val.adj.g_topgenes <- meta.data.LDL_topgenes$neg.log10.p.val.adj.g

meta.data.MI$neg.log10.p.val.g_topgenes <- meta.data.MI_topgenes$neg.log10.p.val.g
meta.data.MI$neg.log10.p.val.adj.g_topgenes <- meta.data.MI_topgenes$neg.log10.p.val.adj.g

meta.data.NAFLD$neg.log10.p.val.g_topgenes <- meta.data.NAFLD_topgenes$neg.log10.p.val.g
meta.data.NAFLD$neg.log10.p.val.adj.g_topgenes <- meta.data.NAFLD_topgenes$neg.log10.p.val.adj.g
```

Re-name colnames
```{r}
meta.data.CAD$neg.log10.p.val.g.CAD <- meta.data.CAD$neg.log10.p.val.g
meta.data.CAD$neg.log10.p.val.adj.g.CAD <- meta.data.CAD$neg.log10.p.val.adj.g
meta.data.CAD$neg.log10.p.val.d.CAD <- meta.data.CAD$neg.log10.p.val.d
meta.data.CAD$neg.log10.p.val.adj.d.CAD <- meta.data.CAD$neg.log10.p.val.adj.d
meta.data.CAD$neg.log10.p.val.g_topgenes.CAD <- meta.data.CAD$neg.log10.p.val.g_topgenes
meta.data.CAD$neg.log10.p.val.adj.g_topgenes.CAD <- meta.data.CAD$neg.log10.p.val.adj.g_topgenes

meta.data.CIRR$neg.log10.p.val.g.CIRR <- meta.data.CIRR$neg.log10.p.val.g
meta.data.CIRR$neg.log10.p.val.adj.g.CIRR <- meta.data.CIRR$neg.log10.p.val.adj.g
meta.data.CIRR$neg.log10.p.val.d.CIRR <- meta.data.CIRR$neg.log10.p.val.d
meta.data.CIRR$neg.log10.p.val.adj.d.CIRR <- meta.data.CIRR$neg.log10.p.val.adj.d
meta.data.CIRR$neg.log10.p.val.g_topgenes.CIRR <- meta.data.CIRR$neg.log10.p.val.g_topgenes
meta.data.CIRR$neg.log10.p.val.adj.g_topgenes.CIRR <- meta.data.CIRR$neg.log10.p.val.adj.g_topgenes

meta.data.CHOL$neg.log10.p.val.g.CHOL <- meta.data.CHOL$neg.log10.p.val.g
meta.data.CHOL$neg.log10.p.val.adj.g.CHOL <- meta.data.CHOL$neg.log10.p.val.adj.g
meta.data.CHOL$neg.log10.p.val.d.CHOL <- meta.data.CHOL$neg.log10.p.val.d
meta.data.CHOL$neg.log10.p.val.adj.d.CHOL <- meta.data.CHOL$neg.log10.p.val.adj.d
meta.data.CHOL$neg.log10.p.val.g_topgenes.CHOL <- meta.data.CHOL$neg.log10.p.val.g_topgenes
meta.data.CHOL$neg.log10.p.val.adj.g_topgenes.CHOL <- meta.data.CHOL$neg.log10.p.val.adj.g_topgenes
  
meta.data.LD$neg.log10.p.val.g.LD <- meta.data.LD$neg.log10.p.val.g
meta.data.LD$neg.log10.p.val.adj.g.LD <- meta.data.LD$neg.log10.p.val.adj.g
meta.data.LD$neg.log10.p.val.d.LD <- meta.data.LD$neg.log10.p.val.d
meta.data.LD$neg.log10.p.val.adj.d.LD <- meta.data.LD$neg.log10.p.val.adj.d
meta.data.LD$neg.log10.p.val.g_topgenes.LD <- meta.data.LD$neg.log10.p.val.g_topgenes
meta.data.LD$neg.log10.p.val.adj.g_topgenes.LD <- meta.data.LD$neg.log10.p.val.adj.g_topgenes

meta.data.LDL$neg.log10.p.val.g.LDL <- meta.data.LDL$neg.log10.p.val.g
meta.data.LDL$neg.log10.p.val.adj.g.LDL <- meta.data.LDL$neg.log10.p.val.adj.g
meta.data.LDL$neg.log10.p.val.d.LDL <- meta.data.LDL$neg.log10.p.val.d
meta.data.LDL$neg.log10.p.val.adj.d.LDL <- meta.data.LDL$neg.log10.p.val.adj.d
meta.data.LDL$neg.log10.p.val.g_topgenes.LDL <- meta.data.LDL$neg.log10.p.val.g_topgenes
meta.data.LDL$neg.log10.p.val.adj.g_topgenes.LDL <- meta.data.LDL$neg.log10.p.val.adj.g_topgenes

meta.data.MI$neg.log10.p.val.g.MI <- meta.data.MI$neg.log10.p.val.g
meta.data.MI$neg.log10.p.val.adj.g.MI <- meta.data.MI$neg.log10.p.val.adj.g
meta.data.MI$neg.log10.p.val.d.MI <- meta.data.MI$neg.log10.p.val.d
meta.data.MI$neg.log10.p.val.adj.d.MI <- meta.data.MI$neg.log10.p.val.adj.d
meta.data.MI$neg.log10.p.val.g_topgenes.MI <- meta.data.MI$neg.log10.p.val.g_topgenes
meta.data.MI$neg.log10.p.val.adj.g_topgenes.MI <- meta.data.MI$neg.log10.p.val.adj.g_topgenes

meta.data.NAFLD$neg.log10.p.val.g.NAFLD <- meta.data.NAFLD$neg.log10.p.val.g
meta.data.NAFLD$neg.log10.p.val.adj.g.NAFLD <- meta.data.NAFLD$neg.log10.p.val.adj.g
meta.data.NAFLD$neg.log10.p.val.d.NAFLD <- meta.data.NAFLD$neg.log10.p.val.d
meta.data.NAFLD$neg.log10.p.val.adj.d.NAFLD <- meta.data.NAFLD$neg.log10.p.val.adj.d
meta.data.NAFLD$neg.log10.p.val.g_topgenes.NAFLD <- meta.data.NAFLD$neg.log10.p.val.g_topgenes
meta.data.NAFLD$neg.log10.p.val.adj.g_topgenes.NAFLD <- meta.data.NAFLD$neg.log10.p.val.adj.g_topgenes

```

Add meta data:
```{r}
se <- AddMetaData(se, metadata = meta.data.CAD)

se <- AddMetaData(se, metadata = meta.data.CIRR)

se <- AddMetaData(se, metadata = meta.data.CHOL)

se <- AddMetaData(se, metadata = meta.data.LD)

se <- AddMetaData(se, metadata = meta.data.LDL)

se <- AddMetaData(se, metadata = meta.data.MI)

se <- AddMetaData(se, metadata = meta.data.NAFLD)

se$neg.log10.p.val.g <- NULL
se$neg.log10.p.val.adj.g <- NULL
se$neg.log10.p.val.g_topgenes <- NULL
se$neg.log10.p.val.adj.g_topgenes <- NULL
se$neg.log10.p.val.d <- NULL
se$neg.log10.p.val.adj.d <- NULL

head(se[[]])

```

All same scale
```{r, fig.height=25,fig.width=14}
ST.FeaturePlot(object = se, features = c("neg.log10.p.val.adj.g.CAD","neg.log10.p.val.adj.g_topgenes.CAD","neg.log10.p.val.adj.d.CAD","neg.log10.p.val.adj.g.CIRR","neg.log10.p.val.adj.g_topgenes.CIRR","neg.log10.p.val.adj.d.CIRR","neg.log10.p.val.adj.g.CHOL","neg.log10.p.val.adj.g_topgenes.CHOL","neg.log10.p.val.adj.d.CHOL","neg.log10.p.val.adj.g.LD","neg.log10.p.val.adj.g_topgenes.LD","neg.log10.p.val.adj.d.LD","neg.log10.p.val.adj.g.LDL","neg.log10.p.val.adj.g_topgenes.LDL","neg.log10.p.val.adj.d.LDL","neg.log10.p.val.adj.g.MI","neg.log10.p.val.adj.g_topgenes.MI","neg.log10.p.val.adj.d.MI","neg.log10.p.val.adj.g.NAFLD","neg.log10.p.val.adj.g_topgenes.NAFLD","neg.log10.p.val.adj.d.NAFLD"), pt.size = 1.3, cols = viridis(nr_of_pvals),value.scale = "all",grid.ncol =3)
```

Samplewise scaling
```{r, fig.height=25,fig.width=14}
ST.FeaturePlot(object = se, features = c("neg.log10.p.val.adj.g.CAD","neg.log10.p.val.adj.g_topgenes.CAD","neg.log10.p.val.adj.d.CAD","neg.log10.p.val.adj.g.CIRR","neg.log10.p.val.adj.g_topgenes.CIRR","neg.log10.p.val.adj.d.CIRR","neg.log10.p.val.adj.g.CHOL","neg.log10.p.val.adj.g_topgenes.CHOL","neg.log10.p.val.adj.d.CHOL","neg.log10.p.val.adj.g.LD","neg.log10.p.val.adj.g_topgenes.LD","neg.log10.p.val.adj.d.LD","neg.log10.p.val.adj.g.LDL","neg.log10.p.val.adj.g_topgenes.LDL","neg.log10.p.val.adj.d.LDL","neg.log10.p.val.adj.g.MI","neg.log10.p.val.adj.g_topgenes.MI","neg.log10.p.val.adj.d.MI","neg.log10.p.val.adj.g.NAFLD","neg.log10.p.val.adj.g_topgenes.NAFLD","neg.log10.p.val.adj.d.NAFLD"), pt.size = 1.3, cols = viridis(nr_of_pvals),value.scale = "samplewise",grid.ncol =3)
```

PDF
```{r}
pdf(file = "meta_data_pval_all_traits_[mouse_JBO002].pdf", height = 25, width = 14)

ST.FeaturePlot(object = se, features = c("neg.log10.p.val.adj.g.CAD","neg.log10.p.val.adj.g_topgenes.CAD","neg.log10.p.val.adj.d.CAD","neg.log10.p.val.adj.g.CIRR","neg.log10.p.val.adj.g_topgenes.CIRR","neg.log10.p.val.adj.d.CIRR","neg.log10.p.val.adj.g.CHOL","neg.log10.p.val.adj.g_topgenes.CHOL","neg.log10.p.val.adj.d.CHOL","neg.log10.p.val.adj.g.LD","neg.log10.p.val.adj.g_topgenes.LD","neg.log10.p.val.adj.d.LD","neg.log10.p.val.adj.g.LDL","neg.log10.p.val.adj.g_topgenes.LDL","neg.log10.p.val.adj.d.LDL","neg.log10.p.val.adj.g.MI","neg.log10.p.val.adj.g_topgenes.MI","neg.log10.p.val.adj.d.MI","neg.log10.p.val.adj.g.NAFLD","neg.log10.p.val.adj.g_topgenes.NAFLD","neg.log10.p.val.adj.d.NAFLD"), pt.size = 1.3, cols = viridis(nr_of_pvals),value.scale = "all",grid.ncol =3)

dev.off()
```



# Notes
```{r}
sessionInfo()
```

