---
title: "Allen_Brain_Atlas_Mouse_CTX-HPF_dataset_random_250_cells"
output: html_document
author: "Linda Kvastad"
date: "2024-09-19"
---

NOTE: Random downsampling of the Allen Brain Atlas single-cell data.

```{r}
## Load necessary libraries
library(rhdf5)      # For reading hdf5; https://www.bioconductor.org/packages/devel/bioc/vignettes/rhdf5/inst/doc/rhdf5.html
library(HDF5Array)  # Alternatively option for reading the data matrix with less memory: https://rdrr.io/github/Bioconductor/HDF5Array/
library(data.table) # For fast reading of csv files
library(Seurat)
```

```{r}
## Read in sample and gene names for use later
genes   <- h5read("expression_matrix.hdf5","/data/gene")
samples <- h5read("expression_matrix.hdf5","/data/samples")

```


```{r}
## Read in the metadata using fread (fast!)
metadata <- fread("metadata.csv")
metadata <- as.data.frame(metadata)
rownames(metadata) <- metadata$sample_name
# Note that the order of metadata and counts and the number of cells are DIFFERENT 
#   (there are 107 cells with no metadata). This will be critical later!

```


```{r}
## Subsample your data
## -- If you want to analyze these data in R and especially using Seurat, you will
## --   have a better chance of success if you only work on parts of the data at a
## --   time.  We suggest, using information in the metadata (e.g., cell type or
## --   brain region columns) to subset.   
## -- For this example code, I'm selecting 1000 random cells checking overlap with samples

#set.seed(42)
#use_samples  <- intersect(sample(rownames(metadata),1000),samples)
#read_samples <- sort(match(use_samples,samples))

```


```{r}
# Set seed for reproducibility
set.seed(42)

# Subset and randomly sample up to 250 cells per subclass
use_samples <- unlist(lapply(split(metadata, metadata$subclass_label), function(subset) {
  # Ensure we don't sample more than the available number of cells
  sample(rownames(subset), min(250, nrow(subset)), replace = FALSE)
}))

# Find intersection with your existing samples
use_samples <- intersect(use_samples, samples)

# Match the use_samples with the original samples
read_samples <- sort(match(use_samples, samples))

# `use_samples` contains the subset of cells, `read_samples` contains the indices

```



```{r}
## Strategy #2: Read in only a relevant subset of data using h5read. This is the 
##   method that probably works best in most situations.
system.time({
  counts1 <- h5read("expression_matrix.hdf5", "/data/counts", index = list(read_samples,NULL))
  counts1 <- t(counts1)
  subcounts1 <- as(counts1, "dgCMatrix")
}) 

```


```{r}
## Add gene and sample names to the data matrix
## -- Note: We'll works with the recommended strategy (#2) for the rest of the script
rownames(subcounts1) <- as.character(genes)
colnames(subcounts1) <- as.character(samples) [read_samples]

```


```{r}
## Read the subsetted data and metadata into Seurat
## -- Note that this **WILL NOT WORK** for the full 1 Million+ cell data set!
## -- I would strongly encourage other methods for analysis when dealing with more than ~100,000 cells at a time
## -- Also recall that the order of data and meta do not match, so reorder here
seu <- CreateSeuratObject(counts=subcounts1)          # Put in a Seurat object
met <- as.data.frame(metadata[colnames(subcounts1),]) # Format the metadata
se <- AddMetaData(seu,met)                           # Add the metadata

```

```{r}
head(se[[]])
```


```{r}
table(se$subclass_label)
```



```{r}
table(se$class_label)
```


```{r}
saveRDS(se, file = "se_allen_brain_atlas_random_250_subclass_label.rds")
```



Notes
```{r}
sessionInfo()
```

