---
title: "meta_data_pval_all_traits_[HLA_Bronchi_A42_311]"
author: "Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
 html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

NOTE: Plots SupFig 12a. For top genes NA, values were set to zero and colored grey manually.

# Load data

Load libraries:
```{r, message=FALSE}
library(dplyr)
library(tidyverse)
library(STutility)
library(viridis)
```

Load ST data:
```{r}

infoTable <- read.csv("spatial_data/infoTable.csv", sep = ";")


se <- InputFromTable(infotable = infoTable, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

```

Load image:
```{r}
se <- LoadImages(se, time.resolve = FALSE)
```

Load meta data:
```{r}
meta.data.AST <- readRDS(file = "Meta_data_pval/meta.data.pval_AST_all_genes.RDS")
#meta.data.AST_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_AST_topGenes_genes.RDS") N/A

# N/A for top genes, set all to zero
rownames(meta.data.AST) <- meta.data.AST$CellID
meta.data.AST_topgenes <- meta.data.AST
meta.data.AST_topgenes$neg.log10.p.val.g <- 0
meta.data.AST_topgenes$neg.log10.p.val.adj.g <- 0
meta.data.AST_topgenes$neg.log10.p.val.d <- 0
meta.data.AST_topgenes$neg.log10.p.val.adj.d <- 0

meta.data.BRD <- readRDS(file = "Meta_data_pval/meta.data.pval_BRD_all_genes.RDS")
#meta.data.BRD_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_BRD_topGenes_genes.RDS") N/A

# N/A for top genes, set all to zero
rownames(meta.data.BRD) <- meta.data.BRD$CellID
meta.data.BRD_topgenes <- meta.data.BRD
meta.data.BRD_topgenes$neg.log10.p.val.g <- 0
meta.data.BRD_topgenes$neg.log10.p.val.adj.g <- 0
meta.data.BRD_topgenes$neg.log10.p.val.d <- 0
meta.data.BRD_topgenes$neg.log10.p.val.adj.d <- 0

meta.data.COPD <- readRDS(file = "Meta_data_pval/meta.data.pval_COPD_all_genes.RDS")
meta.data.COPD_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_COPD_top80_genes.RDS")

rownames(meta.data.COPD) <- meta.data.COPD$CellID
rownames(meta.data.COPD_topgenes) <- meta.data.COPD_topgenes$CellID

meta.data.LUD <- readRDS(file = "Meta_data_pval/meta.data.pval_LUD_all_genes.RDS")
meta.data.LUD_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_LUD_top90_genes.RDS")

rownames(meta.data.LUD) <- meta.data.LUD$CellID
rownames(meta.data.LUD_topgenes) <- meta.data.LUD_topgenes$CellID

nr_of_pvals <- 8*4
```


Merge meta data
```{r}
meta.data.AST$neg.log10.p.val.g_topgenes <- meta.data.AST_topgenes$neg.log10.p.val.g
meta.data.AST$neg.log10.p.val.adj.g_topgenes <- meta.data.AST_topgenes$neg.log10.p.val.adj.g

meta.data.BRD$neg.log10.p.val.g_topgenes <- meta.data.BRD_topgenes$neg.log10.p.val.g
meta.data.BRD$neg.log10.p.val.adj.g_topgenes <- meta.data.BRD_topgenes$neg.log10.p.val.adj.g

meta.data.COPD$neg.log10.p.val.g_topgenes <- meta.data.COPD_topgenes$neg.log10.p.val.g
meta.data.COPD$neg.log10.p.val.adj.g_topgenes <- meta.data.COPD_topgenes$neg.log10.p.val.adj.g

meta.data.LUD$neg.log10.p.val.g_topgenes <- meta.data.LUD_topgenes$neg.log10.p.val.g
meta.data.LUD$neg.log10.p.val.adj.g_topgenes <- meta.data.LUD_topgenes$neg.log10.p.val.adj.g
```

Re-name colnames
```{r}
meta.data.AST$neg.log10.p.val.g.AST <- meta.data.AST$neg.log10.p.val.g
meta.data.AST$neg.log10.p.val.adj.g.AST <- meta.data.AST$neg.log10.p.val.adj.g
meta.data.AST$neg.log10.p.val.d.AST <- meta.data.AST$neg.log10.p.val.d
meta.data.AST$neg.log10.p.val.adj.d.AST <- meta.data.AST$neg.log10.p.val.adj.d
meta.data.AST$neg.log10.p.val.g_topgenes.AST <- meta.data.AST$neg.log10.p.val.g_topgenes
meta.data.AST$neg.log10.p.val.adj.g_topgenes.AST <- meta.data.AST$neg.log10.p.val.adj.g_topgenes

meta.data.BRD$neg.log10.p.val.g.BRD <- meta.data.BRD$neg.log10.p.val.g
meta.data.BRD$neg.log10.p.val.adj.g.BRD <- meta.data.BRD$neg.log10.p.val.adj.g
meta.data.BRD$neg.log10.p.val.d.BRD <- meta.data.BRD$neg.log10.p.val.d
meta.data.BRD$neg.log10.p.val.adj.d.BRD <- meta.data.BRD$neg.log10.p.val.adj.d
meta.data.BRD$neg.log10.p.val.g_topgenes.BRD <- meta.data.BRD$neg.log10.p.val.g_topgenes
meta.data.BRD$neg.log10.p.val.adj.g_topgenes.BRD <- meta.data.BRD$neg.log10.p.val.adj.g_topgenes
  
meta.data.COPD$neg.log10.p.val.g.COPD <- meta.data.COPD$neg.log10.p.val.g
meta.data.COPD$neg.log10.p.val.adj.g.COPD <- meta.data.COPD$neg.log10.p.val.adj.g
meta.data.COPD$neg.log10.p.val.d.COPD <- meta.data.COPD$neg.log10.p.val.d
meta.data.COPD$neg.log10.p.val.adj.d.COPD <- meta.data.COPD$neg.log10.p.val.adj.d
meta.data.COPD$neg.log10.p.val.g_topgenes.COPD <- meta.data.COPD$neg.log10.p.val.g_topgenes
meta.data.COPD$neg.log10.p.val.adj.g_topgenes.COPD <- meta.data.COPD$neg.log10.p.val.adj.g_topgenes

meta.data.LUD$neg.log10.p.val.g.LUD <- meta.data.LUD$neg.log10.p.val.g
meta.data.LUD$neg.log10.p.val.adj.g.LUD <- meta.data.LUD$neg.log10.p.val.adj.g
meta.data.LUD$neg.log10.p.val.d.LUD <- meta.data.LUD$neg.log10.p.val.d
meta.data.LUD$neg.log10.p.val.adj.d.LUD <- meta.data.LUD$neg.log10.p.val.adj.d
meta.data.LUD$neg.log10.p.val.g_topgenes.LUD <- meta.data.LUD$neg.log10.p.val.g_topgenes
meta.data.LUD$neg.log10.p.val.adj.g_topgenes.LUD <- meta.data.LUD$neg.log10.p.val.adj.g_topgenes

```

Add meta data:
```{r}
se <- AddMetaData(se, metadata = meta.data.AST)

se <- AddMetaData(se, metadata = meta.data.BRD)

se <- AddMetaData(se, metadata = meta.data.COPD)

se <- AddMetaData(se, metadata = meta.data.LUD)

se$neg.log10.p.val.g <- NULL
se$neg.log10.p.val.adj.g <- NULL
se$neg.log10.p.val.g_topgenes <- NULL
se$neg.log10.p.val.adj.g_topgenes <- NULL
se$neg.log10.p.val.d <- NULL
se$neg.log10.p.val.adj.d <- NULL

head(se[[]])

```

All same scale
```{r, fig.height=15,fig.width=14}
ST.FeaturePlot(object = se, features = c("neg.log10.p.val.adj.g.AST","neg.log10.p.val.adj.g_topgenes.AST","neg.log10.p.val.adj.d.AST","neg.log10.p.val.adj.g.BRD","neg.log10.p.val.adj.g_topgenes.BRD","neg.log10.p.val.adj.d.BRD","neg.log10.p.val.adj.g.COPD","neg.log10.p.val.adj.g_topgenes.COPD","neg.log10.p.val.adj.d.COPD","neg.log10.p.val.adj.g.LUD","neg.log10.p.val.adj.g_topgenes.LUD","neg.log10.p.val.adj.d.LUD"), pt.size = 1.3, cols = viridis(nr_of_pvals),value.scale = "all",grid.ncol =3)
```

Samplewise scaling
```{r, fig.height=15,fig.width=14}
ST.FeaturePlot(object = se, features = c("neg.log10.p.val.adj.g.AST","neg.log10.p.val.adj.g_topgenes.AST","neg.log10.p.val.adj.d.AST","neg.log10.p.val.adj.g.BRD","neg.log10.p.val.adj.g_topgenes.BRD","neg.log10.p.val.adj.d.BRD","neg.log10.p.val.adj.g.COPD","neg.log10.p.val.adj.g_topgenes.COPD","neg.log10.p.val.adj.d.COPD","neg.log10.p.val.adj.g.LUD","neg.log10.p.val.adj.g_topgenes.LUD","neg.log10.p.val.adj.d.LUD"), pt.size = 1.3, cols = viridis(nr_of_pvals),value.scale = "samplewise",grid.ncol =3)
```

PDF
```{r}
pdf(file = "meta_data_pval_all_traits_[HLA_Bronchi_A42_311].pdf", height = 15, width = 14)

ST.FeaturePlot(object = se, features = c("neg.log10.p.val.adj.g.AST","neg.log10.p.val.adj.g_topgenes.AST","neg.log10.p.val.adj.d.AST","neg.log10.p.val.adj.g.BRD","neg.log10.p.val.adj.g_topgenes.BRD","neg.log10.p.val.adj.d.BRD","neg.log10.p.val.adj.g.COPD","neg.log10.p.val.adj.g_topgenes.COPD","neg.log10.p.val.adj.d.COPD","neg.log10.p.val.adj.g.LUD","neg.log10.p.val.adj.g_topgenes.LUD","neg.log10.p.val.adj.d.LUD"), pt.size = 1.3, cols = viridis(nr_of_pvals),value.scale = "all",grid.ncol =3)

dev.off()
```



# Notes
```{r}
sessionInfo()
```

