---
title: "QC_filtering_random_250_supercluster_term"
output: html_document
date: '`r format(Sys.Date(), "%B %d, %Y")`'
---

Note: filter out cells based on below gene, UMI, mitochondrial and ribosomal thresholds.

Load libraries
```{r}
library(Seurat)
library(SeuratObject)
library(dplyr)
library(tidyverse)
```


Load SC se object:
```{r}
se <- readRDS("Merged_whole_human_brain_random_250/se_250_cells.RDS")
se
table(se$supercluster_term)
```


Collect QC metrics
```{r}
se[["percent.mt"]] <- PercentageFeatureSet(se, pattern = "^MT-")
se[["percent.rb"]] <- PercentageFeatureSet(se, pattern = "^RPL|^RPS")
```


Plot QC metrics
```{r, fig.width=10, fig.height=20}
VlnPlot(se, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rb"), ncol = 1, group.by = "supercluster_term")
```


```{r, fig.width=10, fig.height=20}
RidgePlot(se, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rb"), ncol = 1, group.by = "supercluster_term")
```


Filtering cells
```{r}
se
se <- subset(se, subset = nFeature_RNA > 200 & nFeature_RNA < 15000 & 
                    nCount_RNA > 500 & nCount_RNA < 125000 & 
                    percent.mt <= 5 & percent.rb <= 4)
se
```


Plot QC metrics
```{r, fig.width=10, fig.height=20}
VlnPlot(se, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rb"), ncol = 1, group.by = "supercluster_term")
```

```{r, fig.width=10, fig.height=20}
RidgePlot(se, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rb"), ncol = 1, group.by = "supercluster_term")
```

Filtering genes
```{r}
se
# Define a threshold for the total UMI count
min_umi <- 100

# Calculate the total UMIs per gene
gene_totals <- Matrix::rowSums(GetAssayData(se, slot = "counts"))

# Subset genes with total UMIs above the threshold
se <- subset(se, features = rownames(se)[gene_totals >= min_umi])
se
```


Plot QC metrics
```{r, fig.width=10, fig.height=20}
VlnPlot(se, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rb"), ncol = 1, group.by = "supercluster_term")
```

```{r, fig.width=10, fig.height=20}
RidgePlot(se, features = c("nFeature_RNA", "nCount_RNA", "percent.mt", "percent.rb"), ncol = 1, group.by = "supercluster_term")
```


```{r}
table(se$supercluster_term)
```



Save cluster annotations
```{r, eval=FALSE}
seurat_clusters <- as.data.frame(se$supercluster_term)
seurat_clusters$Barcode <- colnames(se)
seurat_clusters$seurat_clusters <- seurat_clusters$`se$supercluster_term`
seurat_clusters$`se$supercluster_term` <- NULL

write.table(seurat_clusters,file="seurat_clusters.csv", col.names = T, row.names = F,quote = FALSE,sep = ";")
```


Normalize data: se <- SCTransform(se,return.only.var.genes = T)
```{r, message=FALSE, include=FALSE, eval=FALSE}
se <- SCTransform(se,return.only.var.genes = T)
```

Save filtered and normalized se object
```{r, eval=FALSE}
saveRDS(se,file = "se_250_cells_filtered_normalized.RDS")
```

SessionInfo
```{r}
sessionInfo()
```

