---
title: "gene_gene_correlation_top_genes_combined"
output: html_document
author: "Linda Kvastad"
date: "2024-03-27"
---

NOTE: Plots Figure 4b.

Load libraries:
```{r, message=FALSE}
library(STutility)
library(dplyr)
library(readr)
library(tibble)
library(stringr)
library(scales)
library(reshape2)
library(RColorBrewer)
library(ComplexHeatmap)
library(viridis)
```

Load ST data:
```{r}

infoTable <- read.csv("spatial_data/infoTable.csv", sep = ";")


se <- InputFromTable(infotable = infoTable, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

```

Load image:
```{r}
se <- LoadImages(se, time.resolve = FALSE)
```

Normalize data: se <- SCTransform(se,return.only.var.genes = T)
```{r, message=FALSE, include=FALSE}
se <- SCTransform(se,return.only.var.genes = T)
```

Load OpenTargets gene sets
```{r class.source = 'fold-show'}
OpenTargets_ADHD_Genetic_ <- as.character(t(read.table(file = "OpenTargets_gene_sets/Mouse_OpenTargets_ADHD_Genetic.csv")))
OpenTargets_ADHD_Genetic_top_ <- OpenTargets_ADHD_Genetic_[1:200]
length(OpenTargets_ADHD_Genetic_top_)

OpenTargets_ASD_Genetic_ <- as.character(t(read.table(file = "OpenTargets_gene_sets/Mouse_OpenTargets_ASD_Genetic.csv")))
OpenTargets_ASD_Genetic_top_ <- OpenTargets_ASD_Genetic_[1:130]
length(OpenTargets_ASD_Genetic_top_)

OpenTargets_ALZ_Genetic_ <- as.character(t(read.table(file = "OpenTargets_gene_sets/Mouse_OpenTargets_ALZ_Genetic.csv")))
OpenTargets_ALZ_Genetic_top_ <- OpenTargets_ALZ_Genetic_[1:70]
length(OpenTargets_ALZ_Genetic_top_)

OpenTargets_BIP_Genetic_ <- as.character(t(read.table(file = "OpenTargets_gene_sets/Mouse_OpenTargets_BIP_Genetic.csv")))
OpenTargets_BIP_Genetic_top_ <- OpenTargets_BIP_Genetic_[1:80]
length(OpenTargets_BIP_Genetic_top_)

OpenTargets_SCZ_Genetic_ <- as.character(t(read.table(file = "OpenTargets_gene_sets/Mouse_OpenTargets_SCZ_Genetic.csv")))
OpenTargets_SCZ_Genetic_top_ <- OpenTargets_SCZ_Genetic_[1:140]
length(OpenTargets_SCZ_Genetic_top_)

all_genes_top <- unique(c(OpenTargets_ADHD_Genetic_top_,OpenTargets_ASD_Genetic_top_,OpenTargets_ALZ_Genetic_top_,OpenTargets_BIP_Genetic_top_,OpenTargets_SCZ_Genetic_top_))


OpenTargets_ADHD_Drugs_ <- as.character(t(read.table(file = "OpenTargets_gene_sets/Mouse_OpenTargets_ADHD_Drugs.csv")))
length(OpenTargets_ADHD_Drugs_)

OpenTargets_ASD_Drugs_ <- as.character(t(read.table(file = "OpenTargets_gene_sets/Mouse_OpenTargets_ASD_Drugs.csv")))
length(OpenTargets_ASD_Drugs_)

ALZ_drug_targets_ <- as.character(t(read.table(file = "OpenTargets_gene_sets/Mouse_OpenTargets_ALZ_Drugs.csv")))
length(ALZ_drug_targets_)

OpenTargets_BIP_Drugs_ <- as.character(t(read.table(file = "OpenTargets_gene_sets/Mouse_OpenTargets_BIP_Drugs.csv")))
length(OpenTargets_BIP_Drugs_)

OpenTargets_SCZ_Drugs_ <- as.character(t(read.table(file = "OpenTargets_gene_sets/Mouse_OpenTargets_SCZ_Drugs.csv")))
length(OpenTargets_SCZ_Drugs_)

neuropsychiatric_drug_targets <- unique(c(OpenTargets_ADHD_Drugs_,OpenTargets_ASD_Drugs_,OpenTargets_BIP_Drugs_,OpenTargets_SCZ_Drugs_))


```


Non-intersected genes
```{r}
# Add a not-in function
`%!in%` <- Negate(`%in%`)
```


```{r}
BIP_only_ <- unique(all_genes_top[all_genes_top %!in% OpenTargets_ADHD_Genetic_])
BIP_only_ <- unique(BIP_only_[BIP_only_ %!in% OpenTargets_ALZ_Genetic_])
BIP_only_ <- unique(BIP_only_[BIP_only_ %!in% OpenTargets_ASD_Genetic_])
BIP_only_ <- unique(BIP_only_[BIP_only_ %!in% OpenTargets_SCZ_Genetic_])
BIP_only_
```


Prepare data
```{r}
neuropsychiatric_drug_targets_legend <- as.character(all_genes_top %in% neuropsychiatric_drug_targets)
neuropsychiatric_drug_targets_legend <- replace(neuropsychiatric_drug_targets_legend,neuropsychiatric_drug_targets_legend=="TRUE","Drug targets")
neuropsychiatric_drug_targets_legend <- replace(neuropsychiatric_drug_targets_legend,neuropsychiatric_drug_targets_legend=="FALSE","nonTargets")

ALZ_drug_targets_legend <- as.character(all_genes_top %in% ALZ_drug_targets_)
ALZ_drug_targets_legend <- replace(ALZ_drug_targets_legend,ALZ_drug_targets_legend=="TRUE","Drug targets")
ALZ_drug_targets_legend <- replace(ALZ_drug_targets_legend,ALZ_drug_targets_legend=="FALSE","nonTargets")


intersect(all_genes_top,neuropsychiatric_drug_targets)
length(intersect(all_genes_top,neuropsychiatric_drug_targets))

intersect(all_genes_top,ALZ_drug_targets_)
length(intersect(all_genes_top,ALZ_drug_targets_))

```



Select data from OT gene list
```{r}
mydata <- FetchData(se,vars=all_genes_top)
```


Create spearman correlation heat map
```{r}
cormat <- cor(mydata,method = c("spearman"))
melted_cormat <- reshape2::melt(cormat)
melted_cormat$value <- ifelse(melted_cormat$Var1 == melted_cormat$Var2, NA, melted_cormat$value)

```


Prepare data
```{r}
# all genes for ADHD, ASD, BIP, SCZ and ALZ
ADHD_genes_legend <- as.character(all_genes_top %in% OpenTargets_ADHD_Genetic_)
ADHD_genes_legend <- replace(ADHD_genes_legend,ADHD_genes_legend=="TRUE","ADHD")
ADHD_genes_legend <- replace(ADHD_genes_legend,ADHD_genes_legend=="FALSE","nonADHD")

ASD_genes_legend <- as.character(all_genes_top %in% OpenTargets_ASD_Genetic_)
ASD_genes_legend <- replace(ASD_genes_legend,ASD_genes_legend=="TRUE","ASD")
ASD_genes_legend <- replace(ASD_genes_legend,ASD_genes_legend=="FALSE","nonASD")

ALZ_genes_legend <- as.character(all_genes_top %in% OpenTargets_ALZ_Genetic_)
ALZ_genes_legend <- replace(ALZ_genes_legend,ALZ_genes_legend=="TRUE","ALZ")
ALZ_genes_legend <- replace(ALZ_genes_legend,ALZ_genes_legend=="FALSE","nonALZ")

BIP_genes_legend <- as.character(all_genes_top %in% OpenTargets_BIP_Genetic_)
BIP_genes_legend <- replace(BIP_genes_legend,BIP_genes_legend=="TRUE","BIP")
BIP_genes_legend <- replace(BIP_genes_legend,BIP_genes_legend=="FALSE","nonBIP")

SCZ_genes_legend <- as.character(all_genes_top %in% OpenTargets_SCZ_Genetic_)
SCZ_genes_legend <- replace(SCZ_genes_legend,SCZ_genes_legend=="TRUE","SCZ")
SCZ_genes_legend <- replace(SCZ_genes_legend,SCZ_genes_legend=="FALSE","nonSCZ")


df_legend <- data.frame(ADHD_genes_legend,ASD_genes_legend,ALZ_genes_legend,BIP_genes_legend,SCZ_genes_legend)

```



```{r}
library(circlize)
col_fun = colorRamp2(c(-0.4, 0, 0.4), c("blue","white","red"))
col_fun(seq(-3, 3))
```


Complex Heatmaps
```{r}
#Heatmat annotations
ha = HeatmapAnnotation(
    Neuropsychiatric_drug_targets = neuropsychiatric_drug_targets_legend,
    ALZ_drug_targets = ALZ_drug_targets_legend,
    ADHD = ADHD_genes_legend,
    ASD = ASD_genes_legend,
    ALZ = ALZ_genes_legend,
    BIP = BIP_genes_legend,
    SCZ = SCZ_genes_legend,
    col = list(ALZ_drug_targets =c("Drug targets"="red","nonTargets"="white"),
               Neuropsychiatric_drug_targets =c("Drug targets"="red","nonTargets"="white"),
               ADHD = c("ADHD" = "blue", "nonADHD" = "white"),
               ASD = c("ASD" = "lightblue", "nonASD" = "white"),
               ALZ = c("ALZ" = "purple", "nonALZ" = "white"),
               BIP = c("BIP" = "darkgreen", "nonBIP" = "white"),
               SCZ = c("SCZ" = "orange", "nonSCZ" = "white")
    ),
    annotation_legend_param = list(at=c("Drug targets","ADHD","ASD","ALZ","BIP","SCZ"))
)

set.seed(123)

myheatmap <-  Heatmap(cormat,name="Spearman\nCorrelation",row_names_gp = gpar(fontsize = 2),column_names_gp = gpar(fontsize = 2),clustering_method_columns = "complete",clustering_method_rows = "complete",show_row_dend = F,show_column_names = T,top_annotation = ha,row_split = 7, column_split = 7,col = col_fun)

myheatmap
```




PDF
```{r, eval=FALSE}
pdf(file = "gene_gene_correlation_top_genes_combined[10X_Visium_mouse_brain_coronal]_complex_heatmap_genes_ADHD_ASD_ALZ_BIP_SCZ.pdf", height = 20, width = 20)

myheatmap

dev.off()
```



SessionInfo
```{r}
sessionInfo()
```

