---
title: "pval_distribution_[genetic_all_genes_non_selected]_compare"
author: "Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
 html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

NOTE: Creates the plot for supplementary figure 9 c, and calculates the pi1 statistics for non-selected trait-tissue pairs for the nominal p-value distribution of genetically associated genes (genetic all).

#Load libraries
```{r}
library(dplyr)
library(ggplot2)
library(qvalue)
```


#Load data
```{r}
pval_data_non_selected <- read.csv(file="pval_distribution_[all_datasets]_summary_non_selected_tissue_trait_pairs.csv",sep = ";")
```


Subset to all Genes selected and all Genes non-selected
```{r}
#subset all genes data
data_Genes_non_selected <- pval_data_non_selected[grep("all", pval_data_non_selected$gene_list),]

```


Change p-value scale
```{r}
# change from character to numeric
data_Genes_non_selected$p.val_genetic <- as.numeric(data_Genes_non_selected$neg.log10.p.val_genetic)

# change/add new p-value scale to dataframe
data_Genes_non_selected$p.val_genetic <- 10^(-data_Genes_non_selected$p.val_genetic)
```


Plot
```{r}
theme_set(theme_classic())

# Color by groups
p2 <- ggplot(data_Genes_non_selected, aes(x=p.val_genetic)) + 
                geom_histogram(alpha=1, color="black",position="identity", fill="grey") +
                ylab("trait-structure pairs")+
                xlab("p-values") +
                ggtitle("Genetic all genes") +
                ylim(0,500)+
                #coord_cartesian(ylim = c(0, 10))+
                theme_classic(base_size = 25)+
                theme(plot.title = element_text(size = 25))+
                geom_vline(xintercept = 0.05, linetype = "dashed", color = "red", size = 1)

p2
```



PDF
```{r, eval=FALSE}
pdf(file = "Fig_traits_with_genetic_all_Genes_non_selected.pdf", width=5,height=5)

p2

dev.off()
```


```{r}
pi0_estimate <- pi0est(p=data_Genes_non_selected$p.val_genetic, pi0.method = c("bootstrap"))
pi0_estimate

pi0 <- pi0_estimate$pi0
pi1 <- 1-pi0

pi1
```


#Notes
```{r}
sessionInfo()
```

