---
title: "Semla_cell_type_mapping_NNLS_subclass_label_10X_random_250_cells"
output: html_document
author: "Linda Kvastad"
date: "2024-08-20"
---

NOTE: Plots Fig 6 a and b.

Libraries
```{r}
library(semla)
library(tibble)
library(dplyr)
library(SingleCellExperiment)
library(Seurat)
library(purrr)
library(patchwork)
library(ggplot2)
library(RcppML)
```

Load data
```{r}
se_allen <- readRDS("se_allen_brain_atlas_random_250_subclass_label.rds")
se_spatial <- readRDS("10X_mouse_brain_coronal.rds")
```

Subset spatial data
```{r}
# Genes x Spots to start with
dim(se_spatial)

# keep spots with a total count of X
se_spatial <- SubsetSTData(se_spatial, expression = nCount_Spatial >= 500)
dim(se_spatial)

# keep genes with at least a total count of X
genes_to_keep <- rownames(se_spatial)[(GetAssayData(se_spatial, slot = "counts") %>% rowSums()) >= 100]
se_spatial <- SubsetSTData(se_spatial, features = genes_to_keep)
dim(se_spatial)

# keep genes expressed in at least X spots
genes_to_keep <- rownames(se_spatial)[rowSums(GetAssayData(se_spatial, slot = "counts") > 0) >= 5]
se_spatial <- SubsetSTData(se_spatial, features = genes_to_keep)
dim(se_spatial)
```

Normalize data
```{r}
# Normalize data and find variable features for Visium data
se_spatial <- se_spatial |>
  NormalizeData() |>
  FindVariableFeatures(nfeatures = 10000)

# Normalize data and run vanilla analysis to create UMAP embedding
se_allen <- se_allen |>
  NormalizeData() |>
  FindVariableFeatures() |> 
  ScaleData() |> 
  RunPCA() |> 
  RunUMAP(reduction = "pca", dims = 1:30)

# Rerun FindVariableFeatures to increase the number before cell type deconvolution
se_allen <- se_allen |> 
  FindVariableFeatures(nfeatures = 10000)
```

UMAP plot
```{r}
DimPlot(se_allen, group.by = "subclass_label")
```


Cell type mapping: Non-Negative Least Squares
```{r}
DefaultAssay(se_spatial) <- "Spatial"

ti <- Sys.time()
se_spatial <- RunNNLS(object = se_spatial, 
                            singlecell_object = se_allen, 
                            groups = "subclass_label")
```

List of cell types
```{r}
cell_type_features <- rownames(se_spatial[["celltypeprops"]])
length(cell_type_features)
print(cell_type_features)
```


Plot
```{r, fig.width=4, fig.height=4}
MapFeatures(se_spatial,features = cell_type_features[1])
MapFeatures(se_spatial,features = cell_type_features[2])
MapFeatures(se_spatial,features = cell_type_features[3])
MapFeatures(se_spatial,features = cell_type_features[4])
MapFeatures(se_spatial,features = cell_type_features[5])
MapFeatures(se_spatial,features = cell_type_features[6])
MapFeatures(se_spatial,features = cell_type_features[7])
MapFeatures(se_spatial,features = cell_type_features[8])
MapFeatures(se_spatial,features = cell_type_features[9])
MapFeatures(se_spatial,features = cell_type_features[10])

MapFeatures(se_spatial,features = cell_type_features[11])
MapFeatures(se_spatial,features = cell_type_features[12])
MapFeatures(se_spatial,features = cell_type_features[13])
MapFeatures(se_spatial,features = cell_type_features[14])
MapFeatures(se_spatial,features = cell_type_features[15])
MapFeatures(se_spatial,features = cell_type_features[16])
MapFeatures(se_spatial,features = cell_type_features[17])
MapFeatures(se_spatial,features = cell_type_features[18])
MapFeatures(se_spatial,features = cell_type_features[19])
MapFeatures(se_spatial,features = cell_type_features[20])

MapFeatures(se_spatial,features = cell_type_features[21])
MapFeatures(se_spatial,features = cell_type_features[22])
MapFeatures(se_spatial,features = cell_type_features[23])
MapFeatures(se_spatial,features = cell_type_features[24])
MapFeatures(se_spatial,features = cell_type_features[25])
MapFeatures(se_spatial,features = cell_type_features[26])
MapFeatures(se_spatial,features = cell_type_features[27])
MapFeatures(se_spatial,features = cell_type_features[28])
MapFeatures(se_spatial,features = cell_type_features[29])
MapFeatures(se_spatial,features = cell_type_features[30])

MapFeatures(se_spatial,features = cell_type_features[31])
MapFeatures(se_spatial,features = cell_type_features[32])
MapFeatures(se_spatial,features = cell_type_features[33])
MapFeatures(se_spatial,features = cell_type_features[34])
MapFeatures(se_spatial,features = cell_type_features[35])
MapFeatures(se_spatial,features = cell_type_features[36])
MapFeatures(se_spatial,features = cell_type_features[37])
MapFeatures(se_spatial,features = cell_type_features[38])
MapFeatures(se_spatial,features = cell_type_features[39])

MapFeatures(se_spatial,features = cell_type_features[40])
MapFeatures(se_spatial,features = cell_type_features[41])
MapFeatures(se_spatial,features = cell_type_features[42])
```

Cell type co-localization
```{r,fig.height=10,fig.width=10}
cor_matrix <- FetchData(se_spatial, cell_type_features) |> 
  mutate_all(~ if_else(.x<0.1, 0, .x)) |>  # Filter lowest values (-> set as 0)
  cor(method = "spearman")

cor_matrix[is.na(cor_matrix)] <- 0
diag(cor_matrix) <- NA
max_val <- max(cor_matrix, na.rm = T)
cols <- RColorBrewer::brewer.pal(7, "RdYlBu") |> rev(); cols[4] <- "white"
pheatmap::pheatmap(cor_matrix, 
                   breaks = seq(-max_val, max_val, length.out = 100),
                   color=colorRampPalette(cols)(100),
                   cellwidth = 14, cellheight = 14, 
                   treeheight_col = 10, treeheight_row = 10, 
                   main = "Cell type correlation\nwithin spots")
```


Add cell props metadata
```{r}
metadata_props <- FetchData(se_spatial, cell_type_features)

se_spatial <- AddMetaData(se_spatial, metadata = metadata_props)

```

Add seurat clusters to metadata
```{r}
seurat_clusters <- read.csv(file = "seurat_clusters_mouse_10X.csv", sep = ";")

seurat_clusters$Barcode <- gsub("_1$", "", seurat_clusters$Barcode)
rownames(seurat_clusters) <- seurat_clusters$Barcode
seurat_clusters$Barcode <- NULL
se_spatial$seurat_clusters <- seurat_clusters

se_spatial <- AddMetaData(se_spatial, metadata = seurat_clusters, col.name = "seurat_clusters")

head(se_spatial[[]])
```

Dotplot across clusters
```{r}
# Get the key of the assay
assay_key <- Key(se_spatial[["celltypeprops"]])

# Prepend the key to each feature in the cell_type_features vector
cell_type_features_plot <- gsub("^", assay_key, cell_type_features)

# Check the updated feature names
print(cell_type_features_plot)


```


```{r, fig.height=15,fig.width=9}
Idents(se_spatial) <- "seurat_clusters"

# Set the order of the clusters from 0 to 18
desired_order <- as.character(0:18)  # Convert to character for factors

# Now you can use the updated feature names in the DotPlot
p <- DotPlot(se_spatial, features = cell_type_features, cols = c("grey87","red2"), col.min = 0, col.max = 3, scale = T) + 
        #RotatedAxis() +
        theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
        xlab("cell types") +
        ylab("tissue substructures") +
        #coord_flip() +
        scale_y_discrete(limits = desired_order) +
        scale_x_discrete(limits = cell_type_features)

p
```

PDF
```{r, eval=FALSE}
pdf(file = "DotPlot_mouse_10X_NNLS_allen_subclass_label_random_250_cells_horizontal.pdf", height = 6, width = 12)

p

dev.off()
```


```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_VLMC.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[41],pt_stroke = 0, pt_size = 0.8)
dev.off()
```


```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_SMC_Peri.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[36],pt_stroke = 0, pt_size = 0.8)
dev.off()
```


```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_Endo.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[9],pt_stroke = 0, pt_size = 0.8)
dev.off()
```


```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_Oligo.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[34],pt_stroke = 0, pt_size = 0.8)
dev.off()
```



```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_Pvalb.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[35],pt_stroke = 0, pt_size = 0.8)
dev.off()
```



```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_L5_IT_CTX.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[19],pt_stroke = 0, pt_size = 0.8)
dev.off()
```


```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_L4_5_IT_CTX.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[18],pt_stroke = 0, pt_size = 0.8)
dev.off()
```

```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_L4_RSP_ACA.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[17],pt_stroke = 0, pt_size = 0.8)
dev.off()
```

```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_L2_3_IT_CTX.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[12],pt_stroke = 0, pt_size = 0.8)
dev.off()
```

```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_L2_3_IT_ENTI.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[13],pt_stroke = 0, pt_size = 0.8)
dev.off()
```

```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_L6_CT_CTX.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[24],pt_stroke = 0, pt_size = 0.8)
dev.off()
```

```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_L6b_CTX.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[27],pt_stroke = 0, pt_size = 0.8)
dev.off()
```

```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_L5_6_IT_TPE_ENT.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[22],pt_stroke = 0, pt_size = 0.8)
dev.off()
```

```{r, eval=FALSE}
png_res <- 600
png(filename = file.path("MapFeatures_Micro_PVM.png"), res = png_res, width = 4*png_res, height = 4*png_res)
MapFeatures(se_spatial,features = cell_type_features[31],pt_stroke = 0, pt_size = 0.8)
dev.off()
```



```{r}
DefaultAssay(se_spatial) <- "Spatial"

MapFeatures(se_spatial,features = "Tmem19",pt_stroke = 0, pt_size = 0.8)
MapFeatures(se_spatial,features = "P2ry12",pt_stroke = 0, pt_size = 0.8)
MapFeatures(se_spatial,features = "Hexb",pt_stroke = 0, pt_size = 0.8)
MapFeatures(se_spatial,features = "Sall1",pt_stroke = 0, pt_size = 0.8)
```


Notes:
```{r}
sessionInfo()
```

