---
title: "meta_data_pval_T1DM_T2DM_[pancreas_human_20PCW_S1]"
author: "Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
 html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
---

NOTE: Plots SupFig 11f.

# Load data

Load libraries:
```{r, message=FALSE}
library(dplyr)
library(tidyverse)
library(STutility)
library(viridis)
```

Load ST data:
```{r}

infoTable <- read.csv("spatial_data/infoTable.csv", sep = ";")


se <- InputFromTable(infotable = infoTable, 
                      minUMICountsPerGene = 100, 
                      minSpotsPerGene = 5,
                      minUMICountsPerSpot = 500,
                      platform =  "Visium")

```

Load image:
```{r}
se <- LoadImages(se, time.resolve = FALSE)
```

Load meta data:
```{r}

meta.data.T1DM <- readRDS(file = "Meta_data_pval/meta.data.pval_T1DM_all_genes.RDS")
meta.data.T1DM_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_T1DM_top130_genes.RDS")

rownames(meta.data.T1DM) <- meta.data.T1DM$CellID
rownames(meta.data.T1DM_topgenes) <- meta.data.T1DM_topgenes$CellID

meta.data.T2DM <- readRDS(file = "Meta_data_pval/meta.data.pval_T2DM_all_genes.RDS")
meta.data.T2DM_topgenes <- readRDS(file = "Meta_data_pval/meta.data.pval_T2DM_top90_genes.RDS")

rownames(meta.data.T2DM) <- meta.data.T2DM$CellID
rownames(meta.data.T2DM_topgenes) <- meta.data.T2DM_topgenes$CellID

nr_of_pvals <- 7*2
```


Merge meta data
```{r}
meta.data.T1DM$neg.log10.p.val.g_topgenes <- meta.data.T1DM_topgenes$neg.log10.p.val.g
meta.data.T1DM$neg.log10.p.val.adj.g_topgenes <- meta.data.T1DM_topgenes$neg.log10.p.val.adj.g

meta.data.T2DM$neg.log10.p.val.g_topgenes <- meta.data.T2DM_topgenes$neg.log10.p.val.g
meta.data.T2DM$neg.log10.p.val.adj.g_topgenes <- meta.data.T2DM_topgenes$neg.log10.p.val.adj.g
```

Re-name colnames
```{r}
meta.data.T1DM$neg.log10.p.val.g.T1DM <- meta.data.T1DM$neg.log10.p.val.g
meta.data.T1DM$neg.log10.p.val.adj.g.T1DM <- meta.data.T1DM$neg.log10.p.val.adj.g
meta.data.T1DM$neg.log10.p.val.d.T1DM <- meta.data.T1DM$neg.log10.p.val.d
meta.data.T1DM$neg.log10.p.val.adj.d.T1DM <- meta.data.T1DM$neg.log10.p.val.adj.d
meta.data.T1DM$neg.log10.p.val.g_topgenes.T1DM <- meta.data.T1DM$neg.log10.p.val.g_topgenes
meta.data.T1DM$neg.log10.p.val.adj.g_topgenes.T1DM <- meta.data.T1DM$neg.log10.p.val.adj.g_topgenes

meta.data.T2DM$neg.log10.p.val.g.T2DM <- meta.data.T2DM$neg.log10.p.val.g
meta.data.T2DM$neg.log10.p.val.adj.g.T2DM <- meta.data.T2DM$neg.log10.p.val.adj.g
meta.data.T2DM$neg.log10.p.val.d.T2DM <- meta.data.T2DM$neg.log10.p.val.d
meta.data.T2DM$neg.log10.p.val.adj.d.T2DM <- meta.data.T2DM$neg.log10.p.val.adj.d
meta.data.T2DM$neg.log10.p.val.g_topgenes.T2DM <- meta.data.T2DM$neg.log10.p.val.g_topgenes
meta.data.T2DM$neg.log10.p.val.adj.g_topgenes.T2DM <- meta.data.T2DM$neg.log10.p.val.adj.g_topgenes
```

Add meta data:
```{r}
se <- AddMetaData(se, metadata = meta.data.T1DM)

se <- AddMetaData(se, metadata = meta.data.T2DM)

se$neg.log10.p.val.g <- NULL
se$neg.log10.p.val.adj.g <- NULL
se$neg.log10.p.val.g_topgenes <- NULL
se$neg.log10.p.val.adj.g_topgenes <- NULL
se$neg.log10.p.val.d <- NULL
se$neg.log10.p.val.adj.d <- NULL

head(se[[]])

```


```{r, fig.height=8,fig.width=14}
ST.FeaturePlot(object = se, features = c("neg.log10.p.val.adj.g.T1DM","neg.log10.p.val.adj.g_topgenes.T1DM","neg.log10.p.val.adj.d.T1DM","neg.log10.p.val.adj.g.T2DM","neg.log10.p.val.adj.g_topgenes.T2DM","neg.log10.p.val.adj.d.T2DM"), pt.size = 1.5, cols = viridis(nr_of_pvals),value.scale = "all",grid.ncol =3)
```


```{r, fig.height=8,fig.width=14}
ST.FeaturePlot(object = se, features = c("neg.log10.p.val.adj.g.T1DM","neg.log10.p.val.adj.g_topgenes.T1DM","neg.log10.p.val.adj.d.T1DM","neg.log10.p.val.adj.g.T2DM","neg.log10.p.val.adj.g_topgenes.T2DM","neg.log10.p.val.adj.d.T2DM"), pt.size = 1.5, cols = viridis(nr_of_pvals),value.scale = "samplewise",grid.ncol =3)
```



PDF
```{r}
pdf(file = "meta_data_pval_T1DM_T2DM_[pancreas_human_20PCW_S1].pdf", height = 8, width = 14)

ST.FeaturePlot(object = se, features = c("neg.log10.p.val.adj.g.T1DM","neg.log10.p.val.adj.g_topgenes.T1DM","neg.log10.p.val.adj.d.T1DM","neg.log10.p.val.adj.g.T2DM","neg.log10.p.val.adj.g_topgenes.T2DM","neg.log10.p.val.adj.d.T2DM"), pt.size = 1.5, cols = viridis(nr_of_pvals),value.scale = "all",grid.ncol =3)

dev.off()
```


# Notes
```{r}
sessionInfo()
```

