---
title: "Compare_overlap_of_all_genes_by_trait_gsMap_top50genes"
output: html_document
author: "Linda Kvastad"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
---

```{r, warning=FALSE, message=FALSE}
library(dplyr)
library(ggplot2)
library(UpSetR)
library(readr)
library(grid)
```

Load gene sets.
```{r}
#human_brain
ADHD.steam_human_brain <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_brain_151673/Human_OpenTargets_ADHD_Genetic.csv")))

ALZ.steam_human_brain <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_brain_151673/Human_OpenTargets_ALZ_Genetic.csv")))

ASD.steam_human_brain <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_brain_151673/Human_OpenTargets_ASD_Genetic.csv")))

BIP.steam_human_brain <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_brain_151673/Human_OpenTargets_BIP_Genetic.csv")))

SCZ.steam_human_brain <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_brain_151673/Human_OpenTargets_SCZ_Genetic.csv")))

ADHD.gsMap_human_brain <- read.csv(file = "gsMap_diagnostic_info/human_brain_151673/human_cortex_ADHD_Gene_Diagnostic_Info.csv")
ADHD.gsMap_human_brain <- ADHD.gsMap_human_brain$Gene
ADHD.gsMap_human_brain <- ADHD.gsMap_human_brain[1:50]

ALZ.gsMap_human_brain <- read.csv(file = "gsMap_diagnostic_info/human_brain_151673/human_cortex_ALZ_Gene_Diagnostic_Info.csv")
ALZ.gsMap_human_brain <- ALZ.gsMap_human_brain$Gene
ALZ.gsMap_human_brain <- ALZ.gsMap_human_brain[1:50]

ASD.gsMap_human_brain <- read.csv(file = "gsMap_diagnostic_info/human_brain_151673/human_cortex_ASD_Gene_Diagnostic_Info.csv")
ASD.gsMap_human_brain <- ASD.gsMap_human_brain$Gene
ASD.gsMap_human_brain <- ASD.gsMap_human_brain[1:50]

BIP.gsMap_human_brain <- read.csv(file = "gsMap_diagnostic_info/human_brain_151673/human_cortex_BIP_Gene_Diagnostic_Info.csv")
BIP.gsMap_human_brain <- BIP.gsMap_human_brain$Gene
BIP.gsMap_human_brain <- BIP.gsMap_human_brain[1:50]

SCZ.gsMap_human_brain <- read.csv(file = "gsMap_diagnostic_info/human_brain_151673/human_cortex_SCZ_Gene_Diagnostic_Info.csv")
SCZ.gsMap_human_brain <- SCZ.gsMap_human_brain$Gene
SCZ.gsMap_human_brain <- SCZ.gsMap_human_brain[1:50]

#human_heart
ADHD.steam_human_heart <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_heart_ACH003/Human_OpenTargets_ADHD_Genetic.csv")))

ALZ.steam_human_heart <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_heart_ACH003/Human_OpenTargets_ALZ_Genetic.csv")))

ASD.steam_human_heart <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_heart_ACH003/Human_OpenTargets_ASD_Genetic.csv")))

BIP.steam_human_heart <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_heart_ACH003/Human_OpenTargets_BIP_Genetic.csv")))

SCZ.steam_human_heart <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_heart_ACH003/Human_OpenTargets_SCZ_Genetic.csv")))

ADHD.gsMap_human_heart <- read.csv(file = "gsMap_diagnostic_info/human_heart_ACH003/human_heart_ADHD_Gene_Diagnostic_Info.csv")
ADHD.gsMap_human_heart <- ADHD.gsMap_human_heart$Gene
ADHD.gsMap_human_heart <- ADHD.gsMap_human_heart[1:50]

ALZ.gsMap_human_heart <- read.csv(file = "gsMap_diagnostic_info/human_heart_ACH003/human_heart_ALZ_Gene_Diagnostic_Info.csv")
ALZ.gsMap_human_heart <- ALZ.gsMap_human_heart$Gene
ALZ.gsMap_human_heart <- ALZ.gsMap_human_heart[1:50]

ASD.gsMap_human_heart <- read.csv(file = "gsMap_diagnostic_info/human_heart_ACH003/human_heart_ASD_Gene_Diagnostic_Info.csv")
ASD.gsMap_human_heart <- ASD.gsMap_human_heart$Gene
ASD.gsMap_human_heart <- ASD.gsMap_human_heart[1:50]

BIP.gsMap_human_heart <- read.csv(file = "gsMap_diagnostic_info/human_heart_ACH003/human_heart_BIP_Gene_Diagnostic_Info.csv")
BIP.gsMap_human_heart <- BIP.gsMap_human_heart$Gene
BIP.gsMap_human_heart <- BIP.gsMap_human_heart[1:50]

SCZ.gsMap_human_heart <- read.csv(file = "gsMap_diagnostic_info/human_heart_ACH003/human_heart_SCZ_Gene_Diagnostic_Info.csv")
SCZ.gsMap_human_heart <- SCZ.gsMap_human_heart$Gene
SCZ.gsMap_human_heart <- SCZ.gsMap_human_heart[1:50]

#human_liver
ADHD.steam_human_liver <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_liver_JBO0018/Human_OpenTargets_ADHD_Genetic.csv")))

ALZ.steam_human_liver <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_liver_JBO0018/Human_OpenTargets_ALZ_Genetic.csv")))

ASD.steam_human_liver <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_liver_JBO0018/Human_OpenTargets_ASD_Genetic.csv")))

BIP.steam_human_liver <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_liver_JBO0018/Human_OpenTargets_BIP_Genetic.csv")))

SCZ.steam_human_liver <- as.character(t(read.table(file = "OpenTargets_gene_sets/human_liver_JBO0018/Human_OpenTargets_SCZ_Genetic.csv")))

ADHD.gsMap_human_liver <- read.csv(file = "gsMap_diagnostic_info/human_liver_JBO0018/human_liver_ADHD_Gene_Diagnostic_Info.csv")
ADHD.gsMap_human_liver <- ADHD.gsMap_human_liver$Gene
ADHD.gsMap_human_liver <- ADHD.gsMap_human_liver[1:50]

ALZ.gsMap_human_liver <- read.csv(file = "gsMap_diagnostic_info/human_liver_JBO0018/human_liver_ALZ_Gene_Diagnostic_Info.csv")
ALZ.gsMap_human_liver <- ALZ.gsMap_human_liver$Gene
ALZ.gsMap_human_liver <- ALZ.gsMap_human_liver[1:50]

ASD.gsMap_human_liver <- read.csv(file = "gsMap_diagnostic_info/human_liver_JBO0018/human_liver_ASD_Gene_Diagnostic_Info.csv")
ASD.gsMap_human_liver <- ASD.gsMap_human_liver$Gene
ASD.gsMap_human_liver <- ASD.gsMap_human_liver[1:50]

BIP.gsMap_human_liver <- read.csv(file = "gsMap_diagnostic_info/human_liver_JBO0018/human_liver_BIP_Gene_Diagnostic_Info.csv")
BIP.gsMap_human_liver <- BIP.gsMap_human_liver$Gene
BIP.gsMap_human_liver <- BIP.gsMap_human_liver[1:50]

SCZ.gsMap_human_liver <- read.csv(file = "gsMap_diagnostic_info/human_liver_JBO0018/human_liver_SCZ_Gene_Diagnostic_Info.csv")
SCZ.gsMap_human_liver <- SCZ.gsMap_human_liver$Gene
SCZ.gsMap_human_liver <- SCZ.gsMap_human_liver[1:50]

#mouse_brain
ADHD.steam_mouse_brain <- as.character(t(read.table(file = "OpenTargets_gene_sets/mouse_brain_10X/Mouse_OpenTargets_ADHD_Genetic.csv")))

ALZ.steam_mouse_brain <- as.character(t(read.table(file = "OpenTargets_gene_sets/mouse_brain_10X/Mouse_OpenTargets_ALZ_Genetic.csv")))

ASD.steam_mouse_brain <- as.character(t(read.table(file = "OpenTargets_gene_sets/mouse_brain_10X/Mouse_OpenTargets_ASD_Genetic.csv")))

BIP.steam_mouse_brain <- as.character(t(read.table(file = "OpenTargets_gene_sets/mouse_brain_10X/Mouse_OpenTargets_BIP_Genetic.csv")))

SCZ.steam_mouse_brain <- as.character(t(read.table(file = "OpenTargets_gene_sets/mouse_brain_10X/Mouse_OpenTargets_SCZ_Genetic.csv")))

ADHD.gsMap_mouse_brain <- read.csv(file = "gsMap_diagnostic_info/mouse_brain_10X/mouse_coronal_ADHD_Gene_Diagnostic_Info.csv")
ADHD.gsMap_mouse_brain <- ADHD.gsMap_mouse_brain$Gene
ADHD.gsMap_mouse_brain <- ADHD.gsMap_mouse_brain[1:50]

ALZ.gsMap_mouse_brain <- read.csv(file = "gsMap_diagnostic_info/mouse_brain_10X/mouse_coronal_ALZ_Gene_Diagnostic_Info.csv")
ALZ.gsMap_mouse_brain <- ALZ.gsMap_mouse_brain$Gene
ALZ.gsMap_mouse_brain <- ALZ.gsMap_mouse_brain[1:50]

ASD.gsMap_mouse_brain <- read.csv(file = "gsMap_diagnostic_info/mouse_brain_10X/mouse_coronal_ASD_Gene_Diagnostic_Info.csv")
ASD.gsMap_mouse_brain <- ASD.gsMap_mouse_brain$Gene
ASD.gsMap_mouse_brain <- ASD.gsMap_mouse_brain[1:50]

BIP.gsMap_mouse_brain <- read.csv(file = "gsMap_diagnostic_info/mouse_brain_10X/mouse_coronal_BIP_Gene_Diagnostic_Info.csv")
BIP.gsMap_mouse_brain <- BIP.gsMap_mouse_brain$Gene
BIP.gsMap_mouse_brain <- BIP.gsMap_mouse_brain[1:50]

SCZ.gsMap_mouse_brain <- read.csv(file = "gsMap_diagnostic_info/mouse_brain_10X/mouse_coronal_SCZ_Gene_Diagnostic_Info.csv")
SCZ.gsMap_mouse_brain <- SCZ.gsMap_mouse_brain$Gene
SCZ.gsMap_mouse_brain <- SCZ.gsMap_mouse_brain[1:50]

#mouse_liver
ADHD.steam_mouse_liver <- as.character(t(read.table(file = "OpenTargets_gene_sets/mouse_liver_JBO002/Mouse_OpenTargets_ADHD_Genetic.csv")))

ALZ.steam_mouse_liver <- as.character(t(read.table(file = "OpenTargets_gene_sets/mouse_liver_JBO002/Mouse_OpenTargets_ALZ_Genetic.csv")))

ASD.steam_mouse_liver <- as.character(t(read.table(file = "OpenTargets_gene_sets/mouse_liver_JBO002/Mouse_OpenTargets_ASD_Genetic.csv")))

BIP.steam_mouse_liver <- as.character(t(read.table(file = "OpenTargets_gene_sets/mouse_liver_JBO002/Mouse_OpenTargets_BIP_Genetic.csv")))

SCZ.steam_mouse_liver <- as.character(t(read.table(file = "OpenTargets_gene_sets/mouse_liver_JBO002/Mouse_OpenTargets_SCZ_Genetic.csv")))

ADHD.gsMap_mouse_liver <- read.csv(file = "gsMap_diagnostic_info/mouse_liver_JBO002/mouse_liver_ADHD_Gene_Diagnostic_Info.csv")
ADHD.gsMap_mouse_liver <- ADHD.gsMap_mouse_liver$Gene
ADHD.gsMap_mouse_liver <- ADHD.gsMap_mouse_liver[1:50]

ALZ.gsMap_mouse_liver <- read.csv(file = "gsMap_diagnostic_info/mouse_liver_JBO002/mouse_liver_ALZ_Gene_Diagnostic_Info.csv")
ALZ.gsMap_mouse_liver <- ALZ.gsMap_mouse_liver$Gene
ALZ.gsMap_mouse_liver <- ALZ.gsMap_mouse_liver[1:50]

ASD.gsMap_mouse_liver <- read.csv(file = "gsMap_diagnostic_info/mouse_liver_JBO002/mouse_liver_ASD_Gene_Diagnostic_Info.csv")
ASD.gsMap_mouse_liver <- ASD.gsMap_mouse_liver$Gene
ASD.gsMap_mouse_liver <- ASD.gsMap_mouse_liver[1:50]

BIP.gsMap_mouse_liver <- read.csv(file = "gsMap_diagnostic_info/mouse_liver_JBO002/mouse_liver_BIP_Gene_Diagnostic_Info.csv")
BIP.gsMap_mouse_liver <- BIP.gsMap_mouse_liver$Gene
BIP.gsMap_mouse_liver <- BIP.gsMap_mouse_liver[1:50]

SCZ.gsMap_mouse_liver <- read.csv(file = "gsMap_diagnostic_info/mouse_liver_JBO002/mouse_liver_SCZ_Gene_Diagnostic_Info.csv")
SCZ.gsMap_mouse_liver <- SCZ.gsMap_mouse_liver$Gene
SCZ.gsMap_mouse_liver <- SCZ.gsMap_mouse_liver[1:50]

```


Convert gsMap genes back to mouse genes
```{r}
homolog_file <- read.table(file = "mouse_human_homologs_gsMap.txt", header = T)

# List of your gene sets
gene_sets <- list(
  ADHD_brain = ADHD.gsMap_mouse_brain,
  ALZ_brain  = ALZ.gsMap_mouse_brain,
  ASD_brain  = ASD.gsMap_mouse_brain,
  BIP_brain  = BIP.gsMap_mouse_brain,
  SCZ_brain  = SCZ.gsMap_mouse_brain,
  ADHD_liver = ADHD.gsMap_mouse_liver,
  ALZ_liver  = ALZ.gsMap_mouse_liver,
  ASD_liver  = ASD.gsMap_mouse_liver,
  BIP_liver  = BIP.gsMap_mouse_liver,
  SCZ_liver  = SCZ.gsMap_mouse_liver
)

# Map human genes to mouse genes
gene_sets_mouse <- lapply(gene_sets, function(genes) {
  homolog_file$MOUSE_GENE_SYM[match(genes, homolog_file$HUMAN_GENE_SYM)]
})

# Overwrite original variables with mouse versions
ADHD.gsMap_mouse_brain <- unique(gene_sets_mouse$ADHD_brain)
ALZ.gsMap_mouse_brain  <- unique(gene_sets_mouse$ALZ_brain)
ASD.gsMap_mouse_brain  <- unique(gene_sets_mouse$ASD_brain)
BIP.gsMap_mouse_brain  <- unique(gene_sets_mouse$BIP_brain)
SCZ.gsMap_mouse_brain  <- unique(gene_sets_mouse$SCZ_brain)
ADHD.gsMap_mouse_liver <- unique(gene_sets_mouse$ADHD_liver)
ALZ.gsMap_mouse_liver  <- unique(gene_sets_mouse$ALZ_liver)
ASD.gsMap_mouse_liver  <- unique(gene_sets_mouse$ASD_liver)
BIP.gsMap_mouse_liver  <- unique(gene_sets_mouse$BIP_liver)
SCZ.gsMap_mouse_liver  <- unique(gene_sets_mouse$SCZ_liver)

```


Divide gene sets by method and species, then merge gene sets by trait from all tissues.
```{r}
#steam
ADHD.steam_human <- unique(c(ADHD.steam_human_brain,ADHD.steam_human_heart,ADHD.steam_human_liver))
ALZ.steam_human <- unique(c(ALZ.steam_human_brain,ALZ.steam_human_heart,ALZ.steam_human_liver))
ASD.steam_human <- unique(c(ASD.steam_human_brain,ASD.steam_human_heart,ASD.steam_human_liver))
BIP.steam_human <- unique(c(BIP.steam_human_brain,BIP.steam_human_heart,BIP.steam_human_liver))
SCZ.steam_human <- unique(c(SCZ.steam_human_brain,SCZ.steam_human_heart,SCZ.steam_human_liver))

ADHD.steam_mouse <- unique(c(ADHD.steam_mouse_brain,ADHD.steam_mouse_liver))
ALZ.steam_mouse <- unique(c(ALZ.steam_mouse_brain,ALZ.steam_mouse_liver))
ASD.steam_mouse <- unique(c(ASD.steam_mouse_brain,ASD.steam_mouse_liver))
BIP.steam_mouse <- unique(c(BIP.steam_mouse_brain,BIP.steam_mouse_liver))
SCZ.steam_mouse <- unique(c(SCZ.steam_mouse_brain,SCZ.steam_mouse_liver))

#gsMap
ADHD.gsMap_human <- unique(c(ADHD.gsMap_human_brain,ADHD.gsMap_human_heart,ADHD.gsMap_human_liver))
ALZ.gsMap_human <- unique(c(ALZ.gsMap_human_brain,ALZ.gsMap_human_heart,ALZ.gsMap_human_liver))
ASD.gsMap_human <- unique(c(ASD.gsMap_human_brain,ASD.gsMap_human_heart,ASD.gsMap_human_liver))
BIP.gsMap_human <- unique(c(BIP.gsMap_human_brain,BIP.gsMap_human_heart,BIP.gsMap_human_liver))
SCZ.gsMap_human <- unique(c(SCZ.gsMap_human_brain,SCZ.gsMap_human_heart,SCZ.gsMap_human_liver))

ADHD.gsMap_mouse <- unique(c(ADHD.gsMap_mouse_brain,ADHD.gsMap_mouse_liver))
ALZ.gsMap_mouse <- unique(c(ALZ.gsMap_mouse_brain,ALZ.gsMap_mouse_liver))
ASD.gsMap_mouse <- unique(c(ASD.gsMap_mouse_brain,ASD.gsMap_mouse_liver))
BIP.gsMap_mouse <- unique(c(BIP.gsMap_mouse_brain,BIP.gsMap_mouse_liver))
SCZ.gsMap_mouse <- unique(c(SCZ.gsMap_mouse_brain,SCZ.gsMap_mouse_liver))

```


Check gene overlap between datasets

Human ALZ
```{r, fig.height=6, fig.width=7}
# Make a list
gene_sets <- list(
  STEAM.ALZ = ALZ.steam_human,
  gsMap.ALZ = ALZ.gsMap_human
)

# Convert to UpSetR-compatible format
input_upset <- fromList(gene_sets)

# Plot overlap
p1 <- upset(
  input_upset,
  sets = rev(names(gene_sets)),   # use same order as input list
  keep.order = TRUE,         # key to preserve order
  order.by = "freq",
  sets.bar.color = c("#ff7f00","#1f78b4"),
  text.scale = c(3, 3, 3, 1.6, 3, 3)
)

p1

```

PDF
```{r}
pdf(file = "plots/Compare_overlap_all_genes_gsMap_top50genes_by_trait_human_ALZ.pdf", height = 6, width = 9)

p1

dev.off()

```

Human ADHD
```{r, fig.height=6, fig.width=7}
# Make a list
gene_sets <- list(
  STEAM.ADHD = ADHD.steam_human,
  gsMap.ADHD = ADHD.gsMap_human
)

# Convert to UpSetR-compatible format
input_upset <- fromList(gene_sets)

# Plot overlap
p2 <- upset(
  input_upset,
  sets = rev(names(gene_sets)),   # use same order as input list
  keep.order = TRUE,         # key to preserve order
  order.by = "freq",
  sets.bar.color = c("#ff7f00","#1f78b4"),
  text.scale = c(3, 3, 3, 1.6, 3, 3)
)

p2

```

PDF
```{r}
pdf(file = "plots/Compare_overlap_all_genes_gsMap_top50genes_by_trait_human_ADHD.pdf", height = 6, width = 9)

p2

dev.off()

```

Human ASD
```{r, fig.height=6, fig.width=7}
# Make a list
gene_sets <- list(
  STEAM.ASD = ASD.steam_human,
  gsMap.ASD = ASD.gsMap_human
)

# Convert to UpSetR-compatible format
input_upset <- fromList(gene_sets)

# Plot overlap
p3 <- upset(
  input_upset,
  sets = rev(names(gene_sets)),   # use same order as input list
  keep.order = TRUE,         # key to preserve order
  order.by = "freq",
  sets.bar.color = c("#ff7f00","#1f78b4"),
  text.scale = c(3, 3, 3, 1.6, 3, 3)
)

p3

```

PDF
```{r}
pdf(file = "plots/Compare_overlap_all_genes_gsMap_top50genes_by_trait_human_ASD.pdf", height = 6, width = 9)

p3

dev.off()

```

Human BIP
```{r, fig.height=6, fig.width=7}
# Make a list
gene_sets <- list(
  STEAM.BIP = BIP.steam_human,
  gsMap.BIP = BIP.gsMap_human
)

# Convert to UpSetR-compatible format
input_upset <- fromList(gene_sets)

# Plot overlap
p4 <- upset(
  input_upset,
  sets = rev(names(gene_sets)),   # use same order as input list
  keep.order = TRUE,         # key to preserve order
  order.by = "freq",
  sets.bar.color = c("#ff7f00","#1f78b4"),
  text.scale = c(3, 3, 3, 1.6, 3, 3)
)

p4

```

PDF
```{r}
pdf(file = "plots/Compare_overlap_all_genes_gsMap_top50genes_by_trait_human_BIP.pdf", height = 6, width = 9)

p4

dev.off()

```


Human SCZ
```{r, fig.height=6, fig.width=7}
# Make a list
gene_sets <- list(
  STEAM.SCZ = SCZ.steam_human,
  gsMap.SCZ = SCZ.gsMap_human
)

# Convert to UpSetR-compatible format
input_upset <- fromList(gene_sets)

# Plot overlap
p5 <- upset(
  input_upset,
  sets = rev(names(gene_sets)),   # use same order as input list
  keep.order = TRUE,         # key to preserve order
  order.by = "freq",
  sets.bar.color = c("#ff7f00","#1f78b4"),
  text.scale = c(3, 3, 3, 1.6, 3, 3)
)

p5

```

PDF
```{r}
pdf(file = "plots/Compare_overlap_all_genes_gsMap_top50genes_by_trait_human_SCZ.pdf", height = 6, width = 9)

p5

dev.off()

```


Mouse ALZ
```{r, fig.height=6, fig.width=7}
# Make a list
gene_sets <- list(
  STEAM.ALZ = ALZ.steam_mouse,
  gsMap.ALZ = ALZ.gsMap_mouse
)

# Convert to UpSetR-compatible format
input_upset <- fromList(gene_sets)

# Plot overlap
p6 <- upset(
  input_upset,
  sets = rev(names(gene_sets)),   # use same order as input list
  keep.order = TRUE,         # key to preserve order
  order.by = "freq",
  sets.bar.color = c("#ff7f00","#1f78b4"),
  text.scale = c(3, 3, 3, 1.6, 3, 3)
)

p6

```

PDF
```{r}
pdf(file = "plots/Compare_overlap_all_genes_gsMap_top50genes_by_trait_mouse_ALZ.pdf", height = 6, width = 9)

p6

dev.off()

```


Mouse ADHD
```{r, fig.height=6, fig.width=7}
# Make a list
gene_sets <- list(
  STEAM.ADHD = ADHD.steam_mouse,
  gsMap.ADHD = ADHD.gsMap_mouse
)

# Convert to UpSetR-compatible format
input_upset <- fromList(gene_sets)

# Plot overlap
p7 <- upset(
  input_upset,
  sets = rev(names(gene_sets)),   # use same order as input list
  keep.order = TRUE,         # key to preserve order
  order.by = "freq",
  sets.bar.color = c("#ff7f00","#1f78b4"),
  text.scale = c(3, 3, 3, 1.6, 3, 3)
)

p7

```

PDF
```{r}
pdf(file = "plots/Compare_overlap_all_genes_gsMap_top50genes_by_trait_mouse_ADHD.pdf", height = 6, width = 9)

p7

dev.off()

```


Mouse ASD
```{r, fig.height=6, fig.width=7}
# Make a list
gene_sets <- list(
  STEAM.ASD = ASD.steam_mouse,
  gsMap.ASD = ASD.gsMap_mouse
)

# Convert to UpSetR-compatible format
input_upset <- fromList(gene_sets)

# Plot overlap
p8 <- upset(
  input_upset,
  sets = rev(names(gene_sets)),   # use same order as input list
  keep.order = TRUE,         # key to preserve order
  order.by = "freq",
  sets.bar.color = c("#ff7f00","#1f78b4"),
  text.scale = c(3, 3, 3, 1.6, 3, 3)
)

p8

```

PDF
```{r}
pdf(file = "plots/Compare_overlap_all_genes_gsMap_top50genes_by_trait_mouse_ASD.pdf", height = 6, width = 9)

p8

dev.off()

```


Mouse BIP
```{r, fig.height=6, fig.width=7}
# Make a list
gene_sets <- list(
  STEAM.BIP = BIP.steam_mouse,
  gsMap.BIP = BIP.gsMap_mouse
)

# Convert to UpSetR-compatible format
input_upset <- fromList(gene_sets)

# Plot overlap
p9 <- upset(
  input_upset,
  sets = rev(names(gene_sets)),   # use same order as input list
  keep.order = TRUE,         # key to preserve order
  order.by = "freq",
  sets.bar.color = c("#ff7f00","#1f78b4"),
  text.scale = c(3, 3, 3, 1.6, 3, 3)
)

p9

```

PDF
```{r}
pdf(file = "plots/Compare_overlap_all_genes_gsMap_top50genes_by_trait_mouse_BIP.pdf", height = 6, width = 9)

p9

dev.off()

```


Mouse SCZ
```{r, fig.height=6, fig.width=9}
# Make a list
gene_sets <- list(
  STEAM.SCZ = SCZ.steam_mouse,
  gsMap.SCZ = SCZ.gsMap_mouse
)

# Convert to UpSetR-compatible format
input_upset <- fromList(gene_sets)

# Plot overlap
p10 <- upset(
  input_upset,
  sets = rev(names(gene_sets)),   # use same order as input list
  keep.order = TRUE,         # key to preserve order
  order.by = "freq",
  sets.bar.color = c("#ff7f00","#1f78b4"),
  text.scale = c(3, 3, 3, 1.6, 3, 3)
)

p10

```

PDF
```{r}
pdf(file = "plots/Compare_overlap_all_genes_gsMap_top50genes_by_trait_mouse_SCZ.pdf", height = 6, width = 9)

p10

dev.off()

```


Notes
```{r}
sessionInfo()
```

